### ISSUE TITLE
Failed to sync iCloud sync

### ISSUE THREAD

**Issue by yaroslavyaroslav** [Ranchero-Software/NetNewsWire#3873] opened 2023-02-20 05:52 UTC
I guess the app somehow now syncing some of a folders or feeds between iPhone and iPad.

It's like Twitter is in sync, the major part of a library in terms of feeds are the same, but it failed Ty sync some recently added feeds and failed to sync read/unread articles.

![image](https://user-images.githubusercontent.com/16612247/220020270-41243dc7-095c-4bd8-bd58-ec4412e70453.png)
![image](https://user-images.githubusercontent.com/16612247/220020528-9b366cd5-b0ac-45b5-b86b-455322918737.jpeg)

**Comment by yaroslavyaroslav** [comment] 2023-02-20 06:06
Guess it’s #3839 related.

**Comment by brentsimmons** [comment] 2023-03-02 05:17
Duplicate of #3839

**Closed by brentsimmons** 2023-03-02 05:17 UTC
