### ISSUE TITLE
NSToolbar should display divider for when content flows under it

### ISSUE THREAD

**Issue by marioaguzman** [Ranchero-Software/NetNewsWire#3700] opened 2022-09-30 05:23 UTC
App: NetNewsWire for macOS

When content scrolls under the toolbar, a thin divider or shadow (both API options for the NSSplitViewItem that isn't a sidebar) under the toolbar. When the scrolling position is at the top, this divider should disappear. Currently there isn't one and content appears to be "chopped off" as it goes under the toolbar of the window.

When content scrolls under the toolbar, it should be somewhat visible through the toolbar given its translucent nature. Apps you can see as reference for this would be the Notes app or Mail if you use the 3-column layout. Here's another example:

<img width="898" alt="translucency in toolbar" src="https://user-images.githubusercontent.com/11789071/193196228-fa201b13-7f44-4f8b-872e-57fa71998af6.png">

**Comment by marioaguzman** [comment] 2022-09-30 05:27
To show the separator  for the content columns of a Split View is to set the Title Separator in the Storyboard by selecting the NSSplitViewItem and then going to Title Separator in the Attributes Inspector.

<img width="845" alt="Title Separator in Attributes Inspector" src="https://user-images.githubusercontent.com/11789071/193196632-1576fcc7-7bd6-4a8c-a5f4-134fe00ac2bd.png">

**Comment by vincode-io** [comment] 2022-09-30 16:27
This used to work correctly. Sigh... Right now we have the Window and all Split View Items set to `automatic` which does the right thing. It draws the line or at least it does for the Sidebar (our leftmost Split View Item).

I suspect the problem is that the Timeline (the middle Split View Item) has a container view that contains our actual NSTableView. Most likely the toolbar can't find the correct NSScrollView to observe to know when to draw the line.

I think we can get by without the container view and will try that to get the toolbar divider line to work correctly for the Timeline.

**Comment by marioaguzman** [comment] 2022-09-30 16:38
That actually makes sense. As of some version in macOS Monterey, something in AppKit broke and my sidebar was no longer showing the divider either. I found that removing all subviews BUT the outline view fixed it. All edges of my outline view had to be directly "touching" the container for the divider to appear properly. Yes, all sides. I had a bottom bar that I had to sort of "float" above my outline view and the adjust the bottom scroll inset as to not have it cover it. It was very annoying. I believe I submitted a bug on this because this never happened in like the first two dot versions of Monterey. I'd have to go dig up the FB#. I suspect that is what is probably happening here then? Maybe... 

But it's also not showing the table view content behind the toolbar's translucency and I suspect that is probably the same issue.

**Comment by marioaguzman** [comment] 2022-10-01 04:43
Hey @vincode-io, I think I figured it out.

This is consistent with what I had to do with my transit app for macOS. The content view on the view controllers that correspond to the NSSplitViewItems need to have Safe Area Layout Guide enabled in the Size Inspector.

<img width="355" alt="Screen Shot 2022-09-30 at 9 37 57 PM" src="https://user-images.githubusercontent.com/11789071/193392829-0ce28292-4720-48f0-ac02-275eaed4b13e.png">
<img width="355" alt="Screen Shot 2022-09-30 at 9 38 16 PM" src="https://user-images.githubusercontent.com/11789071/193392833-0a39ace8-b083-444b-81f1-cb15bc3c247a.png">

For the "DetailContentView," I did have to make a subview specifically for the Container View rather than using the content view as the container view.

Then, as I suspected and stated in my original message, it seems like the scrolling view needs to anchor directly to the top rather than have a subview in between the parent frame that goes under the toolbar. 

When you set the contentView in DetailContainerView, instead of anchoring the top of the web view to the findBarContainerView, just do it to the superview.topAnchor.

<img width="1365" alt="Screen Shot 2022-09-30 at 9 42 32 PM" src="https://user-images.githubusercontent.com/11789071/193392910-6e631846-a31d-48eb-9760-32b4d402c343.png">

Voilà! The separators now show properly only when content scrolls under them. I suspect another issue is preventing from content shining through the toolbar though.

**Comment by marioaguzman** [comment] 2022-10-01 05:15
I have the translucency also figured out for the TimelineContainerView. Don't worry, I've cloned the project and set it up according to the documentation in the repo readme.
But now you can see the divider appear only when content scrolls under and the translucency shine through. 😊 
<img width="708" alt="Screen Shot 2022-09-30 at 10 13 24 PM" src="https://user-images.githubusercontent.com/11789071/193393739-ceed0e0c-7d0d-437b-9722-210dfd823e1d.png">

**Comment by marioaguzman** [comment] 2022-10-01 05:50
The divider now shows per row and content now shines through the toolbar per row as well.

<img width="1011" alt="Screen Shot 2022-09-30 at 10 47 53 PM" src="https://user-images.githubusercontent.com/11789071/193394769-199b2980-49ea-4774-be1c-043a422e4c4f.png">

**Comment by vincode-io** [comment] 2022-10-01 10:24
That is awesome! Thanks for figuring that out for us. The only problem I see is that you haven't submitted a pull request for this yet. 😉

You could have the distinct honor of being contributor 76 on the NetNewsWire project. Slot 76 is only open for a limited time, so act fast!

**Comment by marioaguzman** [comment] 2022-10-01 15:01
I definitely will. I'm just still testing a bit more and notating where I want to leave comments for the reviewers regarding the changes.

**Comment by vincode-io** [comment] 2022-10-04 21:17
Fixed by the OP.

**Closed by vincode-io** 2022-10-04 21:17 UTC
