### ISSUE TITLE
article(s) read status not synced back to feedly

### ISSUE THREAD

**Issue by justme-1968** [Ranchero-Software/NetNewsWire#2462] opened 2020-09-28 14:37 UTC
the status of articles read with netnewswire and marked as read is not synced back to feedly and other readers that that also use the same feedlot account. this is true also for other netnewswire instances on other machines.

articles read with other readers using feely sync and the fieldy website are correctly marked as read in netnewswire.

this happens on a mac.

**Comment by vincode-io** [comment] 2020-09-28 16:07
How long are you waiting before checking before checking the status?  You need to wait at least two minutes before shutting down NetNewsWire for the read status to get sent to Feedly or do a manual sync before shutting down.

**Comment by justme-1968** [comment] 2020-09-28 18:11
ok. that may be the problem. i have never waited so long as it is not needed in any of the other apps.

how do you sync manually? i it not obvious and even now after explicitly searching for it i could not find it.

there should be at least  an auto sync during termination and i think two minutes is quite long. maybe add another auto sync if everything is read?

**Comment by vincode-io** [comment] 2020-09-28 18:17
You can sync manually by using command-r or by clicking on the button in the toolbar.

We would like to be able to sync on termination.  Unfortunately there isn't a way to do it with the asynchronous nature of network requests.  We only update every couple minutes so that we don't overtax the synchronization services.

I'm going to go ahead and close this since it is functioning as designed.

**Closed by vincode-io** 2020-09-28 18:17 UTC

**Comment by justme-1968** [comment] 2020-09-28 19:12
no wonder i could not find a sync button or command. nowhere in the documentation is mentioned that r for refresh will not only refresh ie. read the feeds but also sync the status back to feebly.

there is nothing stopping a mac app to run an asynchronous task in the background on termination or delay termination for a little to get this final sync done. it is definitely possible. 

if this is really ‘works as designed’ then not only the working but also the design is bad. this is in no way meant to be rude. but it is a bad user experience.
