### ISSUE TITLE
Battery drain in article view -- WebKit issue?

### ISSUE THREAD

**Issue by cupright** [Ranchero-Software/NetNewsWire#2313] opened 2020-07-31 18:43 UTC
I am using NNW 5.0.2 (Build 49) on my iPhone SE (Model MP7X2ll/A), with iOS 13.6. I have been battling a persistent battery drain for several months, and I am finally narrowing the parameters of the problem. I am wondering if this might actually be a WebKit issue, but I'm hoping you can at least confirm the trouble I am seeing. First I will describe the problem, then I will provide what is hopefully a replicable example. Note that I had an online chat with an Apple support member yesterday, including an analysis of diagnostics, and I was told that my current battery health of 84% doesn't warrant replacement.

I am attaching two iPhone screenshots of charge activity in my "Battery" settings. The first shows how I experience rapid battery drain, sometimes falling 20%. This always takes place when I am viewing a webpage, usually one related to a mainstream news site such as cnn.com or nbcnews.com . The second screenshot shows how I am isolating the problem. In the spot I have marked "1" around 7:00 p.m., I stopped using Safari entirely, but spent the next several hours using the Brave browser. My battery level stayed at 58% for the duration. At spot "2," I opened the "First Read" website mentioned below in a NetNewsWire article view window, and within two minutes the charge dropped from 92% to 68% and the device got really hot. At spot 3, I opened the same webpage in Safari, and again it dropped 62% to 49% within one minute (with a similar temperature rise).

Here's the example of the page that is causing the drain:

Feed: https://politicalwire.com/feed/

Item: https://politicalwire.com/2020/07/31/trump-is-flailing/ 

Webpage: https://www.nbcnews.com/politics/meet-the-press/one-bad-day-demonstrates-how-trump-reaping-what-he-s-n1235448

Again, this might be an iOS issue rather than one with NNW, but it would be great if you could at least confirm that this problem isn't isolated to my phone!

![IMG_0004](https://user-images.githubusercontent.com/57457456/89066553-499c6300-d333-11ea-8ae0-942d1d155904.PNG)
![IMG_0037](https://user-images.githubusercontent.com/57457456/89066626-689af500-d333-11ea-9305-79a434ee56a4.png)

**Comment by vincode-io** [comment] 2020-08-02 18:25
I did some profiling of the NNW code using Xcode's Instruments and found that if you are only viewing the RSS article that CPU usage was near 0 when viewing the PoliticalWire feed.  When using the Reader View we would see about 10% constant usage.

What that tells me and is confirmed by your testing outside NNW is that there is badly behaving JavaScript code on these websites.  Reader View does its best to only pull in the most relevant pieces of a webpage, but there must be some JavaScript code getting pulled in with the Article content.  Unfortunately there isn't much we can do about badly behaving websites.

I tested using my iPhone 6s which is my oldest testing device.  I couldn't get it to heat up or cause significant battery drain even when viewing the poorly behaving sites.  There is no way for me to diagnose your personal device, but I can tell you that I can't replicate that on my phone.

I'm sorry that we couldn't help you out more.  I'm going to close this issue since it doesn't look like a NNW bug.  Please comment on this issue if you are able to pinpoint the problem and you think there is something we can do to mitigate it.

**Closed by vincode-io** 2020-08-02 18:25 UTC

**Comment by cupright** [comment] 2020-08-03 20:34
Hi, Maurice,

Thanks for humoring me. The problem has been frustrating me for a while, but I was first able to isolate it using NNW. I have now narrowed it to a Javascript issue, and it must be in iOS (but it might be specific to first generation SE iPhones).

Just for the sake of completeness, I am including the replication instructions below. I don’t expect you to pursue it any further, however, because it is obviously not a NNW issue. I submitted this to the “Feedback Assistant” as an Apple ticket.

Cheers,

-- Craig

------------------------------------------------

Here’s some additional information about this issue. Apparently this is not an uncommon problem for 1st generation iPhone SE devices using iOS 13.X. Here’s one article by Mark Sparrow (published June 26, 2020) that describes it:

https://www.forbes.com/sites/marksparrow/2020/06/26/is-your-apple-iphone-running-hot-and-chewing-its-battery/#385a88b21f42

I suspect the problem is with Javascript. Here’s how I can reproduce it on my phone:

(1) Turn off Javascript in Safari.

(2) Go to this website: www.mailionline.com (the UK’s Daily Mail).

(3) Scroll for a few minutes, reload, and everything is fine.

(4) Turn on Javascript for Safari, and repeat (2) and (3). At this point the battery charge starts ticking down like a stopwatch, and within a minute the phone is really hot.

(5) Turn off Javascript for Safari again, and repeat (2) and (3). Everything is working fine again.

Obviously, turning off Javascript permanently is not an adequate workaround, as this disables so much website functionality. But it can perhaps help isolate the problems.
