### ISSUE TITLE
BazQux Reader support

### ISSUE THREAD

**Issue by SuperTachyon** [Ranchero-Software/NetNewsWire#1827] opened 2020-02-26 16:39 UTC
BazQux is a very reasonably priced sync service with unlimited filters. It’s the service of my choice so far. I really hope NNW (iOS) could add support for its [API](https://github.com/bazqux/bazqux-api), which is a copy of google reader.

**Comment by vincode-io** [comment] 2020-02-26 16:43
Duplicate of #777

**Closed by vincode-io** 2020-02-26 16:43 UTC
