### ISSUE TITLE
NNW flagging read articles as unread

### ISSUE THREAD

**Issue by philviso** [Ranchero-Software/NetNewsWire#2693] opened 2020-12-30 01:01 UTC
I opened NNW on iPad after having not opened it for probably a week or so (I mainly use another app for RSS). After it finished doing a sync with Feedbin, it was showing I had 2 older articles in my account that were unread, but no other apps / NNW clients are showing that those articles are unread.

Other apps I checked:
- After a sync, Reeder 5 on iPhone / iPad considers those articles are read
- After a sync, NNW on the Mac considers those articles read
- Did a clean install of NNW on my iPhone, and after a full sync it considers those articles read

I tried doing a pull-to-refresh a bunch of times on iPad and it kept showing the articles were unread. I left the app for awhile and came back and the auto-refresh triggered some new articles being fetched. Along with bringing in those new articles, NNW also changed the old articles as read.

![IMG_0058](https://user-images.githubusercontent.com/347423/103323276-bc575a80-4a07-11eb-9c60-fe52525c5bdd.PNG)

The 2 articles with arrows next to them are the old ones that were marked read a long time ago in another app, but NNW considered them unread.

**Comment by vincode-io** [comment] 2020-12-30 01:18
I'm pretty sure that this is a duplicate of #2659 and should be fixed in the upcoming 6.0 release.

**Closed by vincode-io** 2020-12-30 01:18 UTC
