### ISSUE TITLE
FreshRSS not picking up new articles even after manual refresh

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#3063] opened 2021-04-24 05:15 UTC
App Store Connect report:

“I am using NNW with a self-hosted FreshRSS instance. After the initial setup yesterday it was showing articles all right. But some hours later and even after a good night’s sleep the list of unread articles is empty, even after a manual refresh. Unread and Fiery Feeds using the same configuration show the same articles as does the web interface of FreshRSS. If you need any further data, please just let me know.”

![original](https://user-images.githubusercontent.com/1297121/115948176-5f355800-a481-11eb-8627-d4b421e0d927.jpg)

**Comment by vincode-io** [comment] 2021-05-14 02:17
These App Store Connect bug reports are really hard to diagnose. I understand that your average user isn't going to be able to write a good bug report, but at least when they submit it via GitHub we can prompt them to get the information we need.

In this example, I really need to know what version of FreshRSS the user is on because I can't recreate it on the version I am using.

**Comment by artyorsh** [comment] 2022-06-03 06:08
Hello!
First of all, many thanks for great product and your efforts put on it

I’m actually facing the same issue with the latest version of the NNW v6.0.2-build.610 and FreshRSS v1.20.0-dev.

When using the app, refresh actions doesn’t trigger the real api refresh and only loads the articles that are already loaded by freshrss instance. Basically the steps to refresh the feed on mobile:
- Refresh freshrss feed via in browser
- Open NNW and pull-to-refresh

Please let me know if I can help with it

**Comment by vincode-io** [comment] 2022-06-05 03:20
@artyorsh Since you are using the iOS version of NNW, I'm assuming that you have a publicly accessible instance of FreshRSS on the web. If you could give me a temporary account on your instance, I can check to see if the issue is with NNW or the dev instance of FreshRSS that you are using.

If you can do this, please send the credentials to mo@vincode.io so that they don't end up all over the internet.

**Comment by artyorsh** [comment] 2022-06-07 07:57
Thanks for the reply @vincode-io
So yesterday I've found this was my misconfiguration. It was dumb to assume it will refresh automatically, so I'll link [this article](https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html) here :) Also, if your FreshRSS instance is running with Docker, [they have an env var](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#environment-variables) which will do it.

**Comment by vincode-io** [comment] 2022-06-07 23:20
Since this was most likely an issue on the FreshRSS side of things, I'm going to close this issue.

**Closed** 2022-06-07 23:20 UTC
Labels: bug, iOS

**Comment by TCB13** [comment] 2024-04-04 22:00
> When using the app, refresh action doesn’t trigger the real api refresh and only loads the articles that are already loaded by freshrss instance.

Yes, I have the same problem... and no, I don't believe this isn't a FreshRSS issue. @vincode-io 

The FreshRSS web interface has a button with a link to `domain/freshrss/i/?c=feed&a=actualize`  that calls the internal "actualize" routine an check all feeds for new content. It essentially does the same as running `FreshRSS/app/actualize_script.php` on the command line as described in [the article](https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html).

Although I've my FreshRSS instance with a systemd trigger to check the feeds ever 6 hours it would be nice to have the "pull to fresh" action on NetNewsWire call that routine as well.

Thank you.
