### ISSUE TITLE
iOS app need a cache clean button.

### ISSUE THREAD

**Issue by SamLinBIT** [Ranchero-Software/NetNewsWire#3655] opened 2022-08-18 00:30 UTC
I have already read the [issue](https://github.com/Ranchero-Software/NetNewsWire/issues/2969) which closed . Also I know how this app define [“what’s new”](https://github.com/Ranchero-Software/NetNewsWire/blob/main/Technotes/RetentionPolicy.markdown).

But if this app add a button which user can choose when to clean the cache, that will be very popular. Or can user get a setting that can set the data remain time?

**Comment by Jerry23011** [comment] 2022-08-24 15:30
What I do is to export my feeds, delete the app and reinstall it. Then I import my feeds back in

**Comment by SamLinBIT** [comment] 2022-08-25 09:01
@Jerry23011 I do the same. But it should not be used that way🥲

**Comment by SamLinBIT** [comment] 2022-08-25 09:02
I do the same. But it should not be used that way.🥲

**Comment by Jerry23011** [comment] 2022-08-25 10:31
I know, lol, hope they can get a feature to clean cache in the future.

**Comment by vincode-io** [comment] 2022-09-01 22:57
Duplicate of #2969.

**Closed by vincode-io** 2022-09-01 22:57 UTC

**Comment by Sissing** [comment] 2024-08-25 06:17
I'm arriving a bit late to the discussion, but I don't believe this is a duplicate of #2969. The automatic cache cleanup feature is great for everyday use. However, in my case, when I'm setting up new feeds, conducting some testing with custom filtering in FreshRSS, and deleting & re-fetching the latest articles, I end up with numerous duplicate articles in NetNewsWire.

One option could be to hold off on opening NetNewsWire until my setup is perfect. However, I prefer to use this app regularly, and I often update my filtering and try again when I come across articles I'm not interested in. The downside is that every time I do this, I have to remove and log back in with FreshRSS, causing me to lose all the other article-cached channels in the app.

Therefore, my hope is that there will still be an option to add a clear cache button per channel. This way, I can reset the cache of the channel I've been working with to find the perfect setup.
