### ISSUE TITLE
Adding Feedly Error: Secrets.CredentialsError error 0

### ISSUE THREAD

**Issue by markelp** [Ranchero-Software/NetNewsWire#2419] opened 2020-09-14 15:15 UTC
Attempted to add a Feedly account to a new install of 5.1b1 and received "The operation couldn't be completed. (Secrets.CredentialsError error0.)"

Feedly appears in the NNW side bar and listed as an account, but no subscriptions/folders appear.

I am able to use the same credentials to log into the feedly.com directly.

macOS Catalina 10.15.6 (19G2021)

<img width="1405" alt="Screen Shot 2020-09-14 at 11 01 04 AM" src="https://user-images.githubusercontent.com/55604191/93103430-9dac9e00-f67a-11ea-84e1-24c616e1bf7f.png">

**Comment by noadminonly** [comment] 2020-09-14 15:49
Hello

i have the same problem on my mac. 

noadminonly ;-)

**Comment by kielgillard** [comment] 2020-09-15 00:16
@markelp @noadminonly Do the folders, feeds and articles load from Feedly if you quit and re-launch NetNewsWire? 

Please don't get me wrong: this obviously is not a solution. But if it does load, this might shed a bit more light onto the nature of the problem.

**Comment by markelp** [comment] 2020-09-15 00:56
No. Upon quit and relaunch, the Feedly section is still blank in the sidebar. The On My Mac section does update as expected.

**Comment by kielgillard** [comment] 2020-09-15 01:03
@markelp Thanks!

First question: do you get an error when you quit and relaunch? If so, what does it say? Or does it just remain blank.

Second question: do you have any `cloud.feedly.com` entries in your Keychain? Here's what my Keychain looks like when I search for "feedly":
![image](https://user-images.githubusercontent.com/567949/93152797-ff383f80-f742-11ea-8f5d-1cd74e13c27b.png)

Feel free to answer these questions too, @noadminonly 😄

**Comment by markelp** [comment] 2020-09-15 01:22
No errors from NNW when it is launched (or relaunched).

Two entries for Feedly in keychain:
<img width="1135" alt="Screen Shot 2020-09-14 at 9 21 38 PM" src="https://user-images.githubusercontent.com/55604191/93153929-5d780a80-f6d0-11ea-937e-aa9439b6ec82.png">

**Comment by kielgillard** [comment] 2020-09-15 01:51
@markelp Thanks for playing!

First: have you tried adding the Feedly account after September 4? 

Second: If you choose one of those `cloud.feedly.com` items and from the menu bar choose File > Get Info, can you tell me what the access control is on that item? Here's what it looks like for me:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/567949/93155567-c2bc1200-f749-11ea-8c4e-40c07456a843.png">

**Comment by kielgillard** [comment] 2020-09-15 01:53
@markelp Also, if you don't mind, could you please try deleting both the Feedly account from NetNewsWire and the `cloud.feedly.com` items from the Keychain and try adding the account again?

**Comment by markelp** [comment] 2020-09-15 02:01
Yes, I tried to add Feedly after September 4th. 

Both entries list the the Alpha version of NNW. I believe I appended "ALPHA" to the app file name when
<img width="553" alt="Screen Shot 2020-09-14 at 10 00 18 PM" src="https://user-images.githubusercontent.com/55604191/93156279-d29a0e80-f6d5-11ea-826e-2fe4c03b23ce.png">
 I installed the beta version.

**Comment by markelp** [comment] 2020-09-15 02:05
Success! Deleting the two Keychain entries, removing the Feedly account entry from the NNW 5.1b1 prefs, quitting NNW 5.1b1, relaunching and re-adding the Feedly account solved the problem.

Feedly appears to be working as expected and there are two new entries in Keychain with today's date and Access Control for the NNW beta version.

**Comment by kielgillard** [comment] 2020-09-15 02:27
Okay, thanks for this. Glad to hear it is up and running. A few follow up questions, if I may?
1. Did adding the Feedly account ever work for you in earlier versions of NetNewsWire?
1. Do you remember which version you first attempted adding an account? (perhaps [this might help](https://nnw.ranchero.com) jog your memory?)
1. Do you think changing the name of the app makes any difference?

**Comment by markelp** [comment] 2020-09-15 03:52
Yes. I had Feedly added and working on a previous version. I believe alpha 2. I don’t think I had any of the “d” versions.

Yes, I think changing the name contributed to the problem. I recall adding Alpha to the file name when I installed the beta because I wanted to keep both in case there was a problem and used it to differentiate between the two apps.

**Comment by kielgillard** [comment] 2020-09-15 04:02
@markelp So if it was working in alpha 2, what made you add the account again in beta 1? Thanks for sticking with me, really appreciate it.

**Comment by markelp** [comment] 2020-09-15 11:32
I don't remember the steps that generated the initial error. I did attempt to remove and re-add Feedly several times after the first error in both the alpha and beta 1 versions.

But couldn't provide the sequence of those events. Maybe @noadminonly has better information.

**Comment by noadminonly** [comment] 2020-09-15 15:35
No i have no better information about the intial error. At the moment i work with Version 5.1b1 (3005) And the solution discribed in this thread works for me.

**Comment by kielgillard** [comment] 2020-09-15 23:03
@noadminonly did you re-name NetNewsWire as well?

**Comment by alapolloni** [comment] 2020-09-16 08:20
> Success! Deleting the two Keychain entries, removing the Feedly account entry from the NNW 5.1b1 prefs, quitting NNW 5.1b1, relaunching and re-adding the Feedly account solved the problem.
> 
> Feedly appears to be working as expected and there are two new entries in Keychain with today's date and Access Control for the NNW beta version.

Just wanted to say I had the same problem and this also fixed it.

**Comment by markelp** [comment] 2020-09-18 01:34
So this error occurred again for me tonight.

After deleting the two Keychain entries per the comment above three days ago and re-adding Feedly, all was working as expected until tonight.

Tonight, I got the pop-up that b2 was available and clicked to let the app update itself. Upon relaunch, the Feedly entry was not in the sidebar. I opened Preferences and added Feedly using my credentials and received the Secrets.CredentialsError error 0 again. There are no feeds or folders under the Feedly entry in the sidebar.

Screenshot of relevant NNW, Finder and Keychain entries attached. 

<<Note the current file name for the new 5.1b2 app that installed Today (Sept 17) at 9:18pm retained the "Beta b1" I appended to the 5.1b1 install file name. The "ALPHA" version is 5.1a2 and the 'plain' version is 5.0.4.>>

I assume the fix is the same (delete Keychain entries for Feedly, restart NNW, re-add Feedly), but will hold off on this until I hear from @kielgillard  in case you need more troubleshooting.

<img width="1892" alt="Screen Shot 2020-09-17 at 9 25 13 PM" src="https://user-images.githubusercontent.com/55604191/93545047-7c270d00-f92d-11ea-9479-1ab766e48a8d.png">

**Comment by vincode-io** [comment] 2020-09-18 21:59
@markelp Could you rename the Beta 2 version of the app to NetNewsWire.app and see if that resolves your issue?

**Comment by markelp** [comment] 2020-09-18 22:16
Yes. Renaming the app back to NetNewsWire and launching the app performs as expected. No error message and the Feedly account in the sidebar populates as expected.

KeyChain Access Control still shows the two cloud.feedly.com entries for "NewNewsWire BETA Latest" as shown in the screenshot above.

**Comment by kellyfirkins** [comment] 2020-10-31 21:20
Just wanted to add an update: I had the same error as above, app name was different in access control, so rather than deleting the KeyChain entries, I just removed the old app and added the current NetNewsWire app in Keychain access control. NetNewsWire picked up the entries and was able to load Feedly.

**Comment by vincode-io** [comment] 2020-11-02 21:28
@kellyfirkins Did you ever run any of the NetNewsWire beta versions?  I'm wondering if something we did during the beta period may have contributed to this problem.

**Comment by kellyfirkins** [comment] 2020-11-02 23:15
Well @vincode-io, I did start with the first version of betas that supported Feedly (I don't _think_ I started a beta before then, but may have), had problems getting it to actually connect (IIRC) and proceeded onto other betas including the beta previous this where I was able to connect & sync. Then this beta had this issue... so I guess there could've been something in that train, but I didn't really keep good notes about what I noticed and when.

**Comment by vincode-io** [comment] 2020-11-16 18:11
I'm not sure what we can do with this one other than provide a more helpful error message.  It looks like Keychain permissions get set based on the application file name rather than the bundle identifier.  This seems bizarre to me.

Here is someone with the same issue that never got a resolution: https://stackoverflow.com/questions/60319474/couldnot-update-delete-or-add-keychain-item-when-app-name-is-changed

**Comment by kellyfirkins** [comment] 2020-11-16 21:22
I can't speak for everyone else, but to me a unique identifying error is sufficient because it can be searched on and lead to easier discovery the issue and workarounds. You can't control the behavior of the keychain. 

Thanks for digging into it.

**Comment by vincode-io** [comment] 2020-11-20 21:53
I'm not able to recreate this on NetNewsWire 6.0.  I'm pretty sure this is because we are sandboxed on NetNewsWire 6.0 and use the additional key [kSecAttrAccessGroup](https://developer.apple.com/documentation/security/ksecattraccessgroup) when sandboxed to query the Keychain.

We use this additional key when sandboxed so that we can share keychain items among our main app and any extensions that would need it as a app group.  Renaming the app doesn't seem to have any impact on the app group registration.

@brentsimmons I feel pretty good that this is resolved.  I recommend we close this issue and open it again if I'm wrong and it is a problem in 6.0.

**Comment by kellyfirkins** [comment] 2020-11-20 22:22
FWIW, I agree, this should be closed out if not reproducible in 6.0.

**Closed** 2020-11-20 22:37 UTC
