### ISSUE TITLE
Mark as read for all articles with the same URL in different feeds

### ISSUE THREAD

**Issue by ghost** [Ranchero-Software/NetNewsWire#2440] opened 2020-09-21 04:47 UTC
Articles with the same URL in different feeds should be mark as read when one of them is read.

Some news sites post the same article in different feeds such as top stories and technology. An article may appear in both of these feeds.

![E08FCBB6-78F2-484B-B604-35C3800D4F72](https://user-images.githubusercontent.com/65079033/93733729-98ac9900-fbfc-11ea-908a-881a8eb67df8.jpeg)

**Comment by TWDickson** [comment] 2020-10-05 13:33
I’d also like to see grouping if you’re viewing the smart lists

**Comment by brentsimmons** [comment] 2023-03-06 04:50
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/847

**Closed by brentsimmons** 2023-03-06 04:50 UTC
