### ISSUE TITLE
Suggestion: option to hide specific feed or folder from the Today Smart Feed

### ISSUE THREAD

**Issue by danielmunoz** [Ranchero-Software/NetNewsWire#3003] opened 2021-04-15 15:48 UTC
It would be great if, when holding a finger over (or right-clicking) a specific feed or folded, you had the option to "Hide this feed/folder from Today Smart Feed".

That way, the Today Smart Feed and the "Your Today Articles" widget could be more revelevant to your interests.

**Comment by brentsimmons** [comment] 2023-03-06 17:02
Duplicate of #2388

**Closed by brentsimmons** 2023-03-06 17:02 UTC
