### ISSUE TITLE
Feature request: option to export starred items

### ISSUE THREAD

**Issue by palaniraja** [Ranchero-Software/NetNewsWire#3863] opened 2023-02-10 07:28 UTC
I would love to have an option to export just starred articles as an alternative to bookmarks for a device without any syncing backend(i.e local only setup)

**Comment by brentsimmons** [comment] 2023-03-06 02:11
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/978

**Closed** 2023-03-06 02:11 UTC
