### ISSUE TITLE
Sidebar state is not restored after relaunch

### ISSUE THREAD

**Issue by tclementdev** [Ranchero-Software/NetNewsWire#3636] opened 2022-07-30 16:10 UTC
1. Go to menu View > Hide Sidebar
2. Relaunch app
3. Sidebar is not hidden

**Comment by vincode-io** [comment] 2022-07-30 19:18
Duplicate of #1944.

**Closed by vincode-io** 2022-07-30 19:18 UTC

**Comment by tclementdev** [comment] 2022-08-01 06:27
I there any rationale that I can read somewhere as to why?
