### ISSUE TITLE
[Feature Request] Generic Feed Provider Api

### ISSUE THREAD

**Issue by c128128** [Ranchero-Software/NetNewsWire#3578] opened 2022-05-28 16:21 UTC
## Generic Feed Provider Api
The idea is to create a generic parser and an API that will permit other developers to create custom scripts in JS that will run inside JavascriptCore and parse custom feeds.

Something like `Extensions` but Generic.

This can be very useful if we want to parse some pages that don't provide a RSS feed like:
1. https://developer.apple.com/documentation/technotes
2. https://www.mongodb.com/docs/realm/release-notes/backend

Some ideas what this should include:
- [ ] An API that will permit developers to write custom parsers.
- [ ] A centralize place where users can add this parsers. (I think something like Cydia.). Where there are some default parsers and custom can be added too.
- [ ] A place where developers can submit their parsers (Maybe with some kind of review).
- [ ] Instructions about how can a developer write and debug a custom parser.

Other ideas are welcome.

P.S: Thank you for your work, the app is amazing.

**Comment by vincode-io** [comment] 2022-10-01 11:44
I think this is basically the same thing as #3385. I'm going to mark this as a duplicate of that. It will have a reference back to this issue that we can review when evaluating #3385.

**Closed by vincode-io** 2022-10-01 11:45 UTC
