### ISSUE TITLE
[mac 6.0] [bug] "Mark all as read, go to next unread" (key L) doesn't jump to next feed

### ISSUE THREAD

**Issue by ednl** [Ranchero-Software/NetNewsWire#2960] opened 2021-04-02 01:19 UTC
Mac version 6.0. When using the keyboard shortcut lowercase L to jump from feed to feed while marking them read, if the first article in a feed is selected it does not jump to the next feed but instead to the second message in the same feed, which should have been marked read already. Apparently the order of the command is: "Go to next unread, mark all as read".

This happens every time when just using the keyboard shortcut to navigate. But it does not happen always in other circumstances, e.g. not when manually marking article 2 unread, selecting article 1, then pressing L.

**Comment by vincode-io** [comment] 2021-04-15 19:36
Duplicate of #2952.

**Closed by vincode-io** 2021-04-15 19:36 UTC
