### ISSUE TITLE
Fine control of which feeds contribute to badge count (like iOS Mail)

### ISSUE THREAD

**Issue by chinarut** [Ranchero-Software/NetNewsWire#2083] opened 2020-05-17 00:51 UTC
It’s good to be back on the RSS bandwagon after Google Reader kicked the bucket!

So I cleared 5-7 years of unread articles yesterday leaving 7 unread articles and woke up to a badge count of 43 due to high volume feeds like mashable, BBC, etc.

One of the ways I deal with my high volume email issue on iOS is the fine-tuned controls built into Mail.    Apple provides a facility as to whether a “mailbox” (account, VIP, starred messages, etc) contributes to the badge count.

<img width="1366" alt="Mail - badge count config" src="https://user-images.githubusercontent.com/6845061/82133179-a610cd00-979d-11ea-9bd0-33abce936f95.png">

Borrowing the same mechanism, I’d like to be able to configure a news feed to **not** contribute to my badge count.

This would help tremendously and hope others feel the same way too!

**Comment by retifrav** [comment] 2020-09-07 09:06
Oooh, I couldn't agree more. I have quite a lot of RSS feeds that I follow, but not all of them are equally important, so I would like to be able to exclude certain feeds from contributing to the badge count, both on iOS and Mac OS.

Here's an illustration, just in case (hopefully, **chinarut** is after the same thing):

<img width="1012" alt="badge" src="https://user-images.githubusercontent.com/6904927/92369933-e9e76380-f0f9-11ea-8ae2-c3418f76e249.png">

**Comment by brentsimmons** [comment] 2023-03-06 03:27
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/1962

**Closed by brentsimmons** 2023-03-06 03:27 UTC
