### ISSUE TITLE
Feature Request: Option to open feed link by system default

### ISSUE THREAD

**Issue by ascagnel** [Ranchero-Software/NetNewsWire#3728] opened 2022-11-05 16:19 UTC
Right now, when you open a feed's link on iOS, it always open in a SafariViewController. I have a few site-specific apps (Tweetbot, Apollo) and extensions (Vinegar for YouTube) installed, and they don't open the URL or function from within the embedded view. Can an option be added to disable this behavior?

**Comment by vincode-io** [comment] 2022-11-05 19:12
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/3029

**Closed by vincode-io** 2022-11-05 19:12 UTC
