### ISSUE TITLE
Mark as read as you scroll the list

### ISSUE THREAD

**Issue by brosenz** [Ranchero-Software/NetNewsWire#2481] opened 2020-10-05 15:52 UTC
This is not a bug, it is a new feature request for iOS/iPadOS, is it possible to have an option to Mark as Read while you scroll the list? To have in iOS and iPadOS the same behavior as in macOS

Sometimes I scroll through some of them, if  leave the app and come back , I will have to scroll through all of them again, the ones I already read. 

The app Newsify has this capability, but I want to move to NetNewsReader, thanks

**Comment by vincode-io** [comment] 2020-10-05 19:15
Duplicate of #1844

**Closed by vincode-io** 2020-10-05 19:15 UTC
