### ISSUE TITLE
Feature request: option to export starred items

### ISSUE THREAD

**Issue by MatBenfield** [Ranchero-Software/NetNewsWire#3509] opened 2022-03-26 16:38 UTC
As a user
I would like to export my starred items in JSON/XML/CSV/HTML/OPML
So I can "process" them

* transfer to safari reading list, add to GitHub pages as readme, do some analysis by grouping and tagging items. 

Currently in the region of 150 starred items on iOS.

Many thanks

**Comment by MatBenfield** [comment] 2022-04-22 15:21
Related #1257

**Comment by vincode-io** [comment] 2022-05-26 19:34
Duplicate of #978

**Closed by vincode-io** 2022-05-26 19:34 UTC
