### ISSUE TITLE
Features request for MacOS

### ISSUE THREAD

**Issue by 2stepbay** [Ranchero-Software/NetNewsWire#3254] opened 2021-08-15 03:28 UTC
In MacOS
single-line option for feed headline/description - this way a running list of feeds is generated similar to NetNewsWire 3. Would make for a much easier read/scan of what is available
ability to rearrange order of feeds within a folder as well as within the overall folder structure for all feeds

**Comment by vincode-io** [comment] 2021-08-18 00:54
Duplicate of #102.

**Closed by vincode-io** 2021-08-18 00:54 UTC
