### ISSUE TITLE
macOS hangs on adding feed to Feedly

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2470] opened 2020-09-30 23:16 UTC
(sorry, hit submit too quickly...)

Tried adding this feed:

https://www.nytimes.com/live/2020/presidential-polls-trump-biden#biden-wins-instant-polls

The first time I tried, I had accidentally selected On My Mac.  It displayed a dark grey Finding Feed... window and after a few seconds timed out.

I then tried to add the same feed again but to Feedly.  Then window popped up again, but now is stuck and I can't quit the app.

**Comment by brentsimmons** [comment] 2020-09-30 23:18
What’s the feed URL? How are you adding it? Using Feedly, Feedbin, or On My Mac?

**Comment by blackketter** [comment] 2020-09-30 23:20
NB: Not sure if it's a valid feed URL, but probably shouldn't get stuck either.

**Comment by brentsimmons** [comment] 2020-09-30 23:46
What do I need to do to reproduce this?

**Comment by brentsimmons** [comment] 2020-09-30 23:47
It’s probably due to the #

**Comment by blackketter** [comment] 2020-10-01 01:06
Alas, no, seems to hang with just:

https://www.nytimes.com/live/2020/presidential-polls-trump-biden

too...  Verified macOS with  5.1.1a1 (3010) and iOS 5.04 build 52.

Interestingly, I was able to cancel out on iOS, no obvious way to cancel on macOS, had to force quit

**Comment by brentsimmons** [comment] 2020-10-01 01:19
It only hangs with Feedly for me. Works with On My Mac and Feedbin. True for you too?

**Comment by blackketter** [comment] 2020-10-01 02:38
I don't have a Feedbin, but yes, only hangs on Feedly for me.

**Comment by kielgillard** [comment] 2020-10-01 22:46
Thanks for letting us know about this @blackketter! Next macOS and iOS releases will contain a fix for this.

Feedly couldn't find a feed for this url and NetNewsWire's Feedly integration wasn't letting the rest of NetNewsWire know the failure, so it just sat there waiting. This means on iOS, it would wait idle but on macOS it would lock up all but the "finding feed" panel. Now, the expected error is shown.

**Closed** 2020-10-02 04:06 UTC
Labels: iOS, macOS
