### ISSUE TITLE
Feedbin folder view status not persistent.

### ISSUE THREAD

**Issue by jordanf** [Ranchero-Software/NetNewsWire#843] opened 2019-08-13 19:50 UTC
I have all my feeds in folders. [Though I guess Feedbin thinks of them as "labels".]

I like all of the folders in my feeds list disclosed/open. That does not persist across NNW launches. Folders are always closed upon launch.
<img width="203" alt="Closed" src="https://user-images.githubusercontent.com/6898542/62972488-2014bf80-bde2-11e9-8eea-ec0756ab6210.png">
<img width="185" alt="Open" src="https://user-images.githubusercontent.com/6898542/62972489-2014bf80-bde2-11e9-91d5-0bce4ee9c85d.png">

**Comment by vincode-io** [comment] 2020-02-29 23:26
Duplicate of #562.

**Closed by vincode-io** 2020-02-29 23:26 UTC
