### ISSUE TITLE
Feature request: sort subscriptions by user choice

### ISSUE THREAD

**Issue by paulehoffman** [Ranchero-Software/NetNewsWire#877] opened 2019-08-26 16:46 UTC
I suspect that #853 will be higher priority than this one, but I really appreciate Innoreader allowing me to group things by my own view of importance.

**Comment by brentsimmons** [comment] 2023-03-06 01:26
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/356

**Closed by brentsimmons** 2023-03-06 01:26 UTC
