### ISSUE TITLE
Feature Request: Filter Feed List

### ISSUE THREAD

**Issue by MDWolinski** [Ranchero-Software/NetNewsWire#1054] opened 2019-09-24 12:00 UTC
In the latest version (5.0.2), when you click on a folder, it feed list shows only the new items.  If you expand the folder and click on an individual feed, it shows all the items, which on feeds that maintain a large list of back stories (ie HackerNews, etc) can make new items at the bottom of the list (depending on how you have the items sorted).

It would be nice, if at the top of the feed list, you had the ability to filter the currently displayed list, perhaps the ability to create smart lists.

For example, the quick morning mockup below would allow me to filter (from left) for Unread items, Read items and Starred items.  I also moved the "Mark All as Read" button to this to be more indicative of what I'm marking as read.

A secondary addition would be the ability to create Smart Filters for this area as well, for example, I could create a "Today" smart filter.

<img width="626" alt="netnewswire_feed_filters" src="https://user-images.githubusercontent.com/22196395/65509695-09618e00-dea1-11e9-8f7e-89f4bd023319.png">

**Comment by brentsimmons** [comment] 2019-09-24 20:08
This is a duplicate of a couple different requests already on the bug tracker — the ability to create smart feeds and the ability to show/hide already-read articles.

**Comment by vincode-io** [comment] 2020-02-29 23:17
Filtering functionality is coming in 5.1.  Closing this issue.

**Closed by vincode-io** 2020-02-29 23:17 UTC
