### ISSUE TITLE
Restore prior 6.0 shortcut behaviour?

### ISSUE THREAD

**Issue by ararimu** [Ranchero-Software/NetNewsWire#3113] opened 2021-05-10 20:57 UTC
Prior to 6.0 (well, at least 6.0.2), if you were browsing the last article in a feed and you pressed keyboard shortcut "l" (mark all as read, go to next unread), NNW would show the next read. That meant you could zip through all of the articles with two keys: space and l.

It appears 6.0 disables this when on the last article - which is now read when on screen. I think technically, that is correct behaviour because the article is read by the time you have skimmed the headline, however it means a bit of a keyboard dance to get to the next unread (yeah, I know, it's just "n"). Just the smallest bit of friction. Would be nice to have old behaviour back.

Comments?

**Comment by brentsimmons** [comment] 2021-05-10 21:00
Good catch!

Duplicate of #3092

**Closed by brentsimmons** 2021-05-10 21:00 UTC
