### ISSUE TITLE
Feature Request: Mac toolbar icons for marking read and stared should visually reflect article state

### ISSUE THREAD

**Issue by jargonjustin** [Ranchero-Software/NetNewsWire#1546] opened 2020-01-06 23:26 UTC
The toolbar icons for toggling read/unread and starred/unstarred article state update their tooltip text based on article state (e.g., "Mark as Starred" versus "Mark as Unstarred"), but use the same icon regardless of the article's state. I found this difficult to use at a glance, as there is no visual indicator of article state tied to the button (or necessarily on screen itself, if the article list is scrolled). Changing to alternate icons (perhaps "unfilled" versions of the current icons?") depending on the current state might make the buttons more usable.

**Comment by brentsimmons** [comment] 2020-01-06 23:36
The problem is this: do you show the current state, or do you show the state that would be a result of performing the action?

No matter which you choose, roughly half the people would expect the opposite.

**Comment by jargonjustin** [comment] 2020-01-06 23:45
> No matter which you choose, roughly half the people would expect the opposite.

Agreed. However, having a toggle button with no visual indication that a state changed occurred seems worse (clicking the button can feel 'broken' at first). I wonder if most users would learn the behavior quickly, even if they found it initially confusing.

Another way to do this might be have some separate indicator of state, but I'm not sure what that would be, and seems unnecessarily cluttered.

I don't have a strong opinion on which way is the right (less wrong?) way, but as a straw proposal: having the icon double as an indicator of the current state seems at least more useful (shows the state at a glance, and interacting with it directly changes that state). It could make sense to show something slightly else, to indicate the button will cause a state transition, but I'm not sure how to do that in an clear way either.

**Comment by jargonjustin** [comment] 2020-01-06 23:48
As a related issue: the "Mark All as Read" and "Go to Next Unread" icons would need to be rationalized with the visual choices here (e.g., if making the "Mark as Read" icon reflect the state and display as 'unfilled', the "Mark All as Read" icon would make more sense if changed in the same way)

**Comment by jargonjustin** [comment] 2020-03-30 03:17
I've been enjoying the iOS version of NetNewsWire and noticed that when swiping a news item to the right, it shows an read/unread toggle action with an icon indicating the state to transition _to_ (i.e., a filled circle on a read item indicating it will be marked as unread, and an unfilled one on a read item indicating it will be marked as unread).

**Comment by vincode-io** [comment] 2020-12-02 16:41
The Mac toolbar on when using NetNewsWire 6.0 (not yet released) shows the state of the article, so I'm closing this issue.

**Closed by vincode-io** 2020-12-02 16:41 UTC
