### ISSUE TITLE
Drop shadow missing from web view

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#2879] opened 2021-03-13 15:52 UTC
After scrolling down a bit on all three columns of NetNewsWire, I see this:

![](https://user-images.githubusercontent.com/25517624/111035806-18683300-83ea-11eb-86cb-17e3453cb5f2.png)

Note that the sidebar and article list have a drop shadow between the title bar and the content, while the web view does not. The shadow does appear when you hover over the title bar, though.

**Comment by j-f1** [comment] 2021-03-13 16:00
There’s probably a good native way to fix this but a hacky fix would be to detect scrolling in the web view and change <code>detailSplitViewItem.[titlebarSeparatorStyle](https://developer.apple.com/documentation/appkit/nssplitviewitem/3622473-titlebarseparatorstyle)</code> based on whether the user has scrolled down.

**Comment by vincode-io** [comment] 2021-03-13 17:00
Duplicate of #2633.

**Closed by vincode-io** 2021-03-13 17:00 UTC
