### ISSUE TITLE
Add custom font support

### ISSUE THREAD

**Issue by Suzie97** [Ranchero-Software/NetNewsWire#3331] opened 2021-11-01 15:25 UTC
# Problem
Fonts are an important aesthetic and more importantly, an important accessibility feature. Especially when it comes to a reading app. Many people spend money on fonts they want to use, and some fonts like Atkinson Hyperlegible are designed with accessibility in mind. Supporting multiple fonts would greatly benefit a lot of users, who are not satisfied with the built in San Francisco fonts for various reasons.

# Proposal
- Add custom font support. I don't know if its possible to add custom font chooser in iOS and Mac. I develop my own RSS reader [Communique](https://github.com/suzie97/communique) for [elementary OS](https://elementary.io) and linux. Fonts installed in the computer can be chosen thorough a font chooser API provided by the system. If something like this is possible, then it would be great.
- Otherwise, the app could bundle in some fonts from the most important font types like Serif, Sans Serifs, some accessibility focused fonts, etc.

# Prior Art
## Communique
![Screenshot from 2021-11-01 20-50-52](https://user-images.githubusercontent.com/68198116/139695942-98624274-b19e-42ba-b7de-e3ccf0b1d569.png)

## Inoreader
![inoreader-font](https://user-images.githubusercontent.com/68198116/139696522-134fe736-3850-4387-ba25-c4dff7084287.jpg)

**Comment by vincode-io** [comment] 2021-11-02 00:24
Our plan to accommodate different fonts, sizes, and colors is to implement Themes. See #19 for more information. This is coming in the next release and we would like to bundle an Accessible Theme.

As a starting point, we can bundle Atkinson Hyperlegible. Can you think of anything else that would need to be done? Should we just use the existing Light/Dark color scheme or is there something that is more legible?

**Comment by Suzie97** [comment] 2021-11-02 04:25
> Our plan to accommodate different fonts, sizes, and colors is to implement Themes. See #19 for more information. This is coming in the next release and we would like to bundle an Accessible Theme.
> 
> As a starting point, we can bundle Atkinson Hyperlegible. Can you think of anything else that would need to be done? Should we just use the existing Light/Dark color scheme or is there something that is more legible?

As mentioned in #3327, reducing the contrast between the fonts and the background color is important. I've faced some headache issues reading high contrast text. I would say use another color for the text other than pure white (#FFFFFF).
![Screenshot from 2021-11-02 09-53-50](https://user-images.githubusercontent.com/68198116/139786637-e681a7f7-5407-478c-bac1-2345966c94b3.png)

**Comment by vincode-io** [comment] 2021-11-02 10:22
I'm no accessibility expert, but I've read enough to know that reducing contrast makes things harder, not easier to see. In the accessibility theme that I'm making (which may or may not be bundled with with NetNewsWire), I've actually _increased_ contrast to make things easier to read. Additionally, I've increased font size by 35% and use the Atkinson Hyperlegible font.

As I commented in #3327, we will provided you the ability to customize fonts and colors using Themes. You can make a low contrast Theme to use and share with others when NetNewsWire 6.1 ships.

Duplicate of #19.

**Closed by vincode-io** 2021-11-02 10:22 UTC
