### ISSUE TITLE
Feature request: Subfolders

### ISSUE THREAD

**Issue by luca-simpletech** [Ranchero-Software/NetNewsWire#3392] opened 2022-01-06 11:45 UTC
I use RSS feeds for YouTube-channels to fetch the newest Videos. It would be nice if I could just drag 'n drop a folder into the folder 'YouTube' for categories like "art", "music", "linux",...

Before switching to NNW, I used Thunderbird, where this feature was a huge time saver for me and made it much easier to search for a specific feed for large RSS libraries.

**Comment by vincode-io** [comment] 2022-01-06 20:24
Duplicate of #503.

**Closed** 2022-01-06 20:24 UTC
