### ISSUE TITLE
Feature Request: Smart Filter by Account

### ISSUE THREAD

**Issue by firexcy** [Ranchero-Software/NetNewsWire#3208] opened 2021-06-29 09:11 UTC
My NNW setup has two accounts, one being the iCloud account and another the NewsBlur account. I use the iCloud account to subscribe to several high-frequency, “skimmable” feeds that I don’t want to dilute my NewsBlur timeline. As such, it is desirable to have the ability to only view items in a specific account. Currently, I can only view items in a specific folder, which requires me to iterate among all folders under my NewsBlur account to read them all.

**Comment by vincode-io** [comment] 2021-06-29 17:41
Duplicate of #217.

**Closed by vincode-io** 2021-06-29 17:41 UTC
