### ISSUE TITLE
App not refreshing in the background

### ISSUE THREAD

**Issue by BearyBearyB** [Ranchero-Software/NetNewsWire#3137] opened 2021-05-28 14:04 UTC
Hi!!

Only upon opening the app (and manually refresh by scrolling down on screen) then the feeds are updated, with notification popping up (banner, etc.) at the same time.

Without opening the app, I don’t receive push notification, it’s as if the app isn’t refreshing in the background. (I checked background refresh setting is turned on.)

This is on IOS device.

**Comment by vincode-io** [comment] 2021-05-28 14:07
Duplicate of #2127. Read through it to see how to get background refresh to work better and understand the limitations of background refresh.

**Closed by vincode-io** 2021-05-28 14:07 UTC
