### ISSUE TITLE
Feature request: auto read articles

### ISSUE THREAD

**Issue by markbattistella** [Ranchero-Software/NetNewsWire#3894] opened 2023-03-03 00:12 UTC
More of a feature I thought would be good - and would only have to run on launch than on a timer or anything.

If there could be a global "Mark as Read after x days" but preferably a per-subscription option.

Use case benefits:
- adding new feeds, every article is unread. having a threshold would auto mark as read, for example older than 14 days
- some feeds post daily or multiple times a day. data can become overwhelming or annoying or unsubscribe-able with data overload

I'm sure there are more benefits, but it could make some nice "smarts" to app.

**Comment by dmshaw** [comment] 2023-03-05 04:19
Feedly (possibly others, but I don't use them so don't know) does this automatically after 30 days.  This feature would be really nice to bring the same sort of functionality to feeds in iCloud.

**Comment by brentsimmons** [comment] 2023-03-05 23:21
Duplicate of [#74](https://github.com/Ranchero-Software/NetNewsWire/issues/74)

**Closed by brentsimmons** 2023-03-05 23:21 UTC
