### ISSUE TITLE
[feature request] Programming smart feeds

### ISSUE THREAD

**Issue by sherlock440** [Ranchero-Software/NetNewsWire#2007] opened 2020-04-22 10:54 UTC
<img width="199" alt="image" src="https://user-images.githubusercontent.com/63901545/79973577-7b826b80-84a0-11ea-9809-a359b9f53c85.png">

at the moment only 3 Smart Feeds are available in the application, which are created automatically. If you ask me, you need to add the ability to customize new Smart Feeds in the "IF ..." scheme.

For example, if there is a word "Apple" in the headline of a news item, then this news item should fall into a separate Smart Feed created by me specifically for this purpose.

**Comment by vincode-io** [comment] 2020-04-22 12:26
Duplicate of #1038.

**Closed by vincode-io** 2020-04-22 12:26 UTC
