### ISSUE TITLE
[Feature Request] Open in Safari Preference on iOS

### ISSUE THREAD

**Issue by thatguygriff** [Ranchero-Software/NetNewsWire#3373] opened 2021-12-20 23:08 UTC
I subscribe to several feeds that require me to login and read the content. The embedded browser often forgets my sessions and doesn’t include the benefits of Safari browser extensions. For these posts I usually open them and then immediately press the Open in Safari button. 

It would be great if a version of the macOS browser preference, or a preference like Twitterrific has made its way into the iOS versions of the app.

**Comment by vincode-io** [comment] 2021-12-20 23:29
Duplicate of #3029.

**Closed by vincode-io** 2021-12-20 23:29 UTC

**Comment by thatguygriff** [comment] 2021-12-20 23:34
Thanks! I only searched open issues and didn’t think to check closed ones 🤣

**Comment by vincode-io** [comment] 2021-12-20 23:49
No problem. It will be there in the next release.
