### ISSUE TITLE
Translate NetNewsWire?

### ISSUE THREAD

**Issue by CyrosX** [Ranchero-Software/NetNewsWire#2140] opened 2020-06-18 07:53 UTC
Could you make NetNewsWire translatable?
There are some group-online-translation applications, which allows users to contribute easily to translations

**Comment by shazron** [comment] 2020-06-18 08:08
see comments in #850 and #851

**Comment by Krinkle** [comment] 2020-10-14 05:03
I'd love to help out with a Dutch translation.

If you're interested in levering an open platform, then [translatewiki.net](https://translatewiki.net/) could help you get a wide range of translations for app on an on-going basis, including peer review from non-technical volunteers. I've worked with them before and could help set things. Practically speaking they'd provide periodic pull requests with semi-automatic exports of the latest string sets.

**Comment by vincode-io** [comment] 2022-12-23 22:43
Duplicate of #78.

**Closed by vincode-io** 2022-12-23 22:43 UTC
