### ISSUE TITLE
Text Formatting options

### ISSUE THREAD

**Issue by InternetEnzyme** [Ranchero-Software/NetNewsWire#920] opened 2019-08-31 02:31 UTC
I would really like to be able to choose from typefaces installed on my system and then be able to pick a custom font size. This would necessitate options for line spacing as well.

**Comment by brentsimmons** [comment] 2019-08-31 17:13
For the article view? Or also the sidebar and timeline? Or…?

**Comment by InternetEnzyme** [comment] 2019-08-31 17:57
The article view is what needs styling options: the default size is huge. I would like to see at least some moderate customization akin to Safari's reader view. But if you decided to go a more granular WYSIWYG route, allowing for styling on a body and header basis, changes made for the header in the article view could also percolate into the timeline view. Also, it would be good to provide a similar preference like Mail's "Use dark background for messages" checkbox and Fantastical's "Light theme" option so that dark mode wouldn't apply to the article view.

**Comment by sayo-melu** [comment] 2019-11-04 03:46
> For the article view? Or also the sidebar and timeline? Or…?

i think the 'article view' first, as many people think serif is much more readable than sans serif in article text. 

furthermore, there are a lot of rss reader have this kind of feature. but they just let user choose from a limited list of font, i think people wish they could choose font like the 'apple pages' does. and it could be way better if user could choose different font for different language, and to support user font in ios 13.

a list to summarize:
- choose font like in 'apple pages'.
- set font size.
- set different font for different language.
- support ios 13 user font.

**Comment by jackyicu** [comment] 2020-04-26 05:05
> I would really like to be able to choose from typefaces installed on my system and then be able to pick a custom font size. This would necessitate options for line spacing as well.

And also a Justify alignment option would be perfect. I haven't seen any rss reader provide Justify option.

**Comment by vincode-io** [comment] 2020-04-26 07:15
Duplicate of #19.

**Closed by vincode-io** 2020-04-26 07:15 UTC
