### ISSUE TITLE
Tiny Tiny RSS account support

### ISSUE THREAD

**Issue by woble** [Ranchero-Software/NetNewsWire#2087] opened 2020-05-18 07:20 UTC
Are there any plans to add support for Tiny Tiny RSS account in a similar fashion as Feedbin.

https://tt-rss.org/wiki/ApiReference

**Comment by brentsimmons** [comment] 2020-05-18 15:41
We plan to support all of the various services.

**Comment by parkr** [comment] 2020-05-19 16:09
Is this a duplicate of #388, or am I misinterpreting?

**Comment by woble** [comment] 2020-05-19 16:16
Seems like it. I guess I didn't search good enough.

**Closed** 2020-05-19 16:16 UTC

**Comment by parkr** [comment] 2020-05-19 16:17
All good—was searching through the sync issues too to see the status and just happened to notice the similarity, but wasn’t sure if you were requesting the same thing. Cheers!

**Comment by eric-pierce** [comment] 2024-09-24 19:07
Tiny-Tiny RSS is now usable with NetNewsWire. I recently published a plugin for Tiny Tiny RSS that will allow NetNewsWire to interface with it using the FreshRSS API here: https://github.com/eric-pierce/freshapi

I've got to say NNW is a really nice experience, better with TT-RSS as the server. If you give it a shot please provide any feedback or issues you find!
