### ISSUE TITLE
Crash when clicking on Google Docs link

### ISSUE THREAD

**Issue by AttilaTheHahn** [Ranchero-Software/NetNewsWire#2474] opened 2020-10-02 20:30 UTC
In the Kottke.org feed, the article at https://kottke.org/20/10/how-to-protect-yourself-from-the-aerosol-spread-of-covid-19, there is a link at the bottom to a Google Docs file, at https://docs.google.com/document/d/1fB5pysccOHvxphpTmCG_TGdytavMmc1cUumn8m0pwzo/preview?pru=AAABdQ5s5mA*YrLy9epGlHWhKPSl5JMT3w#

Clicking on this link crashes NetNewsWire 5.1 (3007).

Crash log is attached.
[NetNewsWire Crash.txt](https://github.com/Ranchero-Software/NetNewsWire/files/5320130/NetNewsWire.Crash.txt)

**Comment by Wevah** [comment] 2020-10-02 20:42
Duplicate of #2445.

**Closed by Wevah** 2020-10-02 20:42 UTC
