### ISSUE TITLE
Feed detection doesn't convert feed: into http(s):

### ISSUE THREAD

**Issue by Wevah** [Ranchero-Software/NetNewsWire#1896] opened 2020-03-13 16:22 UTC
Pasting a `feed:` URL into the add sheet works correctly, but if an HTML page URL is pasted and its `link rel="alternate"` points to a `feed:` url, it's not converted to `http(s):`.

**Comment by vincode-io** [comment] 2020-03-13 16:24
Assigning to 5.0.1 since this looks like it is a regression.

**Closed** 2020-03-13 17:15 UTC
Labels: iOS, macOS
