### ISSUE TITLE
Folders in sidebar should be draggable

### ISSUE THREAD

**Issue by slater** [Ranchero-Software/NetNewsWire#1921] opened 2020-03-17 02:44 UTC
I have a number of folders from an imported OPML file, and they seem to be "stuck" to the bottom of the feed list. Any way to move them to the top, just under the "On My Mac" heading?

**Comment by brentsimmons** [comment] 2020-03-17 02:46
Folders are sorted alphabetically. Could that be it?

If not, would you post a screenshot here so we can see what you see?

**Comment by slater** [comment] 2020-03-17 04:33
Easier to describe: Right now, i have ~200ish feeds not in folders. Below that are the folders with some more feeds in them. I have yet to figure out how I can move those folders to a position ABOVE the ~200ish feeds

**Comment by brentsimmons** [comment] 2020-03-17 21:54
Got it. We put the top-level feeds on top, on the theory that those are your most important feeds.

But we also understand that they could be least-important — so unimportant that you haven’t even bothered to categorize them yet.

Thanks for the feature request!

**Comment by vincode-io** [comment] 2020-03-18 07:30
Duplicate of #760

**Closed by vincode-io** 2020-03-18 07:30 UTC
Labels: macOS
