### ISSUE TITLE
Feature request: QuickLook image viewer

### ISSUE THREAD

**Issue by uncleungie** [Ranchero-Software/NetNewsWire#1954] opened 2020-03-28 07:42 UTC
The iOS app has a handy image viewer that can be invoked by tapping an image in the article view. Currently, the macOS app lacks this feature.

Could this feature be implemented on the Mac by enabling QuickLook for article view images? This would be invoked by double clicking an image or clicking once to focus/highlight an image and then pressing the space bar.

I have very poor eyesight, and zooming in on images is a daily task for me. I use it all the time in the iOS app!

**Comment by vincode-io** [comment] 2020-03-28 11:43
Duplicate of #647

**Closed by vincode-io** 2020-03-28 11:43 UTC
