### ISSUE TITLE
Feature request: < macOS & iOS > Add date separation

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2536] opened 2020-10-30 09:28 UTC
It’d be useful, I think, just a segmented control for “Today/Other Days” or a separation in the home feed or the folders to go fast in one specific date or just like a separation.

**Comment by vincode-io** [comment] 2020-10-30 09:34
Could you be more specific?  Where would this segmented control go?  What would be the segments?  What is a "home feed"?  How would we go fast to a specific date?

I'm just having a lot of trouble following what you are asking for.

**Comment by kevinm6** [comment] 2020-10-30 10:44
Sorry, I wasn’t clear.
I’m asking for a “search/filter by date” added at the current one for [“Here” | "All Articles”].
Where you can choose dates to filter with a date picker.
This is some example, not well done for what I mean.

![nnw](https://user-images.githubusercontent.com/72861758/97695958-22c20a00-1aa5-11eb-902d-7da67fc95927.png)
![nnw2](https://user-images.githubusercontent.com/72861758/97695955-22297380-1aa5-11eb-91dd-0b7e15782562.png)
![nnw3](https://user-images.githubusercontent.com/72861758/97695944-1e95ec80-1aa5-11eb-8445-1d3ca1488c41.png)

**Comment by brentsimmons** [comment] 2023-03-06 05:23
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/866

**Closed by brentsimmons** 2023-03-06 05:23 UTC
