### ISSUE TITLE
Folder name will be HTML-encoded

### ISSUE THREAD

**Issue by octref** [Ranchero-Software/NetNewsWire#2295] opened 2020-07-24 07:24 UTC
NNW Version 5.0.3 (2618)

- Have a folder such as `blog <personal>`
- Restart NNW
- It will become `blog &lt;personal&gt;`

![image](https://user-images.githubusercontent.com/4033249/88369015-b65aaf00-cdc1-11ea-8906-990c23638b60.png)

**Comment by vincode-io** [comment] 2020-07-24 16:05
Duplicate of #1924.

**Closed by vincode-io** 2020-07-24 16:05 UTC
