### ISSUE TITLE
iOS: Article List should truncate by word rather than character

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1840] opened 2020-02-28 23:00 UTC
This is a really weird thing, because iOS tends to also truncate blank spaces. You can see this behavior in the bottom of the screenshot. The words “custom properties” get truncated to “custom...” indicating the word might be something like “custom-....” which is pretty confusing, especially in german (and maybe other languages) where quite the amount of constructed words exist that are tied together with a - .

![68B4931F-9DB1-47D5-B10F-6636F5D9BB73](https://user-images.githubusercontent.com/1244071/75593668-608a1100-5a86-11ea-89ef-278e4b0c292b.jpeg)

I think readibility would greatly benefit from that small change and people with voice-over activated will thank you as well.

🙂

**Comment by vincode-io** [comment] 2020-02-28 23:05
This behavior is defined by UILabelView. Is there some way to use UILabelView that I’m not aware of that provides the truncating behavior you describe?

BTW, VoiceOver reads the full label text even if it is visually truncated.

**Comment by flowinho** [comment] 2020-02-28 23:12
Didn’t know about voice-over. Thanks for teaching me.

Regarding UILabel: Well, you could realize this behavior by using its `linebreaks` functionality. However I currently cannot browse the code very well so I don’t know about the Setup of the cells. 

Aren’t those labels multi line?

**Comment by vincode-io** [comment] 2020-02-28 23:13
They are and use truncating tail to truncate multiline labels.

**Comment by vincode-io** [comment] 2020-02-28 23:15
I’m closing this one since it is functioning as designed. Feel free to keep commenting if you want further clarification.

**Closed by vincode-io** 2020-02-28 23:15 UTC

**Comment by flowinho** [comment] 2020-02-28 23:19
I feel like while UILabel is working as designed by Apple it is still not a good solution for an app focused on reading.
