### ISSUE TITLE
(iOS client bug report)Can't add feeds by tapping the feed link.

### ISSUE THREAD

**Issue by A11URR** [Ranchero-Software/NetNewsWire#2878] opened 2021-03-13 10:50 UTC
If you tap the RSS feed link of any website in Safari, and then tap Open in the 'Open this page in "NetNewsWire"?' view, the app will open, but you won't be able to add the feed because the "Add Web Feed" screen won't appear. You can add it without any problem by entering the feed URL of the same site from the "+" button in the application.

## Screen Recording
https://user-images.githubusercontent.com/73989586/111027217-29d52d80-8432-11eb-9458-13dea897d273.mp4

## Versions and Devices information
NewNewsWire 5.0.5 (build 56)
iOS 14.4.1, iPadOS14.4.1
iPhone 8 Plus, iPad Pro 11(1st gen)
Language setting is Japanese.

**Comment by vincode-io** [comment] 2021-03-13 16:59
Duplicate of #2703.

**Closed by vincode-io** 2021-03-13 16:59 UTC
