### ISSUE TITLE
Phantom unreads

### ISSUE THREAD

**Issue by kdawson** [Ranchero-Software/NetNewsWire#3369] opened 2021-12-15 15:06 UTC
Starting sometime in the last few days, when I leave NNW open the feeds list on the left will show some number of unread items across a number of feeds. Click on any of them and the phantom unread count clears; there weren't really any unread.

Note that in this scenario I haven't requested a refresh with cmd-R; when I do so any resulting unread counts are real.

Version 6.0.3 (6035). Not sure when last updated.

**Comment by vincode-io** [comment] 2021-12-15 16:39
Did you recently upgrade your macOS version?

**Comment by kdawson** [comment] 2021-12-15 19:17
Yes, from Mojave (MacOS 10.14) to Monterey (MacOS 12).

**Comment by vincode-io** [comment] 2021-12-15 19:33
We've been getting reports of users databases getting corrupted when upgrading to Monterey, but we're not sure how it is happening. Did you do a straight upgrade or did you back up and restore from Time Machine?

What kind of account are you using? We may have to recreate it to clear up your problem.

**Comment by kdawson** [comment] 2021-12-15 19:40
I got a new machine with Monterey installed; restored my data from Time Machine backup of the Mojave machine.

I don't know what you mean by "what kind of account." I didn't pay anything for a subscription. Otherwise I don't recall setting up anything like a user/password for NNW.

**Comment by vincode-io** [comment] 2021-12-15 19:55
For some reason when restoring from a Time Machine backup, the NNW database gets corrupted. We haven't been able to figure it out yet.

You are probably using the On My Mac account type. If you export the OPML file from that account, you can create a new On My Mac account and import the OPML file into it. You can then disable the old On My Mac account. It won't transfer your starred items or unread items, but at least it will start working again.

**Comment by vincode-io** [comment] 2021-12-15 19:59
I'm going to close this issue as a duplicate of #3228.

@kdawson Please let us know if you need more help fixing your database by commenting on this issue, even though it is closed.

**Closed by vincode-io** 2021-12-15 19:59 UTC

**Comment by kdawson** [comment] 2021-12-15 20:19
OK thanks, exported to .opml, deactivated the old account, created a new On My Mac account, and imported. All good. But the old account can't be deleted: the "-" at the bottom is and remains greyed-out. Advice?

**Comment by vincode-io** [comment] 2021-12-15 20:24
You don't need to delete it. If you deactivate it, it won't show up in the main NNW window.

**Comment by kdawson** [comment] 2021-12-16 16:59
The new set of feeds, from the imported .opml, behaves in just the same way. Phantom unreads spontaneously pop up. Just FYI, I can live with it, not that serious.

**Comment by vincode-io** [comment] 2021-12-16 17:13
I think you are probably going to have to go nuclear and start over. Save your OPML file somewhere and then run this command in the Terminal.

`rm -rf ~/Library/Containers/com.ranchero.NetNewsWire-Evergreen `

That will remove all of NNW's data. You can then relaunch NNW and it should be as if you just installed it for the first time. The main On My. Mac account should also work again.
