### ISSUE TITLE
Feature Request: Menubar option?

### ISSUE THREAD

**Issue by MoaiGuy** [Ranchero-Software/NetNewsWire#2698] opened 2021-01-02 21:09 UTC
Is it possible to make NNW support the same feature that RSS Bot do: https://apps.apple.com/us/app/rss-bot-news-notifier/id605732865?mt=12
Quite simple app with one feature:
Delivering RSS feeds that you can open via the menubar through your preferred browser.

**Comment by vincode-io** [comment] 2021-01-02 22:08
Duplicate of #890.

**Closed by vincode-io** 2021-01-02 22:08 UTC
