### ISSUE TITLE
Allow reordering of feeds and folders

### ISSUE THREAD

**Issue by WanderingStar** [Ranchero-Software/NetNewsWire#760] opened 2019-06-16 23:35 UTC
I'd like to read my feeds in a particular order (eg. stuff from my friends before art before humor before news). Vienna RSS let me organize my feeds by dragging them around in the feed list, but NNW seems to display them alphabetically. It would be nice to be able to choose the order.

I know that I can prefix my feed names (eg, "01 Friends", "02 Art",... for the respective folders) to get them to sort in the order that I want them, but that seems like a cumbersome workaround and unintuitive.

**Comment by HillbillyInBC** [comment] 2019-08-10 16:26
Seconded.  The app is unusable for me until this essential feature is included.

**Comment by timlance** [comment] 2019-08-15 02:39
+1 for reordering! I have a flow which I much prefer.

**Comment by tcuzzillo** [comment] 2019-09-02 00:34
The app is almost unusable without the ability to reorder feeds and folders.

**Comment by WanderingStar** [comment] 2019-09-02 00:38
If y'all who think the app is actually unusable want a workaround...

![image](https://user-images.githubusercontent.com/1622203/64084331-07683d00-ccf0-11e9-9522-f831d51589be.png)

You can name your folder so that they sort in the desired order.

**Comment by HillbillyInBC** [comment] 2019-09-02 01:44
> You can name your folder so that they sort in the desired order.

Doesn't work for my desired order (and by "desired" I mean "deeply embedded in my subconscious for most of the 15 years I've been using NNW").  My current subscription list starts with two folders, then three subscriptions that aren't filed in folders, then several more folders, then a dozen more unfiled subscriptions, and carries on in this fashion for quite a lengthy list that is arranged in the precise order I expect to see things.  If I use your workaround, the unfiled subscriptions always precede the folders no matter what sort of name games I play.  I suppose I could invent new folders to fill the gaps, but then they would have silly names like "09 Several unrelated subscriptions grouped together for no apparent reason, part the fifth".  Guess I'd rather wait until NNW5 behaves like its predecessors in this significant matter.

**Comment by noahkuhn** [comment] 2019-09-03 20:03
Yeah, this is a no brainer, +1

**Comment by Alvy** [comment] 2019-09-04 11:01
+1 for me too.

Also it would be interesting to have the old '[x] don't refresh this subscription' or 'refresh every [xx] hours' in the info box of the subscriptions.

**Comment by brentsimmons** [comment] 2019-09-04 20:00
@Alvy Would you make that a separate feature request? Thanks!

**Comment by Nothorse** [comment] 2019-09-06 12:35
I have to +1 this too.

And even more I'd love to see nested folders again. That is the one essential NNW feature that I've found nowhere else (and consequently never changed from NNW to any other news reader

**Comment by tcuzzillo** [comment] 2019-09-06 15:33
+1 for nested folders.

**Comment by timlance** [comment] 2019-09-06 21:22
I have been clamoring for this from the first announcement of your returning.

I appreciate your latest info and grudgingly must accept it. Not least because it’s your app! ;)

I do wonder if there might be a push by folks who would be willing to take the risk and so ask for an option to use an in app browser.

But I think I for one will accept, most likely even prefer, a ‘reader type’ view. Can I assume there would be an easy to implement option to view any particular page in browser and not ‘reader view’ within NNW?

Best!
tim

**Comment by scbarton** [comment] 2019-10-17 13:32
+1 for reordering feeds and folders. It's the main think that keeps me using ReadKit.

**Comment by fuzzy76** [comment] 2020-04-14 16:33
This is even worse for a feedbin synced account. Feedbin doesn't do folders, but tags. And I only tag a few feeds, I don't see a reason to enforce tagging for absolutely everything. But my tags are the "important" ones, and hidden on the bottom...

**Comment by ErniePC12** [comment] 2020-05-20 13:24
Sorry for beating a dead horse, but I would really like this option as well.

**Comment by tcuzzillo** [comment] 2020-05-20 15:50
It's not a dead horse as long as there's someone who keeps developing NetNewsWire. Everyone who wants this feature should keep beating, beating, beating.

**Comment by HillbillyInBC** [comment] 2020-05-20 15:59
I would even contend that NetNewsWire is a dead horse until this feature is included. I certainly have no interest in using it before then.

**Comment by brentsimmons** [comment] 2020-05-20 16:20
@HillbillyInBC It doesn’t make us more likely to add a feature you want when you call our app a dead horse!

We’re a collection of volunteers who work hard and do our best to bring people a free, high-quality app. We could be spending our free time doing something else!

**Comment by brentsimmons** [comment] 2020-05-20 16:25
There’s never a need to "beat" on us for a feature. We’re aware of this feature request and all the others.

Figuring out what to do and when is complex. There are a lot of variables to consider — but people "beating" on us for a feature isn’t one of those variables.

**Comment by tcuzzillo** [comment] 2020-05-20 16:29
Dear NNW volunteer developers, Don't take "beat" literally. Better words are remind, ask, cajole, and probably a bunch of others. Just keep doing what you're doing. It's a terrific app already, and so much better than the rest or I wouldn't use it.

**Comment by WanderingStar** [comment] 2020-05-20 16:47
As the person who originally opened this feature request, I just want to say that I _do_ use NNW every day and really appreciate it, even in the absence of this feature. Thanks @brentsimmons and the rest of the devs!

**Comment by ErniePC12** [comment] 2020-05-20 17:03
@brentsimmons I didn't want to seem like nagging which is why I used the horse phrase.  I have so much muscle memory from the old version that I find it very hard to use the newer version.  And because I know that this is all a volunteer effort.  I really wish I had the ability to help you all.

**Comment by HillbillyInBC** [comment] 2020-05-20 17:06
Duly noted. Apologies for the brusque metaphor. I'll keep watching this issue for resolution of this disqualifying defect, and keep using NNW 4 in the interim.

**Comment by chrisgrande** [comment] 2021-04-03 22:14
I'd like to add — under the functionality of reordering — the ability to set to auto order, based on the feed with the latest article.

**Comment by brentsimmons** [comment] 2023-03-06 01:11
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/356

**Comment by brentsimmons** [comment] 2023-03-06 01:11
“Not planned” doesn’t mean we’ll never do this. That’s just means I’m closing this as a duplicate of another earlier ticket

**Closed by brentsimmons** 2023-03-06 01:11 UTC

**Comment by tbodt** [comment] 2023-03-06 01:13
This doesn't seem to be the same as #356? That's about sorting automatically by name or date, and this's about sorting manually.

**Comment by brentsimmons** [comment] 2023-03-06 01:15
Good point — but in my head it’s the same thing. “Manual order” is just one of the types of sorts possible.
