### ISSUE TITLE
Customize UI Colors

### ISSUE THREAD

**Issue by forrie** [Ranchero-Software/NetNewsWire#922] opened 2019-08-31 16:54 UTC
It would be great to allow some customization of the colors in the UI.  For example, the blue titles, I'd prefer Slashdot title bars.  This should be easy to do.  Others may want to do further customizations, including "dark mode" on the Mac, etc.

**Comment by brentsimmons** [comment] 2019-08-31 17:12
Are you talking about the article pane? Or also the sidebar and timeline, or…?

**Comment by forrie** [comment] 2019-08-31 17:31
Primarily the article pane - though others may wish to customize both.   Support for Dark Mode would be good, too :)  Thank you.

**Comment by brentsimmons** [comment] 2019-09-04 05:20
We do have Dark Mode, by the way. It follows the system setting.

**Comment by alessiomaffeis** [comment] 2020-01-28 10:12
I second this issue, but mostly due to the fact that the background colour **on iOS** seems to be solid black, which is not really easy on the eye all the time.

As a minimum, it would be great to offer an alternative "Lighter" Dark Theme option, as many apps do. Any thoughts on that, @brentsimmons? :)

**Comment by brentsimmons** [comment] 2020-01-28 17:18
On both Mac and iOS, we use the colors Apple provides for Dark Mode. I don’t expect us to create any additional themes any time soon — there are so many more other things to do.

**Comment by forrie** [comment] 2020-01-29 18:45
You an provide a simple method (or "theme") to change the font colors and font background -- that's not a lot of development time.  For example, I prefer /. (Slashdot) colors as it's easier (for me to read).   I would prioritize simple items like this that make the UI at least conform to some basic preferences.

**Comment by forrie** [comment] 2020-08-27 18:06
Here's a direct example:

Presently, NetNewsWire only presents this color/theme (which I find difficult to read for my eyes):

<img width="849" alt="Screen Shot 2020-08-27 at 2 04 28 PM" src="https://user-images.githubusercontent.com/228967/91478698-5054c200-e86e-11ea-906d-442006ee35c8.png">

Slashdot has this color theme, which I find easier to scan/read:

<img width="963" alt="Screen Shot 2020-08-27 at 2 04 43 PM" src="https://user-images.githubusercontent.com/228967/91478706-521e8580-e86e-11ea-8332-ca5d95a15ad6.png">

I would think that allowing the customization of some of these elements, in user preferences, would be a good idea.

**Comment by vincode-io** [comment] 2020-12-24 16:38
Duplicate of #19.

**Closed by vincode-io** 2020-12-24 16:38 UTC
