### ISSUE TITLE
Render Media Attachments in RSS Feed

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3754] opened 2022-11-22 03:06 UTC
The below XML contains media attachments (images) that are not rendered by NetNewsWire. This _should_ be supported?

```xml
<item>
      <guid isPermaLink="true">https://mastodon.social/@stuarticus/109362403944020073</guid>
      <link>https://mastodon.social/@stuarticus/109362403944020073</link>
      <pubDate>Fri, 18 Nov 2022 02:17:33 +0000</pubDate>
      <description>&lt;p&gt;Smashing morning for a cycle.&lt;/p&gt;</description>
      <media:content url="https://files.mastodon.social/media_attachments/files/109/362/400/645/102/130/original/13dc804f6215a91f.jpg" type="image/jpeg" fileSize="381023" medium="image">
        <media:rating scheme="urn:simple">nonadult</media:rating>
        <media:description type="plain">Sunrise photo from the F1 pit lane.</media:description>
      </media:content>
      <media:content url="https://files.mastodon.social/media_attachments/files/109/362/401/602/664/228/original/ac6af9ed67737d5a.jpg" type="image/jpeg" fileSize="265961" medium="image">
        <media:rating scheme="urn:simple">nonadult</media:rating>
        <media:description type="plain">Group photo, with bikes, at the Singapore flyer.</media:description>
      </media:content>
</item>
```

**Comment by gferreroferri** [comment] 2022-11-23 12:43
Same happens with this feed
https://www.helsinginuutiset.fi/feed/rss

```
<item>
<title>Uuden Lastensairaalan korjausten maksajasta ei vielä tietoa – SRV: "Totta kai tuli yllätyksenä"</title>
<link>https://www.helsinginuutiset.fi/paikalliset/5524355</link>
<description>Korjaustyöt kestävät viikkoja.</description>
<guid isPermaLink="true">https://www.helsinginuutiset.fi/paikalliset/5524355</guid>
<category>Paikalliset</category>
<enclosure url="https://i.media.fi/incoming/uvmqf1/2363958.jpg/alternates/LANDSCAPE_960/2363958.jpg" length="0" type="image/jpg"/>
<source>Helsingin Uutiset</source>
<pubDate>2022-11-22T14:15:00+02:00</pubDate>

```

**Comment by vincode-io** [comment] 2022-11-29 01:03
Duplicate of #2538.

**Closed by vincode-io** 2022-11-29 01:03 UTC
