### ISSUE TITLE
Feature Request: Article body text color

### ISSUE THREAD

**Issue by circa1977** [Ranchero-Software/NetNewsWire#2394] opened 2020-09-04 13:01 UTC
It'd be great if the article body text color could be a preference, to render higher contrast and/or black. More than any other app I'm reading in, the gray on white text in NNW almost creates a shadow or blur down the middle that makes it hard for me to read.

The ability to bump down the font size a bit, too, would be welcome. I've had a hard time finding a 4K/UHD monitor smaller than 27", and on a smaller desk the monitor is close and text is huge.

Thanks!

**Comment by vincode-io** [comment] 2020-09-08 22:51
Those are great suggestions.  We plan to let you customize the article view.  In fact it is one of our oldest outstanding features that we have yet to implement.

Duplicate of #19.

**Closed by vincode-io** 2020-09-08 22:51 UTC
