### ISSUE TITLE
Make shift-space work to scroll up when article pane does not have focus

### ISSUE THREAD

**Issue by brentsimmons** [Ranchero-Software/NetNewsWire#969] opened 2019-09-05 04:48 UTC

**Comment by Wevah** [comment] 2020-07-10 18:07
Should this only scroll up, or also go to the previous unread when scrolled to the top (to mirror plain spacebar)?

**Comment by Wevah** [comment] 2020-07-10 18:55
Duplicate of #452.

**Closed by Wevah** 2020-07-10 18:55 UTC
