### ISSUE TITLE
Default all feeds to hide read articles

### ISSUE THREAD

**Issue by dbarros** [Ranchero-Software/NetNewsWire#3840] opened 2023-02-01 22:42 UTC
My apologies if this has been raised before. I did do a search in Issues, but couldn't see something exactly like what I'm looking for (although I'm sure someone will let me know soon enough that there is).

When I setup NNW on a new Mac, connect my Feedly account, it would be nice to be able to have a global option that made all feeds hide read articles by default. I end up clicking on the _Hide Read Articles_ button for each feed as I visit them.

**Comment by brentsimmons** [comment] 2023-03-05 20:31
Needs design.

**Comment by brentsimmons** [comment] 2023-03-11 04:36
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/3030

**Closed by brentsimmons** 2023-03-11 04:36 UTC
