### ISSUE TITLE
Feature Request: Per-Feed "Automatically Mark as Read"

### ISSUE THREAD

**Issue by letrastudio** [Ranchero-Software/NetNewsWire#3094] opened 2021-04-28 19:20 UTC
A feed set to Automatically Mark as Read would never show an unread count or a single blue dot, unless an entry is manually marked as unread. This would be a context menu option for feeds, and ideally also for folders, applying to every feed within. Could be a simple boolean flag (option A) or, going a bit further, a drop-down list with some sensible time delay options (option B):

![automatically mark as read](https://user-images.githubusercontent.com/4627002/116457831-cd03ca00-a85b-11eb-990e-6f8486086c65.png)

This feature would basically be the opposite of "Show Notifications for New Articles." Some feeds just aren't very important, are too high-volume, or quickly lose relevancy, but you might not want to get rid of them. Setting an automatic expiration date for new posts would be a great option to reduce unread count anxiety and FOMO.

I'm already using Feedbin Actions to achieve this by marking some high-volume folders as read immediately, and I absolutely love using NNW's Today smart feed in conjunction with that. **It makes the Today feed content-rich, but keeps its unread count low.** If I'm in a hurry I just scan the unread posts, but if I have more time I'll also look at some of the others. But it's a shame that I can't control that directly in NetNewsWire whenever I feel that some feed becomes more or less deserving of my attention.

**Comment by Aetles** [comment] 2021-05-06 22:49
I have the same feature request. 

I use the Twitter feeds in NNW as a searchable Twitter archive of my timeline (because NNW is by far the best solution I've found for this!) but I would like for them to be marked as read immediately, since I'm not using NNW to actually read every tweet.

**Comment by eivindml** [comment] 2021-08-18 12:17
I would also love something like this. Like a "pause", "archive" or "unsubscribe" feature. There are some feeds that I don't want to follow that closely, or stop following for a period, but don't wan't to delete it completely, so I can still keep the feed for later. Any feature that would let me do something like this, would be very nice.

For now I'll create a separate "Archive" folder, and just immediately mark them all as read. Only issue is that I have to move the "paused" feeds to this folder, so my organization is lost.

**Comment by vsheg** [comment] 2022-04-09 18:30
Up!
"Leave only the last N articles unread" is also useful. News feeds spam you with dozens of "here and now" articles and you physically can read only a few of them and really want to ignore the rest. But some resources publish long-reads a couple times a month, so you want to store a few of them unread for a long time sometimes.

**PS** Amazing app. Thanks for the work.

**Comment by brentsimmons** [comment] 2023-03-06 16:54
Duplicate of #74

**Closed by brentsimmons** 2023-03-06 16:54 UTC
