### ISSUE TITLE
Add support for mute filters

### ISSUE THREAD

**Issue by j-f1** [Ranchero-Software/NetNewsWire#3018] opened 2021-04-18 15:53 UTC
Feedly has a feature called [Mute Filters](https://blog.feedly.com/leo-and-mute-filters/) which allows you to hide articles in given feeds/folders that match a given word or phrase. This is great for feeds which include ads (especially ones made from mailing lists) because you can set up a mute filter to remove such articles.

<img width="500" alt="Screenshot_2021-04-18 11 51 54" src="https://user-images.githubusercontent.com/25517624/115151802-7cf75d00-a03c-11eb-80b7-47fe9585979f.png">

Of course, you don’t get the benefit of mute filters if you use a non-Feedly account, so it would be great to have this feature inside of NNW!

**Comment by kielgillard** [comment] 2021-04-18 22:42
While I suspect this is a request to have a UI in NNW to configure mute filters, I'm just making sure the same articles still appear on Feedly web and NNW after you set them up on Feedly web, right?

**Comment by j-f1** [comment] 2021-04-19 02:15
Yep! After muting an article via Feedly, NNW sees it as read so it doesn’t show up in the all unread list.

**Comment by bbsixzz** [comment] 2021-09-07 01:18
I use feedrinse.com to clean up my feeds from ads etc.

Not having to rely on a third party would be awesome.

**Comment by exrector** [comment] 2021-09-27 08:33
[Waiting ](https://github.com/Ranchero-Software/NetNewsWire/issues/1864#issuecomment-846121895)

**Comment by justinferrell** [comment] 2022-08-22 09:13
Very interested in this feature as well. I use the native iCloud sync for NNW and being able to filter/remove/block articles with keywords in the title would be a huge improvement for me personally.

**Comment by vincode-io** [comment] 2022-09-01 22:38
Duplicate of #1864

**Closed by vincode-io** 2022-09-01 22:38 UTC
