### ISSUE TITLE
Feed Statistics

### ISSUE THREAD

**Issue by vruyr** [Ranchero-Software/NetNewsWire#3561] opened 2022-05-15 22:54 UTC
Detection and reporting of dead feeds is currently not supported in NetNewsWire. Dead and inactive feeds slow down the Refresh without contributing anything.

It is possible to export the feeds as an opml file and run a script over it to detect dead feeds:

```shell
xpath -q <Subscriptions-iCloud.opml -e '//*[local-name()="outline"]/@xmlUrl' | sed 's/^[[:space:]]*xmlUrl="//; s/"$//;' | xargs -n1 curl -fsL -o /dev/null -w '%{http_code}\t%{url}\t%{redirect_url}\n' | grep -v $'^200\t'
```

But detection of inactive feeds would be more involved, and overly active and noisy feeds would be even harder to identify.

Please implement a feature where NetNewsWire will flag in the UI feeds that report error codes (404, 403, etc.) and show statistics of number of articles per period of time for each feed and allow for sorting.

An example implementation is available at Feedly's Organize Feeds page which allow for filtering the list by Inactive, Unreachable, etc., display the number of items the feed publishes a month and when was the last item published.

This will allow the user to analyze currently followed feeds and do a cleanup.

**Comment by vincode-io** [comment] 2022-05-26 19:56
Duplicate of #1107

**Closed by vincode-io** 2022-05-26 19:56 UTC
