### ISSUE TITLE
YouTube videos crash when rotating iPhone screen

### ISSUE THREAD

**Issue by stewf** [Ranchero-Software/NetNewsWire#3724] opened 2022-10-27 04:41 UTC
Open [a post](https://www.macrumors.com/2022/10/26/ipad-10-m2-ipad-pro-hands-on/) with an embedded YouTube video. Play video and go full screen. Rotating the screen stops the video and returns to post view. 

I’m using NNW 6.0.2.

**Comment by vincode-io** [comment] 2022-10-29 00:33
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/2369.

**Closed by vincode-io** 2022-10-29 00:33 UTC
