### ISSUE TITLE
YouTube Feeds not working 

### ISSUE THREAD

**Issue by astrojebus** [Ranchero-Software/NetNewsWire#3196] opened 2021-06-26 10:27 UTC
Hello guys , I just found your app and I love it but I can’t get YouTube channel Feeds to pull content but it gets the items lists however

**Comment by ednl** [comment] 2021-07-27 11:15
This is true but I hadn't really missed it: no content, just titles for YouTube channel subscriptions. This would be great to have as a bonus.

However, for me the more interesting issue is how to even add a YouTube channel subscription! Google/YouTube seems to make it harder and harder to discover the RSS feed url of channels ;( I manage to do it manually but it takes a lot of effort (exporting, looking up the Channel ID, editing, importing). It would be awesome if the toolbar icon extension could do that for me!

**Comment by pimoore** [comment] 2022-02-14 03:31
Any update on this bug, as I’m still seeing blank content in YT feeds both in iCloud and local device.  The same feeds show the thumbnail embed and description if using Feedbin on the backend.  The links themselves can still be sent to the browser or YT app for viewing, but definitely annoying not to see the details first.

**Comment by vincode-io** [comment] 2022-02-21 22:22
Duplicate of #2538.

**Closed by vincode-io** 2022-02-21 22:22 UTC
