### ISSUE TITLE
Two features I wish existed

### ISSUE THREAD

**Issue by sauljaffe** [Ranchero-Software/NetNewsWire#3667] opened 2022-08-28 12:13 UTC
Not interested in coding, and I don't have access to the Slack group so I hope it's ok to post this here.

Feature 1: Eliminate duplicates.

Description: Very often when I subscribe to news services like the CBS news feed, I'll pull the "national" news and the "regional" news and the "local" news... and I'll see three copies of the same article because CBS created 3 different RSS links for it, one in each group. This gets really annoying when multiplied by the number of articles pulled, and wastes my time scrolling through them. On an average day, I see at least 100 duplicates (i.e. 3 or 4 copies of about 20-30 articles). I don't know how easy it is to implement but I wish the newsreader could/would detect that these were duplicates and only present me with the first one it found. It can hide the others automatically, or delete them, I don't care. 

Feature 2: Eliminate video feeds

Description: Often, the RSS link/header that gets pulled to an article is just a video. That is, there's no text for the actual article, just a video. I wish there were a way for the newsreader to detect this and hide or delete the header. These really waste my time as I'm not interested in pulling videos. If I wanted videos, I would watch the tv news or watch a youtube channel with the videos, or whatever was required to watch those videos. But, I'm not interested in the videos! They just waste my time!

Thank you for an otherwise great software.

**Comment by vincode-io** [comment] 2022-09-01 23:53
The first item is a duplicate of #847. We're already looking into it.

The second item would have very little utility for almost all of the NetNewsWire users. It is very particular to your desired workflow. We have to be judicious about which features we implement so that NetNewsWire doesn't become bloated and difficult to use. I'm sure you understand.

**Closed by vincode-io** 2022-09-01 23:53 UTC
