### ISSUE TITLE
Feature Request (iOS & macOS): Option to manually order (sort) feeds and folders and sync with iCloud

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#3096] opened 2021-04-29 08:01 UTC

**Comment by vincode-io** [comment] 2022-06-08 20:31
Duplicate of #2997

**Comment by kevinm6** [comment] 2022-09-01 22:58
Sorry, but I don't think it's the same.
I was not very clear explaining the request.
My idea is to have the ability to sort the feeds manually in the "Feed View", inside of a folder or the main sync service.
Now is impossible due to the alphabetical sort.

The issue you mentioned is about choose sorting method per folder/smart-feed.
Mine is more allow edit the main UITableView and sync the changes between devices on iCloud

**Comment by vincode-io** [comment] 2022-09-01 23:34
Sorry about that. I meant to link #760.

**Comment by brentsimmons** [comment] 2023-03-06 16:53
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/356

**Closed by brentsimmons** 2023-03-06 16:53 UTC
