### ISSUE TITLE
macOS: Hidden parts of the sidebar should be hidden after relaunch of the app

### ISSUE THREAD

**Issue by irodknocker1** [Ranchero-Software/NetNewsWire#1815] opened 2020-02-24 14:26 UTC
Could you take care that parts of the Sidebar which i hide are hidden after i quit the app and launch it?

![bildschirmfoto_2020-02-23_um_10 02 57](https://user-images.githubusercontent.com/61420503/75160197-e4a46780-5719-11ea-8719-ce307a3bd686.jpg)
![bildschirmfoto_2020-02-23_um_10 02 35](https://user-images.githubusercontent.com/61420503/75160207-e9691b80-5719-11ea-8c1e-36c197f6eb13.jpg)

**Comment by vincode-io** [comment] 2020-02-24 15:48
This is a duplicate of #494 which is where we are tracking window state saving.

**Closed by vincode-io** 2020-02-24 15:48 UTC
