### ISSUE TITLE
Feature request: Pause a subscribed feed

### ISSUE THREAD

**Issue by erik-visser** [Ranchero-Software/NetNewsWire#3304] opened 2021-09-25 07:00 UTC
I would love to be able to pause a feed. Having feeds that are still there but don't update. Of course there is unsubscribing, but then it's gone from the list and the internet is a big place, finding it again when I crave it is difficult and keeping a list outside NetNewsWire is an ugly hack.

**Comment by kevinm6** [comment] 2021-09-25 08:00
> I would love to be able to pause a feed. Having feeds that are still there but don't update. Of course there is unsubscribing, but then it's gone from the list and the internet is a big place, finding it again when I crave it is difficult and keeping a list outside NetNewsWire is an ugly hack.

Hi, I think this issue could be similar or the same as [one that](https://www.github.com/ranchero/netnewswire/issue/2837) I open some months ago, and NNW Devs reply me already

**Comment by vincode-io** [comment] 2021-09-25 11:44
Duplicate of #2837

**Closed by vincode-io** 2021-09-25 11:44 UTC
