### ISSUE TITLE
Feature Request: Option to clear cache in iOS

### ISSUE THREAD

**Issue by macmx09** [Ranchero-Software/NetNewsWire#3240] opened 2021-08-01 08:31 UTC
On my iPhone (App Size 11,8MB Documents&Data 1,17GB, iOS 14.7.1) and on my iPad (App Size 11,8MB Documents&Data 999,8MB, iOS 14.7.1) the app data is growing rapidly each day. An option to clear cache would be greatly appreciated.

**Comment by kevinm6** [comment] 2021-08-01 12:55
#2969

**Comment by vincode-io** [comment] 2021-08-05 21:54
Please see this comment: https://github.com/Ranchero-Software/NetNewsWire/issues/2969#issuecomment-813104011 

Duplicate of #2969

**Closed by vincode-io** 2021-08-05 21:54 UTC
