### ISSUE TITLE
Force refresh favicon

### ISSUE THREAD

**Issue by gingerbeardman** [Ranchero-Software/NetNewsWire#3436] opened 2022-01-30 16:29 UTC
One of my feeds has an old favicon listed against it.

I'm not sure how often, if ever, the favicon is refreshed.

So it would be good to have an manual option to do this.

I have tried removing the feed and adding it again, but the old icon persists.

**Comment by vincode-io** [comment] 2022-01-30 17:44
We clear the Favicon cache every 3 days. Just wait a few days and it will clear itself up. 

We work really hard to keep our settings and options clear and easy to understand. An option to flush the Favicon cache is such a rare and specific use case that I don't ever see us implementing it.

Closing this issue because NNW is functioning as designed in this case.

**Closed** 2022-01-30 17:44 UTC

**Comment by gingerbeardman** [comment] 2022-01-30 20:39
Thanks, that's good to know!

BTW I don't really mean there should be an option, so I'll be more clear with my language in future. I just meant it would be good if there was a manual way to do it, somehow.

I'd be happy if I could trash a file or type something on the command line, for example.

So I just set my date 3 days forward, opened NetNewsWire, then reset the date to automatic.

**Comment by vincode-io** [comment] 2022-01-30 21:08
Nice trick. If I had known you were on the Mac and had thought of it, I could have given you a command to delete the Favicon cache. 

Anyway, it looks like your trick worked and everything is good now.

**Comment by gingerbeardman** [comment] 2022-01-30 21:43
Next time! Cheers

**Comment by urda** [comment] 2023-09-17 04:45
> So I just set my system date 3 days forward, opened NetNewsWire, then set the system date back to automatic. 🔁

This was a HUGE help to me. My NetNewsWire recently pulled a bad / cached value and I couldn't figure out how to get it to resync: https://urda.social/@urda/111066006406420261

... I do wish the user could just slam a button in settings to force the issue.

**Comment by urda** [comment] 2024-01-17 23:34
I know this issue is closed but I'd still love a not-debug-menu button to force refresh my icons ❤️
