### ISSUE TITLE
Alert sound played inexplicably when scrolling with arrow keys

### ISSUE THREAD

**Issue by yuvalne** [Ranchero-Software/NetNewsWire#3970] opened 2023-05-09 16:19 UTC
When scrolling through an article with the arrow keys, the MacOS alert sound is heard:

https://github.com/Ranchero-Software/NetNewsWire/assets/97384040/2afcd8df-48ce-4c3a-9f3c-6398ce2217ab

Playing the sound makes sense when you reached the end of the article, but not while actively scrolling

**Comment by GetToSet** [comment] 2023-05-14 06:32
Hi @yuvalne, have you encountered this issue before or it only happens after a macOS or Safari upgrade?

It looks more like a WebKit isssue according to the following callstack and I could reproduce it as well with macOS 13.3.1 (a) and the latest Safari 16.4.

<img width="617" alt="Screenshot 2023-05-14 at 14 27 18" src="https://github.com/Ranchero-Software/NetNewsWire/assets/8158163/91d0c90d-e529-462d-9534-6cb09d1fffb4">

Still I'll try to take a deeper look at it.

**Comment by yuvalne** [comment] 2023-05-14 11:45
I believe this has been a thing for a while now, although as I only now bothered opening the ticket I can't really guarantee when it started.

**Comment by GetToSet** [comment] 2023-05-14 12:00
Some testing with my other Macs confirms this should be an issue introduced with macOS 13.3. It could be reproduced with other applications utilizing WKWebView (a component that loads renders HTML pages using WebKit Framework bundled along with the system) as well.

If this issue bothers, a quick solution would be turning down the ”Alert Volume” in “System Settings” - “Sound”.

Ethan Wong ***@***.***>

**Comment by GetToSet** [comment] 2023-05-15 08:24
Update: this issue has already been addressed recently on the upstream WebKit branch. More info could be found here: https://bugs.webkit.org/show_bug.cgi?id=255039.

Since this issue still persists on macOS 13.4 RC 2, we'll probably have to wait until the next macOS stable release after macOS 13.4 to carry this fix.

**Comment by brentsimmons** [comment] 2023-05-16 17:58
I think we can optimistically close this issue, given that the fix has been addressed in WebKit.

**Closed by brentsimmons** 2023-05-16 17:58 UTC
