### ISSUE TITLE
Unable to set browser on iOS/iPadOS

### ISSUE THREAD

**Issue by thommesborg** [Ranchero-Software/NetNewsWire#3261] opened 2021-08-21 06:45 UTC
NetNewsWire uses an instance of Safari for web-view. It ignores the chosen default browser, nor is there any dialog asking what browser to use with NetNewsWire. As FF and Brave have better privacy protection, I'd like to set the browser NetNewsWire makes use of.

**Comment by vincode-io** [comment] 2021-08-21 18:42
Have you tried to set your default browser to to FireFox or Brave? NetNewsWire does honor that setting when you select the Open in Browser option (for example under the Share menu when viewing the article).

If you are referring to the built in browser, it isn't possible to embed anything except WebKit on iOS. As a matter of fact, all browsers on iOS use WebKit because Apple doesn't allow other rendering engines to be installed. It is better to think of the embedded web view as the NetNewsWire Browser.

**Comment by thommesborg** [comment] 2021-08-21 20:02
@vincode-io thanks for the reply. By using the share menu there is no issue. But that's the share menu. By opening the article in the "built-in browser", a Safari-session will be opened. I knew about the WebKit-only issue, but browsers like Firefox or Brave provide better privacy than Safari, also when using WebKit.

**Comment by vincode-io** [comment] 2021-08-21 20:22
I think this is actually what you are asking for: #3029

**Comment by thommesborg** [comment] 2021-08-21 20:38
@vincode-io yep! Another wording but same need. Can you combine both issues?

**Comment by vincode-io** [comment] 2021-08-21 20:39
What we will due is file it as a duplicate which contains an link back to this issue that we can reference when working on it.

Duplicate of #3029

**Closed by vincode-io** 2021-08-21 20:39 UTC
