### ISSUE TITLE
feature request: manual sort for feeds and folders

### ISSUE THREAD

**Issue by tcuzzillo** [Ranchero-Software/NetNewsWire#925] opened 2019-08-31 20:17 UTC
The only feature I miss -- and I REALLY miss it -- is manual sorting. In NNW 4, that was controlled with View > Arrange Sites.

**Comment by stewf** [comment] 2019-09-02 00:20
Duplicate of #760

**Comment by vincode-io** [comment] 2020-03-18 07:30
Duplicate of #760

**Closed by vincode-io** 2020-03-18 07:30 UTC
