### ISSUE TITLE
NSBlog sort of went away

### ISSUE THREAD

**Issue by mmmayer** [Ranchero-Software/NetNewsWire#1991] opened 2020-04-17 14:07 UTC
NSBlog (https://www.mikeash.com/pyblog/) articles are no longer appear in NNW (Version 5.0.3 (2618)).   
Last night my iMac updated to 10.15.4 and restarted.  This morning all the NSBlog articles are missing.  NSBlog is still subscribed but the articles are not showing.  The NSBlog website is still up and running.   

It might be a NNW problem.  It might be a NSBlog problem.  But it occurred when my Mac updated  to 10.15.4, which makes me think this is a problem with NNW caused by the update.

**Comment by vincode-io** [comment] 2020-04-17 14:19
Are you using the On My Mac account or Feedbin?

**Comment by mmmayer** [comment] 2020-04-17 14:21
On My Mac account

Regards, Michael
===============
Michael M. Mayer
Minneapolis, MN
m.mayer6@me.com

**Comment by vincode-io** [comment] 2020-04-17 14:23
I'm able to add the blog in NNW 5.0.3 to the On My Mac account.  I wonder if the feed URL changed on it.

When you look at the Feed Inspector (using cmd-I) do you see the URL as `http://www.mikeash.com/pyblog/rss.py`?

**Comment by mmmayer** [comment] 2020-04-17 14:30
Yes I do (without the question mark at the end).

Regards, Michael
===============
Michael M. Mayer
Minneapolis, MN
m.mayer6@me.com

**Comment by vincode-io** [comment] 2020-04-17 14:35
I honestly don't know what is happening with this particular feed.  Could you try deleting it and adding it again?  I hate to use the nuclear option, but I'm not sure what is going on.

**Comment by mmmayer** [comment] 2020-04-17 14:51
I tried that and no change.  It subscribes but the articles don’t show.

Regards, Michael
===============
Michael M. Mayer
Minneapolis, MN
m.mayer6@me.com

**Comment by vincode-io** [comment] 2020-04-17 15:07
I'm sorry that you are having these problems and thanks for hanging in there with me.  

Could you please try something to help us track down the problem? Create a new On My Mac account and try adding the feed to that and let me know what happens?

**Comment by mmmayer** [comment] 2020-04-17 15:41
I created a new On My Mac account and added NSBlog to that and it worked.  The articles show up in that account.

Regards, Michael
===============
Michael M. Mayer
Minneapolis, MN
m.mayer6@me.com

**Comment by brentsimmons** [comment] 2020-04-17 16:58
I know what this is. It’s not a bug, exactly, but we will be changing the behavior in 5.0.4 so that this doesn’t happen.

NetNewsWire has a 90-day article retention policy. (The clock starts when the app sees the article — which is not necessarily the publication date.)

In 5.0.4, we’ll change that policy so that NetNewsWire always shows the contents of the feed. As long as an article is still in the feed, it will still be in NetNewsWire.

(Exception: starred articles stay forever.)

**Comment by brentsimmons** [comment] 2020-04-17 16:59
I’m actually working on this particular change right now. The code will first appear in NetNewsWire 5.0.1 for iOS, and then we’ll do 5.0.4 for Mac.

**Comment by mmmayer** [comment] 2020-04-17 17:30
Brent -

Thank you so much for the response.  I guess the macOS update to 10.15.4 was a bit of a red herring other than it caused the app to quit and restart or maybe just coincided with me setting this up 90 days ago?

Regards, Michael
===============
Michael M. Mayer
Minneapolis, MN
m.mayer6@me.com

**Comment by brentsimmons** [comment] 2020-04-17 17:39
It was the quitting and restarting. The 90-day policy cutoff date is determined at launch time and not updated until the next launch. (Which means 90 days could become 91, 100, 200 — as long as NNW is never quit and restarted.)

**Comment by brentsimmons** [comment] 2020-05-13 00:52
This will be fixed by the retention policy change coming in 5.0.4.

**Closed by brentsimmons** 2020-05-13 00:52 UTC
Labels: macOS
