### ISSUE TITLE
Does NNW have plans to support Tiny Tiny Rss?

### ISSUE THREAD

**Issue by Wym1ng** [Ranchero-Software/NetNewsWire#3762] opened 2022-11-26 03:10 UTC
I wish NetNewsWire would support TTRss because it's a great experience, as opposed to Reeder, which I don't really like on iOS and Mac.

I know there are several identical issues, but I am very sorry I still want to praise and mention the need alone
#3665 #2087 #388 It was first proposed in 2018

**Comment by brentsimmons** [comment] 2022-11-26 19:45
We plan very little at a time — our planning is very short-term. Just because it’s not in our plans doesn’t mean we won’t do it. We just have some other priorities first.

**Comment by vincode-io** [comment] 2022-12-03 02:04
Duplicate of #388.

**Closed by vincode-io** 2022-12-03 02:04 UTC

**Comment by eric-pierce** [comment] 2024-09-24 19:07
Tiny-Tiny RSS is now usable with NetNewsWire. I recently published a plugin for Tiny Tiny RSS that will allow NetNewsWire to interface with it using the FreshRSS API here: https://github.com/eric-pierce/freshapi

I've got to say NNW is a really nice experience, better with TT-RSS as the server. If you give it a shot please provide any feedback or issues you find!
