### ISSUE TITLE
move feeds to different folders using two NNW windows not possible

### ISSUE THREAD

**Issue by Thomas-U** [Ranchero-Software/NetNewsWire#3756] opened 2022-11-22 18:44 UTC
I tried this today but it did not work.

When trying to move a feed the destination folder gets blue and a red line appears where the feed should be sortet in. But when I let go the feed is not moved.

When doing the same within one window the move is finished as it should.

Are these operations between two windows not possible at all or is this a glitch?

**Comment by haikusw** [comment] 2022-11-24 08:25
Hi @Thomas-U  This was previously written up [bug](https://github.com/Ranchero-Software/NetNewsWire/issues/3580) and fixed, but seems to now not work (?!).  I will take a look at this.

If you wanted to share specifics about where you're seeing this (what type of accounts (local, iCloud, etc)) and if what you're dragging from/to (top level, from inside a folder), that might be helpful.

Thanks.

**Comment by Thomas-U** [comment] 2022-11-24 13:49
Yes, this happens within an iCloud-account, no other accounts involved.

**Comment by haikusw** [comment] 2022-11-24 19:05
Ok.  Thanks.  As an outside developer I can't work on iCloud accounts in Xcode, but I'll see what I can figure out reading the code.

**Comment by vincode-io** [comment] 2022-12-03 02:03
Duplicate of #3580.

@Thomas-U this fix hasn't been released yet and will be part of the 6.2 release.

**Closed by vincode-io** 2022-12-03 02:03 UTC

**Comment by haikusw** [comment] 2022-12-03 02:50
Thanks
