### ISSUE TITLE
Youtube videos are not shown at all...

### ISSUE THREAD

**Issue by sorenpeter** [Ranchero-Software/NetNewsWire#2810] opened 2021-02-13 12:24 UTC
It just shows nothing when i add a youtube feed:
![Screenshot 2021-02-13 at 13 23 02](https://user-images.githubusercontent.com/8458421/107849951-d48c0900-6dfe-11eb-9d10-5a9fee556b3b.png)

It gets the names of the shows, but no video..

**Comment by vincode-io** [comment] 2021-02-13 19:15
Duplicate of #2538

**Closed by vincode-io** 2021-02-13 19:15 UTC
