### ISSUE TITLE
Selected item appears white

### ISSUE THREAD

**Issue by gferreroferri** [Ranchero-Software/NetNewsWire#2442] opened 2020-09-21 07:40 UTC
Selected item on the article list appears all white. See screenshot attached @
<img width="640" alt="Captura de pantalla 2020-09-21 a las 10 39 23" src="https://user-images.githubusercontent.com/823394/93742466-d5759180-fbf6-11ea-9740-ea05e032f77c.png">

**Comment by jaanus** [comment] 2020-09-21 07:44
Is this Big Sur? What version? This problem was known in Big Sur, and appears fixed in Big Sur latest beta 7.

**Comment by gferreroferri** [comment] 2020-09-21 07:46
Yes, latest Big Sur public beta

**Comment by StrangeNoises** [comment] 2020-09-21 10:19
Confirmed, exactly this, also on the same version of the public beta. We're still one behind the Developer beta so it looks like this is one that'll go away if you ignore it for a while. 😉

**Closed** 2020-09-21 13:45 UTC
