### ISSUE TITLE
Support for Private Feeds

### ISSUE THREAD

**Issue by mawise** [Ranchero-Software/NetNewsWire#2106] opened 2020-05-23 21:52 UTC
An RSS feed can be private by requiring http basic auth headers in the request.  These credentials can be embedded in a url as follows:
```
https://<username>:<password>@domain.com/rss
```
Right now, it seems like NetNewsWire doesn't respect the embedded credentials--it says "Feed not found" when trying to add a feed with such a URL.  Private feeds allow people to publish private blogs and still allow their friends to use RSS to read their content.

**Comment by brentsimmons** [comment] 2020-05-23 22:43
We don’t want to support adding credentials to the URL, because we store those URLs in plain text, and that’s not secure enough for this purpose.

Closing as duplicate of #502

https://github.com/Ranchero-Software/NetNewsWire/issues/502

**Closed by brentsimmons** 2020-05-23 22:43 UTC

**Comment by mawise** [comment] 2020-05-23 22:57
Thanks!  I didn't see this was a dupe (shame on me for not researching open issues).  It might still be valuable to support providing a URL with embedded credentials, even if they get split up and stored elsewhere.
