### ISSUE TITLE
Add "copy link" to the Share options for feed entries

### ISSUE THREAD

**Issue by spodick** [Ranchero-Software/NetNewsWire#2292] opened 2020-07-21 23:44 UTC
On MacOS the contextual menu "Share" option should include an option to copy the URL so that it can be pasted anywhere else.  The current set of share options requires me to perform extra steps to include a link in an already composed e-mail or a web comment.

**Comment by MaineSoNewOrleans504** [comment] 2020-07-28 06:20
Yes

**Comment by wataguy** [comment] 2020-09-19 22:58
Also, please, a hotkey to copy the URL of the currently viewed article.

**Comment by mzagaja** [comment] 2020-11-08 17:52
I am interested in this as well and think it's a duplicate of #1285.

**Comment by brentsimmons** [comment] 2023-03-06 05:00
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/1285

**Closed by brentsimmons** 2023-03-06 05:00 UTC
