### ISSUE TITLE
”Go back to last viewed article” is missing

### ISSUE THREAD

**Issue by ghoffart** [Ranchero-Software/NetNewsWire#2694] opened 2020-12-31 08:49 UTC
Switching from NN4 to 5 this is the most severe bug: this feature, to hop along the ”thread” of read articles, is missing.

In NN4 I often browsed through articles/items, and after hopping to the next one my brain clicked ”wait, the last one indeed sounded interesting". In NN4, I pressed ⌘[ and hopped back. In NN5 I can’t find that feature.

This worked across origins, so "cursor up" in the item list view is not a replacement.

**Comment by vincode-io** [comment] 2020-12-31 18:57
Duplicate of #44

**Closed by vincode-io** 2020-12-31 18:57 UTC
