### ISSUE TITLE
Random feeds become unread

### ISSUE THREAD

**Issue by sgoodwin** [Ranchero-Software/NetNewsWire#1828] opened 2020-02-27 08:26 UTC
Not sure how this is happening, but at least once per day when I check my feeds on my iPhone, the app thinks a whole feed is unread. It seems to be a different feed each time, but it's pretty consistent that I need to mark a whole feed as unread.

**Comment by vincode-io** [comment] 2020-02-28 20:03
@sgoodwin is this a local account, Feedly, or Feedbin?

**Comment by flowinho** [comment] 2020-02-28 20:06
Confirmed - happening to me as well. It‘s a local account.

**Comment by vincode-io** [comment] 2020-02-28 20:07
@flowinho Would you be so good as to give us the URL of the feed that this happened on?

**Comment by flowinho** [comment] 2020-02-28 20:10
Sure thing. It‘s `https://wptavern.com/feed/json ` 👍

**Comment by flowinho** [comment] 2020-02-28 20:15
My settings are:
- Sort oldest to newest - OFF
- Group by feed - OFF
- Refresh to clear read articles - OFF
- Confirm Mark all as read - ON
- Enable full screen articles - OFF

**Comment by sgoodwin** [comment] 2020-03-02 06:43
Yes, I have no Feedly or Feedbin accounts, these are all local. It's also a different feed each time.

**Comment by vincode-io** [comment] 2020-03-12 23:39
I'm assigning to Brent since I have no idea what is going on here.

**Comment by brentsimmons** [comment] 2020-03-13 05:19
I’ve tracked down reports like this hundreds of times since NetNewsWire Lite 1.0 — and it’s always a bug in the feed. Something changes which causes items to get a new unique ID in the feed, and NetNewsWire (dutifully) thinks they’re new.

That said, it’s always worth checking again, just in case. So please do report feed URLs here when things like this happen.

**Comment by sgoodwin** [comment] 2020-03-18 06:10
Hi! It happened today with http://www.useronboard.com/rss

**Comment by brentsimmons** [comment] 2020-03-18 15:37
My theory is that they’ve made a change to their feed. Is there any chance you’d be willing to put your NNW DQ.sqlite3 database on Dropbox or somewhere I could download it? That would let me see if my theory is correct.

**Comment by sgoodwin** [comment] 2020-03-18 19:53
Sure, here it is: https://www.dropbox.com/s/el2lnmzhbuyo99k/DB.sqlite3?dl=0 (I assume you meant DB.sqlite3 rather than DQ)

**Comment by brentsimmons** [comment] 2020-03-20 05:57
@sgoodwin I assume this database file is from your Mac. Have you been been using NetNewsWire since it was still called Evergreen?

**Comment by brentsimmons** [comment] 2020-03-20 06:06
When this happens, do you have doubles of each article? You may have to turn off the read-items filter to see.

**Comment by sgoodwin** [comment] 2020-03-20 07:17
Yes, I've been using since one of the first betas you made public that was kinda usable.

I don't see doubles I don't think, it appears to just be one of each old article.

**Comment by brentsimmons** [comment] 2020-03-20 21:06
I thought I remembered that you were on one of the first testers. 👍

Two more things:

1. Does this happen only on iPhone and not on your Mac?

2. Could I get a copy of the DB.sqlite3 from your iPhone? I don’t actually know how to do that, but I bet you know how. 😀

**Comment by sgoodwin** [comment] 2020-03-21 11:40
I do have more feeds on my Mac than the iPhone now. Lemme get you an iPhone file.

**Comment by svandragt** [comment] 2020-05-17 07:19
I experience this as well (local option /iPhone) this happened on the official NetNewsWire feed a few weeks ago and also on zeldman’s feed today. Someone posts one new article and the whole feed is seen as unread.

**Comment by sgoodwin** [comment] 2020-05-17 11:27
I never got the iPhone database, but this week many feeds including Brent's feed.

**Comment by svandragt** [comment] 2020-05-22 15:48
I exported my opml feed, deleted the app  downloaded it from the App Store and imported my feeds. No more problems since.

**Comment by elindsey** [comment] 2020-05-26 14:27
Similar story for me - I've been using it since the beta and repeatedly seeing old feeds resurrected (far more than can be accounted for by bad upstream rss changes). Backing up my opml, reinstalling and reimporting has fixed it for me.

**Comment by sgoodwin** [comment] 2020-05-26 15:03
Is it just an issue then with us beta people?

**Comment by brentsimmons** [comment] 2020-12-13 05:22
Closing this since it hasn’t been reported in quite a while. If it comes up again, we can reopen this.

**Closed by brentsimmons** 2020-12-13 05:22 UTC
Labels: iOS
