### ISSUE TITLE
Feature request: user-defined smart folders or smart feeds

### ISSUE THREAD

**Issue by harmeling** [Ranchero-Software/NetNewsWire#2966] opened 2021-04-03 09:40 UTC
Dear authors, great piece of software! Thank you a ton!

If time and priorities permit, user-defined smart folders/feeds would be super useful!  

Here is my use case:  following an RSS feed like http://arxiv.org/rss/cs.LG we get everyday 100 new posts listed, which is impossible to go through by hand.  With smart folders, we could filter by author or keywords.

Stefan

**Comment by vincode-io** [comment] 2021-04-03 13:52
Duplicate of #1887

**Closed by vincode-io** 2021-04-03 13:52 UTC
