### ISSUE TITLE
Feature request: In-app web view

### ISSUE THREAD

**Issue by uncleungie** [Ranchero-Software/NetNewsWire#1953] opened 2020-03-28 05:53 UTC
Can the Mac app include an option to open links in an in-app browser/web view? I often briefly want to check on web content, and it is jarring to repeatedly be pulled out of the app.

The iOS app uses a Safari web view, and it would be nice to have this feature ported to the Mac.

**Comment by vincode-io** [comment] 2020-03-28 06:54
Duplicate of #565

**Closed** 2020-03-28 06:54 UTC
