### ISSUE TITLE
MacOS: Feature request: easy article link share

### ISSUE THREAD

**Issue by LowTech** [Ranchero-Software/NetNewsWire#1809] opened 2020-02-22 17:48 UTC
I often find that I want to share long articles (which tend to be the ones I read most often). The only way to do so on the Mac is to scroll up to the top, right-click on the title, and choose "Copy Link." However, I lose my place by doing so, right at the quote I often want to pull. The Share sheet doesn't include a Link option, but if it could, that would solve my dilemma.

**Comment by vincode-io** [comment] 2020-02-22 18:36
We agree.  This is a duplicate of #1285, so I'm closing it.

**Closed by vincode-io** 2020-02-22 18:36 UTC
