### ISSUE TITLE
Images in Mastodon Toots do not appear in NNW

### ISSUE THREAD

**Issue by mmmayer** [Ranchero-Software/NetNewsWire#3763] opened 2022-11-26 18:01 UTC
I am viewing Mastodon postings in NNW by adding .rss to the link to the Mastodon account.  That part works great and I even created a folder so all the "toots" are gathered together in a single place like my twitter feed was.  However, images linked in the post as well as other links I guess are not being displayed by NNW.  This makes me sad and it feels broken.

**Comment by brentsimmons** [comment] 2022-11-26 18:35
What kind of account are you using? iCloud, Feedbin, On My Mac, or…?

Would you provide the URLs of a couple feeds that have this issue?

Are you seeing this on Mac or iOS (or both)?

**Comment by mmmayer** [comment] 2022-11-26 19:52
I created the feeds in my iCloud account.  It happens on both iOS and Mac.  Some example feeds are:
https://mastodon.social/@twostraws.rss
https://mastodon.social/@neilhimself.rss
https://mastodon.social/@feliciaday.rss

**Comment by stuartbreckenridge** [comment] 2022-11-27 02:26
@brentsimmons Duplicate of #3754

**Closed** 2022-11-27 04:48 UTC

**Comment by 11rchitwood** [comment] 2023-01-12 00:33
> I am viewing Mastodon postings in NNW by adding .rss to the link to the Mastodon account.

I didn't know you could this. It might be worth adding this to the FAQ. Something like "How do I subscribe to a Mastodon account?"
