### ISSUE TITLE
FreshRSS account: "The data couldn’t be read because it isn’t in the correct format."

### ISSUE THREAD

**Issue by necrevistonnezr** [Ranchero-Software/NetNewsWire#2765] opened 2021-01-27 10:38 UTC
Version: Version 6.0d5 (6005) on macOS 11.1

When I try to add a self-hosted FreshRSS Account, I get the following error: `The data couldn’t be read because it isn’t in the correct format.`
I can see that _folders_ from my FreshRSS instance, but not the feeds.

I used as 
* URL: https://[url_of_my_freshrss_instance]/api/greader.php (I tried _https://[url_of_my_freshrss_instance]/api/_ and _https://[url_of_my_freshrss_instance]/api/fever.php_ as well but both gave me a `Network error`)
* username: admin
* Password: API Password I set up in FreshRSS

**Comment by vincode-io** [comment] 2021-01-27 15:21
What version of FressRSS are you using?

**Comment by necrevistonnezr** [comment] 2021-01-28 08:14
1.17.0 (the latest release listed on https://github.com/FreshRSS/FreshRSS/releases)

**Comment by vincode-io** [comment] 2021-01-28 19:12
Do you have "Enable API Access" checked in Authentication?

If you set up a test account for me I will help you debug the problem.  Just send the credentials to mo@vincode.io.

**Comment by necrevistonnezr** [comment] 2021-01-29 05:20
Yes, API is activated (and in use by the Reeder app on iOS). Just sent you credentials - many thanks!

**Comment by gracjankn** [comment] 2021-01-29 13:03
> Version: Version 6.0d5 (6005) on macOS 11.1
> 
> When I try to add a self-hosted FreshRSS Account, I get the following error: `The data couldn’t be read because it isn’t in the correct format.`
> I can see that _folders_ from my FreshRSS instance, but not the feeds.
> 
> I used as
> 
> * URL: https://[url_of_my_freshrss_instance]/api/greader.php (I tried _https://[url_of_my_freshrss_instance]/api/_ and _https://[url_of_my_freshrss_instance]/api/fever.php_ as well but both gave me a `Network error`)
> * username: admin
> * Password: API Password I set up in FreshRSS

I had the same problem. For me the URL that worked was: https://[url_of_my_freshrss_instance]/p/api/greader.php. It's none of the ones you've tried.

I determined what URL would work by searching Keychain Access for FreshRSS. I use FreshRSS with Reeder, so there was an application password saved by it. It had the working URL as part the name.

**Comment by necrevistonnezr** [comment] 2021-01-29 15:59
> I had the same problem. For me the URL that worked was: https://[url_of_my_freshrss_instance]/p/api/greader.php. It's none of the ones you've tried.
> 
> I determined what URL would work by searching Keychain Access for FreshRSS. I use FreshRSS with Reeder, so there was an application password saved by it. It had the working URL as part the name.

I tried your suggestion but it doesn't work either. Also, when I enter `https://[url_of_my_freshrss_instance]/**p/**api/greader.php` in my browser, I get a 404, but using `https://[url_of_my_freshrss_instance]/api/greader.php` I receive an "OK"

**Comment by Boycottangent** [comment] 2021-03-28 13:03
The same problem when using FreshRSS. I can see all my feed and folders but can't refresh. (it just get stuck half way) I am using [RSSHub](https://docs.rsshub.app/en/) for many websites and services that don't provide rss feed. These feeds may have less standard format. (I'm not sure) 

I attach my `opml` file for your debug if necessary.
[FreshRSS_opml.zip](https://github.com/Ranchero-Software/NetNewsWire/files/6217322/FreshRSS_opml.zip)

**Comment by vincode-io** [comment] 2021-03-28 14:14
@Boycottangent Which version of FreshRSS are you on? I just imported your OPML file and didn't have any problems syncing with it on FreshRSS 1.17.1.

**Comment by Boycottangent** [comment] 2021-03-28 14:36
> @Boycottangent Which version of FreshRSS are you on? I just imported your OPML file and didn't have any problems syncing with it on FreshRSS 1.17.1.

1.17.1-dev, I'll upgrade to stable release and see if problem still exists.

**Comment by vincode-io** [comment] 2021-03-28 14:37
That version should be fine. Are your RSSHub feeds included in your OPML file?

**Comment by vincode-io** [comment] 2021-03-28 14:38
But do upgrade to a stable version to see if it helps.

**Comment by Boycottangent** [comment] 2021-03-28 14:56
I upgrade to version 1.18.0 and now everything works well. That OPML file has all my feeds including RSSHub feeds so the problem is probably caused by freshRSS itself.
Thank you!

**Comment by vincode-io** [comment] 2021-03-28 15:00
@necrevistonnezr did you ever get your problem resolved?

**Comment by necrevistonnezr** [comment] 2021-03-29 04:54
I just tried again with my FreshRSS instance updated to 1.18. It's still weird: Now it syncs to **one** of my five categories (= folder) of feeds, i.e. I see one folder and one feed, synced. The rest of the folders and feeds are not visible.

**Comment by vincode-io** [comment] 2021-03-29 06:01
Have you tried deleting and adding the account again?

**Comment by necrevistonnezr** [comment] 2021-03-29 09:26
It's a brand new installation of Netnewswire.

**Comment by necrevistonnezr** [comment] 2021-04-09 14:11
After completely removing, reinstalling NNW and adding the account again, FreshRSS works! Thanks!

**Closed** 2021-04-09 14:11 UTC
