### ISSUE TITLE
Feature request: Add shortcut for to navigate to the previously read item

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2413] opened 2020-09-10 14:55 UTC
I often find myself going through my feeds and get a little ahead of myself and want to go back.  

There should be a shortcut to go back to the last article I read.  Up arrow doesn't quite do it as I may have transitioned from one feed to another and up arrow would only navigate to the previous item in the current feed.

I typically keep my finger on the N key to scan through my feeds, maybe the H key could be a good default (it's usually above the N key).

**Comment by vincode-io** [comment] 2020-09-10 22:06
Duplicate of #44

**Closed by vincode-io** 2020-09-10 22:06 UTC
