### ISSUE TITLE
Sepia theme

### ISSUE THREAD

**Issue by 21241** [Ranchero-Software/NetNewsWire#2690] opened 2020-12-24 14:19 UTC
Hello devs, can you add an option to change the article background to sepia on iOS? Something like \#fbfod9 
Thank you very much :D

**Comment by vincode-io** [comment] 2020-12-24 16:39
Thanks for the suggestion. We plan to handle this with theming.  Duplicate of #19

**Closed by vincode-io** 2020-12-24 16:39 UTC
