### ISSUE TITLE
Visual indicator for broken feeds on local and iCloud accounts

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3313] opened 2021-10-06 02:21 UTC
For the device managed accounts, it would be helpful to have a visual indicator for feeds that fail to refresh to allow the user to take action.

**Comment by vincode-io** [comment] 2021-11-02 10:53
Duplicate of #1107.

**Closed by vincode-io** 2021-11-02 10:53 UTC
