### ISSUE TITLE
Feature Request: magazine view

### ISSUE THREAD

**Issue by socceric** [Ranchero-Software/NetNewsWire#2125] opened 2020-06-01 11:49 UTC
Feedly and other readers give you the option to choose the article list view. For me (and I am sure for other too) the current NNW text only view is a deal breaker and I much prefer the view that Feedly define as "magazine view". Please add this essential feature!
See examples below:

![A66F8BAD-EF25-4C08-9DBC-EE8678FF12E4](https://user-images.githubusercontent.com/1143144/83406193-0b9fc300-a406-11ea-9fe8-79e0a5b666cc.png)
![7A467AF6-BEAF-4B79-B4BF-D2EA47CFD89A](https://user-images.githubusercontent.com/1143144/83406200-0f334a00-a406-11ea-8678-a69b985ed63f.png)
![80C14BCE-8365-4126-8F6F-083D9109D3A8](https://user-images.githubusercontent.com/1143144/83406201-0fcbe080-a406-11ea-828f-e4e2efa2e21c.png)

**Comment by vincode-io** [comment] 2020-06-01 12:00
Duplicate of #1551

**Closed** 2020-06-01 12:00 UTC
