### ISSUE TITLE
Reddit feeds not updating or connecting

### ISSUE THREAD

**Issue by malcsweb** [Ranchero-Software/NetNewsWire#3303] opened 2021-09-24 07:59 UTC
Since September 21, 2021  there have been no updates to my Reddit feeds on iCloud. Twitter feeds on iCloud continue to work as normal but Reddit doesn't update on either MacOS or iOS.

Trying to create a new Reddit feed for Home, Popular or All creates a feed but there is no content for the feed. Trying to create a subreddit feed or recreate existing subreddit feeds that aren't working brings up an error message: Feed not found.

**Comment by vincode-io** [comment] 2021-09-24 12:01
What happens if you remove the Reddit extension and add it again?

**Comment by DavidMunch** [comment] 2021-09-24 19:56
I see the same problem, for both Reddit and Twitter extensions, but only on iOS. macOS version has no problems. Started about a week ago.

Removing the Reddit extension and adding it again, did not help. I should mention that I don't see them at all in my feeds anymore, even when not filtrering for unread feeds.

**Comment by vincode-io** [comment] 2021-09-24 20:05
@DavidMunch Reddit and Twitter don't work or sync with BazQux.

**Comment by DavidMunch** [comment] 2021-09-25 07:37
> @DavidMunch Reddit and Twitter don't work or sync with BazQux.
 I am well aware of that, which is why i specified RSS feeds. My point was this was a problem isolated to extensions.

**Comment by vincode-io** [comment] 2021-09-25 11:46
@DavidMunch I'm confused now. If you are having problems syncing your Reddit and Twitter feeds using your iCloud account, why did you bring up BazQux?

**Comment by DavidMunch** [comment] 2021-09-25 14:28
Because I thought it wise to inform what *is* working, to help narrow down the reason for the problem.

**Comment by DavidMunch** [comment] 2021-11-03 17:52
Deleting the app and reinstalling it from the App store doesn't work either.

**Comment by vincode-io** [comment] 2021-11-03 18:21
@DavidMunch could you create a test Reddit account and try with that? I'm just trying things at this point, but this might help us narrow down where the problem is.

**Comment by DavidMunch** [comment] 2021-11-05 07:07
Certainly! I created an entirely new Reddit account, and added it to the previous two I had, but it also doesn't show up. I also waited 12 hours just be sure to have it populated with new Reddit entries in the feed, but still nothing. Screenshot attached.
![IMG_0106](https://user-images.githubusercontent.com/3511519/140471627-99534842-e8a7-4324-b34f-3f30675d742c.jpeg)

**Comment by vincode-io** [comment] 2021-11-05 14:06
@DavidMunch Your On My Mac account is disabled. You have to enable it and have your Reddit feeds added to it for it to work.

**Comment by DavidMunch** [comment] 2021-11-06 07:26
> @DavidMunch Your On My iPad account is disabled. You have to enable it and have your Reddit feeds added to it for it to work.

Are you sure this is correct? On my Mac, I have the "On My Mac" option disabled, yet the Reddit and Twitter feeds still show up. I tried turning on "On my iPad", and deleting/readding a Reddit account, and nothing changed. 
BUT, I now noticed that they are located under "iCloud" on my Mac, and it turns out I had the "iCloud" option in NNW turned off on the iPad, and after activating it, both Reddit and Twitter feeds show up! :)
How does NNW distinguish between iCloud and On my Mac/iPad when it comes to extensions, as I don't see an option to associate them specifically with either?

And following this, I also now notice there's a reminder for this when you add an extension, but it seems both me, and likely also OP, missed that. Perhaps there should be a popup message when adding an extension and neither On my Mac/iPad or iCloud is turned on, asking if the user wants to turn on either of them? 

Which also begs the next question, I am pretty sure I haven't turned off iCloud in NNW at any point, yet it is off now, so how did that happen? Either I am getting senile, or NNW did it by itself by some point.

**Comment by vincode-io** [comment] 2021-11-06 14:29
> > @DavidMunch Your On My iPad account is disabled. You have to enable it and have your Reddit feeds added to it for it to work.
> 
> Are you sure this is correct? 

I wrote the code for the Reddit and Twitter extensions.

> And following this, I also now notice there's a reminder for this when you add an extension, but it seems both me, and likely also OP, missed that. Perhaps there should be a popup message when adding an extension and neither On my Mac/iPad or iCloud is turned on, asking if the user wants to turn on either of them? And how does NNW distinguish between iCloud and On my Mac/iPad when it comes to extensions, as I don't see an option to associate them specifically with either?

A popup message wouldn't have helped you since you disabled the iCloud account after you added the extensions, not before.

When you add a feed that requires an extension to an account, that establishes a relationship between that extension and the account.

It looks like you might still be a little confused about how the Twitter and Reddit feeds work. Please read the help documents again for further clarification. I'm going to close this issue since it looks like you did get them to start working for you.

**Closed by vincode-io** 2021-11-06 14:29 UTC
