### ISSUE TITLE
Make unread articles better visually distinguishable 

### ISSUE THREAD

**Issue by bastilian** [Ranchero-Software/NetNewsWire#1411] opened 2019-12-06 18:04 UTC
At the moment the articles are only distinguishable by the UnreadIndicator to know which ones are read and which are not.

"Graying out" the already read articles in the timeline view would help to better to identify the unread ones.

**Comment by brentsimmons** [comment] 2023-03-06 02:19
Duplicate of #500

**Closed by brentsimmons** 2023-03-06 02:19 UTC
