### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by melwan** [Ranchero-Software/NetNewsWire#2464] opened 2020-09-29 07:55 UTC
Articles written in Right-to-Left languages appear aligned to the left instead of right. This extends to the article title as well as the Reader view.

The annoyance of the issue is not merely an alignment appearance. In the case of Arabic language, when encountering a comma (for example), sentences get broken in half and the two halves get rearranged in reverse order making the article very difficult to read.

Since the SwiftUI transition is pushed back another year, can we see if its possible to tackle this issue?
Implementing RTL awareness should fix both: the appearance and the sentence rearrangement.

This applies to macOS and iOS.

**Comment by Wevah** [comment] 2020-09-30 12:02
Dupe of #2148.

**Closed by Wevah** 2020-09-30 12:02 UTC
