### ISSUE TITLE
Unread status no longer reliably syncing with Feedbin

### ISSUE THREAD

**Issue by michaeljtsai** [Ranchero-Software/NetNewsWire#2975] opened 2021-04-08 19:58 UTC
I'm not sure whether something has changed with Feedbin or in NetNewsWire 6.0.1 (which I recently updated to), but I've started seeing the following issues over the last few days:

- If I mark articles as read in NetNewsWire, they do not get marked as read in the Feedbin Web interface. After a while, they get marked as unread again in NetNewsWire.

- If I mark articles as read in Feedbin, they stay unread in NetNewsWire (even after clicking the Refresh button). They do get marked as read after I quit and relaunch NetNewsWire.

This is happening on macOS 11.2.3. I'm pretty sure it all worked correctly with NetNewsWire 6.0 on macOS 11.2.3. It definitely did with NetNewsWire 6.0 on macOS 10.15.7.

**Comment by vincode-io** [comment] 2021-04-08 20:31
I tried replicating your problem and wasn't able to. I think there might be an issue with your local sync database. We can verify that if are willing to help us out.

Make a copy of your Feedbin account folder. It is located at `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts` and starts with `17_`.

Then using NetNewsWire, remove your Feedbin account and add it back again. Let us know if you are still seeing problems.

If things cleared up, we might have a corruption problem with the sync database. It is the `Sync.sqlite3` file in the Accounts folder we backed up earlier. It doesn't have anything identifying in it. The only identifier it uses is an article identifier that is generated by Feedbin and we have no way of tying it into back to a Feed or Article unless we had your `DB.sqlite3` file. Sending it to Brent or I would help us figure out how this happens. If you don't feel comfortable doing that, maybe you could take a look at it and see if there is anything unusual that could help us?

**Comment by michaeljtsai** [comment] 2021-04-08 23:00
I'm using it with two Macs, but up until the last few days (when the problem began) it was hardly ever open on both Macs at once. Lately, both have had it open almost 24/7. So I'm going to try going back to one Mac for a while, and if that doesn't fix the problem I'll try removing and re-adding the account. Will get back to you in a few days. Thanks!

**Comment by brentsimmons** [comment] 2021-04-08 23:56
Would you try this… find your Feedbin account folder:

~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts/17_*

Command line:

sqlite3 DB.sqlite3

Run this query:

select * from articles where articleID not in (select articleID from statuses);

…and let us know if there are any results. This will let us know if we’re dealing with an instance of #2676. (Which is a bug I haven’t been able to reproduce.)

**Comment by michaeljtsai** [comment] 2021-04-09 01:39
When I posted above, I had just marked everything as read in Feedbin, and this had synced to NetNewsWire, so there were zero unread. I quit NetNewsWire on the other Mac and have not touched it on either Mac since.

Currently, Feedbin shows 173 unread, NetNewsWire shows 155 unread, Feedbin shows 173 unread, and the SQLite query shows 17 articles with no status.

**Comment by vincode-io** [comment] 2021-04-09 01:49
This is definitely #2676. We don't have a fix for this one yet, but are actively working on it.

To improve your quality of life and avoid #2676 do this. Delete your Feedbin account in NetNewsWire and add it again. You'll be back in sync with the Feedbin website.

The only other thing you have to do is shutdown NetNewsWire when you aren't at your computer. #2676 seems to only happen if you have a large number of feeds that are high volume and if you leave it running overnight.

Sorry for the inconvenience, but this one has been a bear to track down.

**Comment by michaeljtsai** [comment] 2021-04-09 01:58
I marked all the posts in NetNewsWire as read, and (with no other devices running NetNewsWire) this quickly synced to Feedbin, and the messages stayed read everywhere. Good.

However, Feedbin now shows 28 posts, some as old as 12 hours, that do not appear at all in NetNewsWire.

I then launched NetNewsWire on my second Mac. It worked as expected: the articles above got automatically marked as read, and seemingly all the articles are showing, even the ones that are absent from the main Mac.

I then marked some new articles as read on the first Mac, and so far these are staying marked as read everywhere.

Thanks for the tip about #2676. Would that explain the missing articles or only the statuses?
 I'm reluctant to shut it down because I'm also using local and and iCloud accounts with some high-volume feeds, and so if NetNewsWire isn't running some articles might fall out of the feed before it sees them.

**Comment by vincode-io** [comment] 2021-04-09 02:02
> Would that explain the missing articles or only the statuses?
We don't show articles if they don't have a status. It is a database join.

You can keep it running if you have to. Just when you notice you have fallen out of sync, delete and recreate your account.

I'm surprised you haven't seen #2676 on your iCloud or Local account yet. You might be suffering from it on those, but haven't noticed yet. I noticed it on my iCloud account first. You can run that same query against your iCloud and Local accounts to know for sure.

**Comment by michaeljtsai** [comment] 2021-04-09 02:10
> We don't show articles if they don't have a status. It is a database join.

Aha. That probably explains the missing articles from Feedbin. But it's not clear to me how I would notice this from the UI for my local accounts.

Running the query, 2 of my 3 local accounts have missing statues. The iCloud account does not, but it is new and lower volume.

Is there a way to add the missing statuses for local accounts? I don't want to lose the statuses that I do have.

**Comment by vincode-io** [comment] 2021-04-09 02:17
You wouldn't have anyway of noticing for your local accounts.

You can try this to get back your local statuses. First, enable the debug menu.

`defaults write com.ranchero.NetNewsWire-Evergreen ShowDebugMenu 1`

Then restart NetNewsWire and select "Drop Conditional Get Info" in the Debug menu. Do a sync. Since these are local accounts, you should get your statuses back. We only retain articles that are still in the feed for local accounts, so in theory, you should get everything back for those accounts.

The restart is necessary because NetNewsWire seems to get itself into a state where it thinks it has article statuses, but they are out of sync with the SQLite database. Restarting clears that up.

**Comment by michaeljtsai** [comment] 2021-04-09 02:38
Removing and re-adding Feedbin brought back those missing articles.

I tried "Drop Conditional Get Info" with the restart as described above, but queries still show that the statuses are missing. I do have some old articles that are probably no longer in the feed, which I think are retained because they are starred. But since it looks like the starred state is also stored in the statuses table, I assume none of those are the ones with missing status.

**Comment by vincode-io** [comment] 2021-04-09 03:00
I just remembered. Drop Conditional Get won't work on anything except debug builds.

I'm not sure what to do about your missing statuses. Now that you've done the restart, those statuses should come back when another article is posted in the feed that you are missing a status from. I'd still like to come up with a solution to more proactively get them back.

...

Now that I think on it some I should be able to craft a query for you that creates those statuses. I need to get some sleep, but I'll try to get it to you early tomorrow.

**Comment by vincode-io** [comment] 2021-04-09 16:00
Here is a query that will generate the SQL you need to fix your local databases.

```sql
select "insert into statuses values ('" || articleID || "', false, false, Date());" 
from articles 
where articleID not in
(select articleID from statuses)
```

**Comment by vincode-io** [comment] 2021-04-09 19:10
@michaeljtsai Are you using the Twitter or Reddit extensions yet? They are starting to look a little suspicious.

**Comment by michaeljtsai** [comment] 2021-04-09 21:27
Thanks, I will try that SQL. I am using the Twitter extension in the Feedbin account that has the problem—only for a low-volume search, though.

**Comment by vincode-io** [comment] 2021-04-09 21:53
The Feedbin/Twitter stuff is fine.

Until we get this bug fixed, I recommend you restart NetNewsWire a couple times a day. You don't have to leave it shut off, just let it clear any old network connections that might be taking up file descriptors.

**Comment by michaeljtsai** [comment] 2021-04-09 23:57
Thanks. Yeah, I had forgotten that moving it to Feedbin would make it stop using the Twitter extension.

**Comment by michaeljtsai** [comment] 2021-04-10 01:14
Fixing the local databases went well, although I had to modify the SQL a bit for one of them because its `statuses` table had an extra `userDeleted` column.

**Comment by vincode-io** [comment] 2021-09-14 21:22
@michaeljtsai This looks like it was a bug in Big Sur. I've been testing on Monterey and had no problems letting NetNewsWire run for extended periods of time and a large number of feeds.

**Comment by michaeljtsai** [comment] 2021-09-14 23:16
@vincode-io Thanks. Will let you know if I still see it on Monterey.

**Comment by vincode-io** [comment] 2021-09-18 18:34
@michaeljtsai I'm going to close this one. If you do see it on Monterey, we'll reopen.

**Closed by vincode-io** 2021-09-18 18:34 UTC
