### ISSUE TITLE
✨ Feature Request: Embed Youtube videos

### ISSUE THREAD

**Issue by fannar** [Ranchero-Software/NetNewsWire#2836] opened 2021-02-25 19:58 UTC
Embed YT videos into reader. Using RSS feed from Youtube only shows title of video and link to it. Would be nice if the video itself would be embedded in the article.

**Comment by vincode-io** [comment] 2021-02-25 21:18
Duplicate of #2538.

**Closed by vincode-io** 2021-02-25 21:18 UTC
