### ISSUE TITLE
Feature Request: Count of notifications for new articles on app badge

### ISSUE THREAD

**Issue by codemonkey85** [Ranchero-Software/NetNewsWire#1861] opened 2020-03-09 18:50 UTC
NetNewsWire has a feature to send push notifications when new articles appear in selected feeds. I'd like to see the number of articles I've been notified about on the app badge. Right now, the app badge notification count shows the total number of unread articles - so a toggle or options form could be appropriate for choosing what to show on the badge.

**Comment by codemonkey85** [comment] 2020-03-09 18:54
Here is a screenshot of the app badge I am referring to:
![E5FF8D00-60D5-4725-B85C-0A2834AC63BC](https://user-images.githubusercontent.com/1414036/76247339-c3fa0880-6215-11ea-8abe-0d424d2bd96c.jpeg)

Here is a screenshot of the number of unread articles being shown on the badge currently:
![12F09CFC-C197-4595-9C0A-8ABD02E52D04](https://user-images.githubusercontent.com/1414036/76247340-c3fa0880-6215-11ea-9421-5ac9b497ce7d.jpeg)

**Comment by codemonkey85** [comment] 2020-03-09 19:04
![B40D2516-195D-4A78-ACA7-06A41B9D63F5](https://user-images.githubusercontent.com/1414036/76248238-5222be80-6217-11ea-98ab-a80e8446d2b8.jpeg)

![99D5FD21-FA76-4B26-BFD4-A5CFE212E8A4](https://user-images.githubusercontent.com/1414036/76248240-5222be80-6217-11ea-8180-48b81f425cac.jpeg)

**Comment by brentsimmons** [comment] 2023-03-06 03:13
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/1962

**Closed by brentsimmons** 2023-03-06 03:13 UTC
