### ISSUE TITLE
Article content is in wrong position after window resize due to monitor configuration change

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2823] opened 2021-02-23 05:26 UTC
When I unplug my external monitor that has the NNW window on it, the window is resized to fit full screen on my MacBook Pro. 

When the window reappears the article content is offset vertically downward incorrectly. (first pic below)  Resizing the window causes the content to appear in the correct position (second pic)

<img width="1280" alt="Screen Shot 2021-02-22 at 9 20 43 PM" src="https://user-images.githubusercontent.com/131679/108805211-6826ad80-7554-11eb-9768-c3102a223ea5.png">

<img width="1277" alt="Screen Shot 2021-02-22 at 9 21 09 PM" src="https://user-images.githubusercontent.com/131679/108805231-783e8d00-7554-11eb-9679-f155c0e9d223.png">

**Comment by stuartbreckenridge** [comment] 2021-02-23 13:23
This is a duplicate of #2597.

I have opened tickets with Apple as there are a few UI issues with the article view (e.g. stutters when resizing vertically, positioning, and lack of drop shadow when scrolling).

**Comment by vincode-io** [comment] 2021-02-23 15:01
Duplicate of #2597.

**Comment by blackketter** [comment] 2021-03-07 21:10
Alas, @vincode-io, l I believe that this was supposed to be fixed in 1.0b1, but I've upgraded and it's still happening in this case (disconnecting external monitor)
<img width="1280" alt="Screen Shot 2021-03-07 at 1 07 25 PM" src="https://user-images.githubusercontent.com/131679/110254962-4959eb00-7f46-11eb-9c79-bfad59c4428d.png">

**Comment by stuartbreckenridge** [comment] 2021-03-07 22:31
I have an idea for this one.

**Comment by blackketter** [comment] 2021-03-27 23:32
Updated to 6.0 final and the screen is still not updated properly.  Reopen?

**Comment by vincode-io** [comment] 2021-03-28 00:10
Reopening, but I don't think we have much of a chance of working around this Big Sur bug.

**Comment by stuartbreckenridge** [comment] 2021-03-28 00:22
I'm at a loss. I can't recreate this anymore. I will keep looking but I'm guessing this'll be a fix we need from Apple.

**Comment by dkocher** [comment] 2021-04-08 18:16
I can confirm this is reproducible in Version 6.0.1 (6030) on 11.2.3 (20D91).

**Comment by stuartbreckenridge** [comment] 2021-04-09 01:02
I will wait till 11.3 is released to the public before testing/working on this again.

**Comment by blackketter** [comment] 2021-04-18 14:19
Just a note, not sure if it is important: Just moving the window will cause it to update properly, you don't have to resize it.

**Comment by blackketter** [comment] 2021-05-05 13:26
I can confirm that this is still an issue under 11.3 and 11.3.1.

**Comment by stuartbreckenridge** [comment] 2021-05-05 14:00
@blackketter This has been fixed by @babbage and will be in a future release.

**Comment by dkocher** [comment] 2021-05-05 14:40
> @blackketter This has been fixed by @babbage and will be in a future release.

It would be great if you reference issues in pull requests and vice versa.

**Closed** 2023-03-06 05:33 UTC
