### ISSUE TITLE
On iOS, opening links with one's default browser

### ISSUE THREAD

**Issue by belcar-s** [Ranchero-Software/NetNewsWire#3660] opened 2022-08-21 22:34 UTC
I would enjoy NetNewsWire much more if it enabled me to quickly open links with my default browser, instead of the app's own browser.

My iPhone has Safari extensions that I'd like to use. Opening a discrete window also facilitates quickly switching between NetNewsWire and the page.

Thanks.

**Comment by vincode-io** [comment] 2022-09-01 22:36
Duplicate of #3029

**Closed by vincode-io** 2022-09-01 22:36 UTC

**Comment by belcar-s** [comment] 2022-09-05 22:06
I can’t find this setting anymore. Was it removed? Why? :(

**Comment by vincode-io** [comment] 2022-09-17 00:20
It is still there in the TestFlight build for iOS.
