### ISSUE TITLE
Feature Request (iOS): setting to adjust the font sizes

### ISSUE THREAD

**Issue by auge8472** [Ranchero-Software/NetNewsWire#2454] opened 2020-09-23 08:20 UTC
At least in the single item view of the iOS app the font sizes are *for me* to large in case of item titles (especially with longer title text) and (a bit) to small for the content text. Thatswhy I want to propose setting points to adjust the font sizes.

**Comment by vincode-io** [comment] 2020-09-23 20:23
Duplicate of #38.

**Closed** 2020-09-23 20:28 UTC

**Comment by auge8472** [comment] 2020-09-24 11:01
Arrgh. Checked the whole 15-pages-list of issues and overlooked this one (#38). Sorry.
