### ISSUE TITLE
Add the ability to enable/disable/filter sources from the Today feed

### ISSUE THREAD

**Issue by DeepFriedPotato** [Ranchero-Software/NetNewsWire#3357] opened 2021-11-23 07:08 UTC
I put my Twitter feed into NetNewsWire, and it's great. Sometimes I wish I could temporarily disable the Twitter feed from the Today feed so I can get through the other articles first.

**Comment by brentsimmons** [comment] 2023-03-09 05:32
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/2388

**Closed by brentsimmons** 2023-03-09 05:32 UTC
