### ISSUE TITLE
Feature request: Go back and Go forward

### ISSUE THREAD

**Issue by rsalmei** [Ranchero-Software/NetNewsWire#3260] opened 2021-08-19 09:07 UTC
Hey, please, would it be possible to implement Go back and forward like in a browser?
Every time I change feeds I loose several seconds searching for the one feed and post I was reading before...
That would be super useful!! To be able to change at will and than just "Go back" and be whatever I was before (including the scroll position if possible).
Then, another "Go forward" would bring me to that latest one again, exactly like in a browser.
The cherry on the top would be the shortcuts ⌘+◀️ and ⌘+▶️.

Thank you.

**Comment by vincode-io** [comment] 2021-08-19 20:06
Duplicate of #44

**Closed by vincode-io** 2021-08-19 20:06 UTC

**Comment by rsalmei** [comment] 2021-08-19 20:18
Wow, and I did search for a similar issue. I just didn't turn so many pages to get way back to 4 years ago.
