### ISSUE TITLE
[feature request] adjustable shortcuts

### ISSUE THREAD

**Issue by ttruckle** [Ranchero-Software/NetNewsWire#3609] opened 2022-06-23 06:24 UTC
Hi, I am using NNW for years now – for a long time on older machines – and got used to the shortcuts of older versions. I have to admit the new ones are reasonable too, but is there a possibility to add an extension to the preferences to edit the shortcuts used in the app?
Cheers tt.

**Comment by vincode-io** [comment] 2022-07-25 23:26
Duplicate of #508

**Closed by vincode-io** 2022-07-25 23:26 UTC
