### ISSUE TITLE
Feature Request: Choose Article Typeface

### ISSUE THREAD

**Issue by ardenott** [Ranchero-Software/NetNewsWire#2006] opened 2020-04-22 05:26 UTC
This is specifically for the iOS version. 

I’m sure it’s been worked on, but I wasn’t able to find any word on it. Would it be possible to allow for changing of the Typeface in the article view? Reading with a serif font is just far more comfortable. 

Thank you!

**Comment by vincode-io** [comment] 2020-04-22 09:07
Yep, that is on our roadmap.  Duplicate of #19.

**Closed by vincode-io** 2020-04-22 09:07 UTC
