### ISSUE TITLE
Space bar not scrolling articles

### ISSUE THREAD

**Issue by matthewloewen** [Ranchero-Software/NetNewsWire#3941] opened 2023-04-13 01:02 UTC
Using NNW 6.1.2 on macOS 13.3.1, the space bar is not scrolling articles.

Other functions that the space bar performs *do* work correctly. To wit:

* after selecting a feed in the sidebar, pressing space bar selects the first unread item
* if an article fits within the window and thus does not require scrolling, pressing space bar moves to the next unread item
* if I *manually* scroll an article that does not fit in the window to the end and then press the space bar, NNW moves to the next unread item

I feel like I noticed this bug as of macOS 13.3, but I've been doing most of my reading on the iPhone recently and so wasn't able to really test it.

**Comment by Alfred-von-Campe-Bose** [comment] 2023-04-13 17:23
The space bar doesn't work at all for me in version 6.1.2 - no scrolling, no advancing to next unread, nothing!

**Comment by stuartbreckenridge** [comment] 2023-04-13 23:16
Space bar scrolling is fixed in the latest macOS 13.4 betas.

**Comment by Alfred-von-Campe-Bose** [comment] 2023-04-27 17:25
I partially take back my previous comment.  The space bar does work as expected if as described in the above comment if the article is scrolled to the end (either because it's very short or you manually scroll to the end of it).  I find it interesting that this is caused by macOS itself, as the space bar works in other applications to either scroll or advance to the next item.

**Comment by brentsimmons** [comment] 2023-04-27 17:50
The macOS bug in this issue is most likely limited specifically to Apple’s WKWebView class, which displays HTML content. And it’s not that using the space bar in a web view stopped working, it’s that calling the API that scrolls down a page in a web view stopped working.

The bad news is that Apple broke it, but the good news is that they fixed it for macOS 13.4. (Or, at least, it’s fixed in the betas.)

**Comment by ELBeavers** [comment] 2023-05-25 13:51
I just realized the spacebar is working for me again. Looks like Apple fixed this bug with the recent OS update. Yay!

**Closed** 2023-05-25 15:22 UTC
