### ISSUE TITLE
Feedly not syncing 

### ISSUE THREAD

**Issue by FM-500** [Ranchero-Software/NetNewsWire#1966] opened 2020-04-05 11:44 UTC
Feedly Feeds do not get updated.
Status Says „updated 2 min ago“ but no articles come in.
Doing a Manual refresh provokes a „not allowed“ error.
![CC3B6DC4-9E40-4C78-96DD-A2FDBF293369](https://user-images.githubusercontent.com/40071240/78473780-89678b00-7743-11ea-99a5-30b201b9afae.png)

**Comment by kielgillard** [comment] 2020-04-05 12:09
What happens if you kill NetNewsWire and relaunch it?

**Comment by FM-500** [comment] 2020-04-06 06:26
Nothing different, articles still not synced.
Issue with the Feedly API?

**Comment by kielgillard** [comment] 2020-04-07 05:53
Do you have a Mac? If so, can you please follow these instructions?

1. Connect your iOS device to your Mac.
1. If you are prompted to trust your Mac (and if you do trust it!) then please tap "Trust", disconnect your iOS device and re-connect it.
1. On your Mac, open Console.app.
1. Using Console.app, choose the iOS device connected to your Mac in the “Devices” section of the side bar on the left.
1. From the menu bar, click the “Action” menu.
1. Ensure “Include Info Messages” and “Include Debug” messages is checked.
1. In the search bar, type “Feedly”
1. On your connected iOS device, attempt to reproduce the alert.

Messages about the behaviour of the Feedly integration in NNW should be revealed in the Console as you use the Feedly account.

**Comment by kielgillard** [comment] 2020-04-07 05:53
@FM-500 posted the comment above for you. This'd be really helpful if you can do it.

**Comment by voiceguy** [comment] 2020-04-08 16:30
I had this exact issue, but relaunching the app DID fix the problem.

**Comment by FM-500** [comment] 2020-04-09 12:22
> Do you have a Mac? If so, can you please follow these instructions?
> 
> 1. Connect your iOS device to your Mac.
> 2. If you are prompted to trust your Mac (and if you do trust it!) then please tap "Trust", disconnect your iOS device and re-connect it.
> 3. On your Mac, open Console.app.
> 4. Using Console.app, choose the iOS device connected to your Mac in the “Devices” section of the side bar on the left.
> 5. From the menu bar, click the “Action” menu.
> 6. Ensure “Include Info Messages” and “Include Debug” messages is checked.
> 7. In the search bar, type “Feedly”
> 8. On your connected iOS device, attempt to reproduce the alert.
> 
> Messages about the behaviour of the Feedly integration in NNW should be revealed in the Console as you use the Feedly account.

`debug	14:20:04.622590 +0200	NetNewsWire	Refreshing access token.
debug	14:20:04.798063 +0200	trustd	replacing non ev reject score: 0 with non ev score: 10011117 <SecCertificatePathVC certs: <cert(0x103021400) s: *.feedly.com i: RapidSSL RSA CA 2018>, <cert(0x10301ac00) s: RapidSSL RSA CA 2018 i: DigiCert Global Root CA>, <cert(0x100d0ad60) s: DigiCert Global Root CA i: DigiCert Global Root CA> >
debug	14:20:04.798298 +0200	trustd	completed: <SecCertificatePathVC certs: <cert(0x103021400) s: *.feedly.com i: RapidSSL RSA CA 2018>, <cert(0x10301ac00) s: RapidSSL RSA CA 2018 i: DigiCert Global Root CA>, <cert(0x100d0ad60) s: DigiCert Global Root CA i: DigiCert Global Root CA> > details: (
        {
    },
        {
    },
        {
    }
) result: 4
debug	14:20:05.024266 +0200	NetNewsWire	Starting sync 1A51CCF5-1C80-40C1-8336-6617B08B2F83
debug	14:20:05.024423 +0200	NetNewsWire	Sending article statuses...
debug	14:20:05.492841 +0200	NetNewsWire	Done sending article statuses.
debug	14:20:05.493289 +0200	NetNewsWire	Requesting collections.
debug	14:20:05.803468 +0200	NetNewsWire	Received collections: <private>.
debug	14:20:05.803982 +0200	NetNewsWire	Ensured 1 folders for 1 collections.
debug	14:20:05.807965 +0200	NetNewsWire	Processing 33 feeds.
debug	14:20:06.029560 +0200	NetNewsWire	Account.FeedlyIngestStreamArticleIdsOperation failed with error: Error Domain=RSWeb.TransportError Code=0 "Unauthorized".
debug	14:20:06.030166 +0200	NetNewsWire	Sync took 1.490 seconds
debug	14:20:06.031033 +0200	NetNewsWire	Cancelling sync 1A51CCF5-1C80-40C1-8336-6617B08B2F83
debug	14:20:12.925982 +0200	NetNewsWire	Starting sync A7100F43-401E-4C1E-9C5B-F027E20D623F
debug	14:20:12.934489 +0200	NetNewsWire	Sending article statuses...
debug	14:20:13.393941 +0200	NetNewsWire	Done sending article statuses.
debug	14:20:13.394171 +0200	NetNewsWire	Requesting collections.
debug	14:20:13.643623 +0200	NetNewsWire	Received collections: <private>.
debug	14:20:13.644206 +0200	NetNewsWire	Ensured 1 folders for 1 collections.
debug	14:20:13.648575 +0200	NetNewsWire	Processing 33 feeds.
debug	14:20:13.875491 +0200	NetNewsWire	Account.FeedlyIngestStreamArticleIdsOperation failed with error: Error Domain=RSWeb.TransportError Code=0 "Unauthorized".
debug	14:20:13.875729 +0200	NetNewsWire	Sync took 0.956 seconds
debug	14:20:13.914489 +0200	NetNewsWire	Cancelling sync A7100F43-401E-4C1E-9C5B-F027E20D623F
`

**Comment by kielgillard** [comment] 2020-04-11 21:19
Thanks so much for the Console output! Are you using a proxy server or is there something else uncommon about your network?

**Comment by kielgillard** [comment] 2020-04-11 21:20
What’s interesting about this is that other requests seem to be working except for the ingest statuses operation.

**Comment by kielgillard** [comment] 2020-04-11 21:22
@FM-500 do see feeds and folders in NNW from Feedly? The log above indicates you should.

**Comment by FM-500** [comment] 2020-04-11 21:24
No proxy or any special setups like firewall etc.
Just plain and simple router.
Actually, right now it IS syncing again.
I have deleted and re-added Feedly multiple times.
But the error still seems odd to me.
BTW: I’ve been able to get it working before, only to have the error come back a few days later.


Michael Freyler
07644 9234478 | michael@freyler.eu
Wagenstadter Weg 5 | 79341 Kenzingen
Am 11. Apr. 2020, 23:21 +0200 schrieb Kiel Gillard <notifications@github.com>:

**Comment by FM-500** [comment] 2020-04-11 21:25
Yep I do.

Michael Freyler
07644 9234478 | michael@freyler.eu
Wagenstadter Weg 5 | 79341 Kenzingen
Am 11. Apr. 2020, 23:22 +0200 schrieb Kiel Gillard <notifications@github.com>:

**Comment by brentsimmons** [comment] 2020-04-11 23:13
For the next time the error happens — does temporarily switching from wi-fi to a cell network fix the problem?

**Comment by voiceguy** [comment] 2020-04-11 23:14
I will keep that in mind. But restarting the app worked great for me this time. (It has happened twice, but not again since then.)

Eric

Eric Armstrong
Assoc. Professor 
Dept. of Theatre
School of the Arts, Media, Performance and Design
York University
Toronto Canada.

email: e.r.armstrong@gmail.com
http://www.voiceguy.ca

**Comment by FM-500** [comment] 2020-04-12 05:55
Didn’t help either. I tried that before zu rule out WiFi problems.

Michael Freyler
07644 9234478 | michael@freyler.eu
Wagenstadter Weg 5 | 79341 Kenzingen
Am 12. Apr. 2020, 01:13 +0200 schrieb Brent Simmons <notifications@github.com>:

**Comment by kielgillard** [comment] 2020-05-20 01:34
The changes in https://github.com/Ranchero-Software/NetNewsWire/pull/2091 may be relevant to this issue. I expect these changes to land in NNW for iOS version 5.0.2.

I'm still at a loss as to how to reproduce this.

**Comment by FM-500** [comment] 2020-05-20 05:49
> The changes in #2091 may be relevant to this issue. I expect these changes to land in NNW for iOS version 5.0.2.
> 
> I'm still at a loss as to how to reproduce this.

Well, I must say, that the issue never appeared again after my last comment!
Maybe temporary issue either the Feedly API?

**Comment by kielgillard** [comment] 2020-05-20 10:41
Strange but pleased to hear it! In that case, if it’s not an issue for you any more, do you mind if we close it?

**Comment by FM-500** [comment] 2020-05-20 13:44
> Strange but pleased to hear it! In that case, if it’s not an issue for you any more, do you mind if we close it?

Right, no need to keep it open!

**Closed** 2020-05-20 13:44 UTC

**Comment by kielgillard** [comment] 2020-05-20 22:08
Thanks! Feel free to open it if the issue reoccurs.
