### ISSUE TITLE
Feed list outline view sometimes displays incorrect disclosure state

### ISSUE THREAD

**Issue by jaanus** [Ranchero-Software/NetNewsWire#3257] opened 2021-08-17 07:54 UTC
Summary: when you quickly interact with feeds and the outline view on iPhone, you may end up in a situation where a group shows "closed" state but is actually open, or vice versa.

How to reproduce: not a surefire pattern, but happens to me a lot in regular use. Open one feed, go back to the feeds list, and tap on various groups to open and close them. Eventually you will end up in a situation where the group disclosure triangle shows "closed" state but the group is actually open, or vice versa.

After you tap on the disclosure triangle a few more times, eventually it is correct, but the intermediate wrong display of state bothers me.

Attached is a video where I managed to reproduce this after a few tries.

https://user-images.githubusercontent.com/184253/129686466-adf48b78-fca3-4573-acab-fda2ed4a4906.mov

**Comment by vincode-io** [comment] 2021-08-24 20:23
Duplicate of #3040.

**Closed by vincode-io** 2021-08-24 20:23 UTC
