### ISSUE TITLE
„Add To Reading List“ keyboard Shortcut or Menu Item

### ISSUE THREAD

**Issue by dirk68-fu** [Ranchero-Software/NetNewsWire#1140] opened 2019-10-17 06:52 UTC
When I browse through the unread articles I would really like to have a way to add articles to the Safari reading list buy pressing a shortcut on the keyboard.

Unfortunately adding this shortcut myself using Preferences.app / Keyboard / Shortcuts does not work, because the „Add to Reading List“ function is hidden behind the share button and context menu. Both does not seems to fire if I use an custom defined shortcut.

Please make this function accessible via a shortcut or offer a standard menu item so is possible to define a shortcut.

**Comment by inkytonik** [comment] 2021-01-04 04:40
I second this. I would use it to share easily to GoodLinks.

The best solution to me seems to be to add a File -> Share menu that is equivalent to the popup share menu. If that menu exists it is possible to directly access particular share actions via a user shortcut. This approach works well in Safari which does have a File -> Share menu.

It's possible to add a shortcut to items in the popup share menu right now, but to use the shortcut you have to open the share menu first. If you invoke the shortcut without that menu open, nothing happens.

**Comment by brentsimmons** [comment] 2023-03-06 03:30
Duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/2070

**Closed by brentsimmons** 2023-03-06 03:30 UTC
Labels: feature request
