### ISSUE TITLE
Feature Request: Nested Folders

### ISSUE THREAD

**Issue by albertsen** [Ranchero-Software/NetNewsWire#1370] opened 2019-11-28 08:59 UTC
It would be nice to be able create folders within folders. For example, I have a folder "Blogs" that I would like to further organize into "Books", "Tech", and "Personal" folders. I'm using FeedBin, in case that makes a difference.

**Comment by justdave** [comment] 2020-01-05 07:53
probably a duplicate of #503

**Closed** 2020-01-05 20:33 UTC
