### ISSUE TITLE
Add ability to mute feeds

### ISSUE THREAD

**Issue by luhinderberger** [Ranchero-Software/NetNewsWire#3420] opened 2022-01-24 19:32 UTC
Hi guys, I would like to add the ability to mute a feed so it doesn't show up in Smart Feeds.

To add some context: I'm subscribed to some feeds that I need to be in a certain mood to consume, or are thematically scattered all over the place, so I only browse them when I have time to kill.

Since I use NNW mostly through the Smart Feeds, I'd like to introduce a way to mute those feeds so they don't show up in the Smart Feeds and pollute them.
That way I can see all the feeds that are important to me in one place, without having to jump back and forth between them or skip a dozen "secondary" feed items in the Smart Feeds.

The easiest way to achieve this in my opinion, is to simply introduce a new switch in the _WebFeedInspectorViewController_, below 'Notify about new articles'.

If you approve this issue, I will implement this feature.
Please let me know when you have any questions regarding this ticket.

**Comment by vincode-io** [comment] 2022-01-25 01:01
Duplicate of #3401.

**Closed by vincode-io** 2022-01-25 01:01 UTC

**Comment by vincode-io** [comment] 2022-01-25 01:07
@luhinderberger If you are interested in working on this, the first thing to do is read our CONTRIBUTING document and then discuss the feature in our #work Slack.
