### ISSUE TITLE
Click on Release Notes in iOS : 404

### ISSUE THREAD

**Issue by grempe** [Ranchero-Software/NetNewsWire#3195] opened 2021-06-26 02:08 UTC
The release notes link in the latest iOS app release returns a 404

https://github.com/Ranchero-Software/NetNewsWire/releases/tag/ios-6.0

**Comment by doamatto** [comment] 2021-06-26 02:49
Duplicate of #3153.

**Comment by vincode-io** [comment] 2021-06-26 18:13
This has been fixed.

**Closed by vincode-io** 2021-06-26 18:13 UTC
