### ISSUE TITLE
iOS: I am not able to get push notifications outside the app.

### ISSUE THREAD

**Issue by noumanumar95** [Ranchero-Software/NetNewsWire#2025] opened 2020-04-27 16:32 UTC
I do not force close the app and let it run in the background, I also have the background app refresh on but for some reason I do not get push notifications outside the app however when I open the app I do get them when the feed refreshes.

**Comment by vincode-io** [comment] 2020-04-27 21:22
Let's try an experiment to try to narrow down where your problem could be.  Would you do me a favor and subscribe to the following feed and turn notifications for that feed on in the Feed Info sheet?

https://www.flickr.com/services/feeds/photos_public.gne

It is an extremely fast moving feed, so expect a lot of entries to come through.  It will clutter up your notification center with lots of notifications.  You can get rid of those by doing a mark all as read on the feed when they start to pile up.

Hopefully we will see something show up while the app is in the background to help us get a clue as to what is going on.

**Comment by noumanumar95** [comment] 2020-04-28 12:57
I didn’t use the app for about 14 hours and when I opened it right now all the notifications started popping up. There were no push notifications.

![00995C29-2B21-4A18-B90C-9D2C5BBFAE2A](https://user-images.githubusercontent.com/64428736/80489648-9578ee00-8979-11ea-9147-d630ef64cee1.jpeg)

**Comment by vincode-io** [comment] 2020-04-28 16:26
It looks like background refresh isn't working at all for you.  This is a hard one, because iOS only lets you suggest when a background refresh will happen.  It gives no guarantee that it will schedule it at all.

You are sure that you don't force quit by sliding NetNewsWire off the top of the screen from the application switcher?  That is the only way that I have seen that iOS will completely refuse to run background refresh.  Of course, you might have some other situation happening here that we need to get figured out.

**Comment by noumanumar95** [comment] 2020-04-28 18:28
I never force quit any of my apps. Every app is always there in the application switcher.

I have the same issue on both, my iPad and my iPhone. Recently I did get one push notification but it was for an article that was post 3 hours before the notification. This is the first app that I have this kind of issue with. 

I'm not sure if other people are also facing the same issue as I am. I use a feedly account, maybe there is an issue from their side but I am not sure.

**Comment by vincode-io** [comment] 2020-04-28 19:13
It does sound like it works, albeit not reliably enough.  I think what you are experiencing is a combination of things.

The first is that you are getting infrequent background refreshes.  Unfortunately because of how iOS is designed we don't have much control over that.  Lots of commercial apps are able to work around this by having a centralized server that monitors and sends notifications.  We have to rely on the device to schedule us to run and it sometimes just doesn't happen.  Honestly, the only thing I know to do to get background refreshes to run more frequently, is to open the app more often.

The second is Feedly's timeliness.  This is another thing we don't have control over.  It is up to the service to deliver new articles to us.  It depends on how often the service checks the RSS feed and how quickly they want to deliver it to us.  The Feedly free tier has a longer lag in it than the paid tier.  If you are using the free tier, I recommend upgrading to the paid one.  Your other options are to use the local account or Feedbin (also paid).

I want to have the app meet your expectations, but we have some real world limits that prevent us from delivering fast notifications of blog posts.

**Comment by noumanumar95** [comment] 2020-04-29 06:54
Will definitely use it more often from now.

I am using the free version of feedly. To be honest I am not that big on news to be willing to pay 72$ per year. The local account was what I was hoping to use in the first place but the lack of iCloud sync was a bummer.

I did experiment with the local account and it is a bit better but there is still a lag.

The app is no doubt amazing and a breeze to use.

**Comment by vincode-io** [comment] 2020-04-29 09:12
We hear you and are working on iCloud sync right now.

**Comment by stuartbreckenridge** [comment] 2020-05-03 14:08
It could also be that Background App Refresh is disabled in Settings?

![IMG_2827](https://user-images.githubusercontent.com/7046652/80916301-68b64380-8d8a-11ea-9796-2e86036eedef.PNG)

**Comment by noumanumar95** [comment] 2020-05-03 18:20
It’s on since day one.
![E12CB459-8B6B-4EBA-A2F7-FE45FF55D924](https://user-images.githubusercontent.com/64428736/80922176-ad46dc80-8d94-11ea-97bd-9bed1ef8f066.png)

**Comment by alexcfaber** [comment] 2020-05-04 10:54
Two more things to try: 

Do you have background app refresh enabled for cellular data? (I noticed you were on 4G in both screenshots).

Settings -> General --> Background App Refresh ---> Background App Refresh:

![IMG_DDD6BE7ACD37-1](https://user-images.githubusercontent.com/1764290/80958950-229ec580-8e06-11ea-8021-3bb749ab4c09.jpeg)

And do you have 'Low data mode disabled'?

Settings -> Mobile Data --> Mobile Data Options ---> 'Low data mode':

![IMG_5CE2075246C9-1](https://user-images.githubusercontent.com/1764290/80959043-4d891980-8e06-11ea-93a6-222f12bdd6b5.jpeg)

**Comment by nickgovier** [comment] 2020-05-12 23:07
I have exactly the same issue - I have never received a push notification from the app when it is not active on screen. I never receive notifications when it is in the background, but get a flurry of notifications when I switch back to the app after a period of inactivity.

**Comment by vincode-io** [comment] 2020-05-13 01:08
There are different kinds of notifications that apps use.  Local and server notifications.  If your other apps have server notifications, as most do, then they won't have any problems.  They aren't reliant on iOS scheduling them to run.  We are.  Quite frequently iOS prioritizes battery life over doing background refreshes, making background refreshes unpredictable.

**Comment by nickgovier** [comment] 2020-05-13 08:27
Thanks vincode-io for confirming. This is not an issue of the iOS scheduler being "unpredictable". It is perfectly predictable in that I have _never_ received a local notification from this app unless it is open on screen. My iOS settings reflect the above, so there is another issue here that is affecting both me and the OP, possibly other users as well.

More generally, the app probably should not be relying on a notification mechanism that is at best "unpredictable", hence why most apps use server push in the first place.

**Comment by stuartbreckenridge** [comment] 2020-05-13 11:12
Out of interest, is your app still being badged with unread counts when running in the background?

**Comment by vincode-io** [comment] 2020-05-13 14:23
@stuartbreckenridge I'm not sure that we are hitting any upper limits on notifications if we aren't getting any notifications at all for these users.  What is your idea for monitoring the errors?  Log statements?

**Comment by vincode-io** [comment] 2020-05-13 14:27
@nickgovier 

> More generally, the app probably should not be relying on a notification mechanism that is at best "unpredictable", hence why most apps use server push in the first place.

Those apps are paying for their server resources by selling tracking and usage information about you to marketing companies.  That is antithetical to what we are trying to do for NetNewsWire and why we don't currently maintain server resources or other kinds of financial overhead.

**Comment by stuartbreckenridge** [comment] 2020-05-13 14:40
@vincode-io I’m not sure we are either, but it’d be interesting to see if notifications are throwing errors at the point of being added. I’m not sure how those errors could be monitored from live installs, however.

**Comment by vincode-io** [comment] 2020-05-13 14:46
I'm pretty sure the problem isn't with notifications.  The users are getting the notifications when they launch NNW and it does its on launch sync.  The problem is that background syncing isn't happening for them.

**Comment by stuartbreckenridge** [comment] 2020-05-13 14:53
> I'm pretty sure the problem isn't with notifications.  The users are getting the notifications when they launch NNW and it does its on launch sync.  The problem is that background syncing isn't happening for them.

Unless the app is still badging...which would complicate things.

**Comment by vincode-io** [comment] 2020-05-13 14:54
Are you suggesting that notifications are only working when in the foreground and not when in the background?

**Comment by nickgovier** [comment] 2020-05-13 16:32
> > I'm pretty sure the problem isn't with notifications.  The users are getting the notifications when they launch NNW and it does its on launch sync.  The problem is that background syncing isn't happening for them.
> 
> Unless the app is still badging...which would complicate things.

I do not get badges until I open the app.

**Comment by stuartbreckenridge** [comment] 2020-05-14 01:18
> Are you suggesting that notifications are only working when in the foreground and not when in the background?

Not anymore. 🤔 I’ve been able to recreate this behaviour by letting my battery drain to less than < 15%, then when opening the app the background task runs and a ton of notifications appear. 

I’ll keep looking into it.

**Comment by stuartbreckenridge** [comment] 2020-05-15 13:10
_Two days later_

I've tested the current release on: 

- iPhone 7 (iOS 13.4.1 (after an _Erase All Contents and Settings_ and fresh install of iOS)
- iPhone 11 Pro (iOS 13.5)
- iPad Pro (iOS 13.5)

The feeds I used were from [http://lorem-rss.herokuapp.com](http://lorem-rss.herokuapp.com).

Over the course of 60 minutes, the iPhone 11 updated twice, the iPad updated thrice, and the iPhone 7 didn't update **at all**.  Over the course of three hours, the iPhone 7 didn't update at all. 

As a test, I rewrote the background refresh code to use `Operation` and override `main()`, and I got the same result—the iPhone 7 didn't update once overnight despite being on WiFi & charger. 

I'm stumped.

**Comment by stuartbreckenridge** [comment] 2020-05-17 07:56
@vincode-io I agree with you, we have no control over this. Background refresh did nothing overnight (while on the charger) but has roared into action from 11:30 onwards...


[screenrecording.zip](https://github.com/Ranchero-Software/NetNewsWire/files/4639836/screenrecording.zip)

**Comment by vincode-io** [comment] 2020-05-17 14:23
@stuartbreckenridge Thanks for doing such a thorough analysis on this.

The bottom line is that our local notifications are working, but background refresh is indeterminate due to how iOS's machine learning schedules it.

I'm closing this issue since there isn't anything more we can do with it.

**Closed by vincode-io** 2020-05-17 14:23 UTC

**Comment by nickgovier** [comment] 2020-05-17 18:20
Thanks very much for investigating.
As a workaround feature request, is there any way you can expose a refresh action to the Shortcuts app so users can force a refresh on a schedule? Currently I have created a Shortcut to open the app a few times per day and cause the notifications to fire, but it still requires user intervention.

**Comment by vincode-io** [comment] 2020-05-18 07:21
From a technical perspective, that is really hard to do without causing crashes.  Since shortcuts don't really launch the main app, you have to include all the main app functionality in the shortcut extension.  This means sharing the main database between multiple running processes.  We've spent a lot of time and effort trying to make that work in the past and backed off the issue.  If we ever come up with a resolution, we'll consider adding refresh as a shortcut.

**Comment by jby** [comment] 2020-12-06 18:23
Did anyone ever find a solution to this?
I'm having the exact same problem now on NNW 5.0.5, iOS 14.2.1 on an iPhone 12 Pro.

**Comment by vincode-io** [comment] 2020-12-06 18:35
@jby Did you see my comment above?

> It does sound like it works, albeit not reliably enough. I think what you are experiencing is a combination of things.
> 
> The first is that you are getting infrequent background refreshes. Unfortunately because of how iOS is designed we don't have much control over that. Lots of commercial apps are able to work around this by having a centralized server that monitors and sends notifications. We have to rely on the device to schedule us to run and it sometimes just doesn't happen. Honestly, the only thing I know to do to get background refreshes to run more frequently, is to open the app more often.
> 

...

> I want to have the app meet your expectations, but we have some real world limits that prevent us from delivering fast notifications of blog posts.

**Comment by stuartbreckenridge** [comment] 2020-12-08 15:40
@jby To provide more context to Maurice's point: our implementation of requesting refreshed subscription data is to do so every 15 minutes, using Apple's `BackgroundTasks` framework. However, that request is basically a "pretty please", over which iOS has ultimate control. The more often the _user_ opens the app, the more likely it is that the request for a 15-minute background refresh will be granted by iOS.

**Comment by ilearnio** [comment] 2023-04-05 11:16
It doesn't show notifications for me on my mac, neither on my iphone. I have enabled the notifications for it in system preferences though. In the app itself I don't see anything in settings related to notifications

**Comment by stuartbreckenridge** [comment] 2023-04-05 11:56
@ilearnio You have to enable notifications in each feed’s “Get Info”.

**Comment by ilearnio** [comment] 2023-04-05 12:56
@stuartbreckenridge oh, you're right. It worked. Thank you so much!!!
