### ISSUE TITLE
[mac] [feature request] Skip folders when navigating to next unread

### ISSUE THREAD

**Issue by ednl** [Ranchero-Software/NetNewsWire#3093] opened 2021-04-28 09:52 UTC
The old NetNewsWire 3 would skip folders when jumping to the next unread message (e.g. with the keyboard shortcuts ```n``` or ```l```). I would very much like to have that behaviour back in the new versions. I prefer to view feeds one at a time, never lumped together, *but* I also prefer to organise them in folders by theme. That combination worked fine in NNW3 but not now.

An extra option like this in Preferences would be perfect for me:
```
[x] Skip folders when navigating to the next unread message
```

**Comment by ednl** [comment] 2021-04-28 10:05
This could be a duplicate of #567 but perhaps the different (and shorter) wording will make the issue clearer.

**Comment by brentsimmons** [comment] 2023-03-06 16:55
Duplicate of #567

**Closed by brentsimmons** 2023-03-06 16:55 UTC
