### ISSUE TITLE
The operation couldn’t be completed. (OAuthSwiftError error -2.)

### ISSUE THREAD

**Issue by anthonyvardizzone** [Ranchero-Software/NetNewsWire#3256] opened 2021-08-17 01:30 UTC
I noticed a while ago I started getting the above error on macOS when manually refreshing my feed.

Through discussion in the #general Slack channel, it was determined that this error is caused due to a `tokenExpired` status for an enabled Twitter extension (not sure if it would also apply to the Reddit extension as well since I did not have that extension enabled).

A simple fix that was suggested to me was to deactivate the extension and then reactivate. I can confirm this worked. I also revoked NetNewsWire from accessing my Twitter account and re-enabled it, but they may not have been necessary. Based on the language on the Twitter page, NetNewsWire's access had not be previously revoked.

Was told to open an issue so it could be kept track of.

**Comment by danielpunkass** [comment] 2021-08-17 01:34
For the scenario where this panel is displayed can be reproduced by explicitly revoking the authentication for a Twitter connection from the Twitter apps page:

https://twitter.com/settings/connected_apps

It sounds like the scenario @anthonyvardizzone was slightly different but handling the -2 error when it comes up will probably work around that issue at least. I suspect when the tokenExpired -2 error is encountered, NNW should just put the user through the process of re-authorizing the app with Twitter.

**Comment by brentsimmons** [comment] 2023-03-05 23:12
Since Twitter integration will stop working soon — as soon as Twitter ends free Twitter API access — I’m closing this.

**Closed by brentsimmons** 2023-03-05 23:12 UTC
