### ISSUE TITLE
Can't Add Feedly Account on Big Sur

### ISSUE THREAD

**Issue by MRyanNYC** [Ranchero-Software/NetNewsWire#2480] opened 2020-10-05 15:49 UTC
Running macOS Big Sur 11.0 Public Beta (20A5384c)
Running NetNewsWire Version 5.1.1a2 (3011)

1 - Open "Preferences", then "Accounts".
2 - Click "Feedly" to add Feedly account.
3 - "Waiting For Access To Feedly" dialog appears in NNW.
4 - "NetNewsWire wants to use Feedly.com to sign in." dialog appears w/Safari logo.
5 - Click continue on the Safari dialog, but then nothing happens.

Preferences remain open, but Feedly account not added because Safari never opens the Feedly login page.

I switched my default browser to Microsoft Edge for Mac (in both NNW and System Preferences) but step 4 always shows the Safari logo in the dialog box.  Default browser is not being honored during this request, but is honored for options under the NNW "Help" menu.  ("Website", "Bug Tracker", etc).  So I'm guessing it's Big Sur interfering.

Is there a macOS workaround?  Or does this require an NNW change?

**Comment by JayMcW** [comment] 2020-10-06 01:27
I'm having this same issue. Did a clean re-install and had the same thing happen again.

**Comment by kielgillard** [comment] 2020-10-06 07:54
@JayMcW are you on Big Sur and using a browser other than Safari?

**Comment by oblcc** [comment] 2020-10-06 09:07
I have the same problem, but did not switch browsers, so also with Safari it doesn't work.

**Comment by kielgillard** [comment] 2020-10-06 09:36
> I have the same problem, but did not switch browsers, so also with Safari it doesn't work.

Is this on big sur, too?

**Comment by oblcc** [comment] 2020-10-06 09:41
Yes, latest Big Sur beta

Edwin van Nuil
Managing Director
Oblivion Cloud Control b.v.
edwin@oblcc.com
+31 6 41 55 88 47
+31 20 210 37 50
https://oblcc.com
Mr. Treublaan 7 | Amsterdam | The Netherlands
Mr. van Rhemenslaan 3 | Apeldoorn | The Netherlands
AWS Premier Consulting Partner

**Comment by JayMcW** [comment] 2020-10-07 17:56
> @JayMcW are you on Big Sur and using a browser other than Safari?

I'm on Big Sur and am just using Safari

**Comment by ianeiloart** [comment] 2020-10-07 18:07
Me three: 
NetNewsWire Version 5.1.1 (3012)
Big Sur 11.0 Beta (20A5384c)
Safari Version 14.0.1 (16610.2.6.1.6)

Really pleased to be getting Feedly sync though. That's the change I've been waiting for!

**Comment by kstlouis** [comment] 2020-10-07 18:58
I'm using the same config as @ianeiloart; also having the same problem. I double-checked and Safari is the default browser.
Tried the latest Beta release of NNW (5.1.1a2) to see if it would be any different, but no dice.

**Comment by vincode-io** [comment] 2020-10-07 22:25
I can confirm this bug is related to Big Sur (and possibly Safari 14).

For some reason the `ASWebAuthenticationSession` callback is returning an error.

`"The operation couldn’t be completed. (com.apple.AuthenticationServices.WebAuthenticationSession error 1.)"`

This looks to me like it is a [canceledLogin](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsessionerror/code/canceledlogin) error, which doesn't make any sense to me.

@kielgillard If you don't have Big Sur or for some reason don't want to install it, I can dig deeper on this.

**Comment by kielgillard** [comment] 2020-10-07 23:04
@vincode-io I don't have Big Sur installed yet and I'm not sure when I'll be allowed to install it on my Mac by my employer's IT department. Looks like [Apple and other people are aware of the issue](https://developer.apple.com/forums/thread/662983)... maybe all we can do is "vote into the void" and intentionally dupe the radar?

**Comment by vincode-io** [comment] 2020-10-07 23:16
That works for me.  I'll revalidate this issue when the next release of Big Sur comes out.  It is such a heinous bug, that I'm sure Apple will get it resolved ASAP.

**Comment by kielgillard** [comment] 2020-10-08 01:36
FB8783985

**Comment by kielgillard** [comment] 2020-10-14 20:57
@vincode-io beta 10 landed today -- can you please check if this issue is resolved?

**Comment by vincode-io** [comment] 2020-10-16 00:50
This has been resolved as of the latest Big Sur beta.  Please update your OS if you are experiencing this issue.

**Closed by vincode-io** 2020-10-16 00:50 UTC

**Comment by kielgillard** [comment] 2020-10-16 02:03
> This has been resolved as of the latest Big Sur beta. Please update your OS if you are experiencing this issue.

Great news! Wish the release notes indicated it was fixed, too.

**Comment by MRyanNYC** [comment] 2020-10-17 13:12
I can confirm the issue is resolved on the latest Big Sur Public Beta.

Thanks team!
