### ISSUE TITLE
[Feature Request] Darker text for dark mode

### ISSUE THREAD

**Issue by pwnell** [Ranchero-Software/NetNewsWire#3327] opened 2021-10-27 22:15 UTC
This is a small feature request, but it would be a great eye strain relief if it could be possible to change the colour of the font in the reader and everywhere else to not be white (#FFFFFF) but rather a grey (#C9C9C9).  The contrast between pure white and the dark background hurts my eyes when then moving to view a web page that has white background and dark text.

**Comment by Suzie97** [comment] 2021-11-01 14:53
We can also look at Apple Books for the colors. The contrast on apple books is still a bit too high for me but its pretty good and works most of the time, AFAIK,it doesn't use pure white (#FFFFFF) for the text color.

**Comment by vincode-io** [comment] 2021-11-02 10:15
In version 6.1 of NNW you will be able to build custom themes that use any color of text you would like. Duplicate of #19.

**Closed by vincode-io** 2021-11-02 10:15 UTC
