### ISSUE TITLE
macOS: System Preferences sidebar icon size is not used

### ISSUE THREAD

**Issue by blackketter** [Ranchero-Software/NetNewsWire#2756] opened 2021-01-23 20:41 UTC
Adjusting the system preferences sidebar icon size setting does not update in NNW, even after a relaunch. The fixed size appears to be close to "Medium" when compared to a Finder sidebar.

Big Sur running 6.0d5.

As mentioned in #2321.

**Comment by vincode-io** [comment] 2021-01-23 20:54
Duplicate of #2755

**Closed** 2021-01-23 20:54 UTC
