### ISSUE TITLE
Support http proxy

### ISSUE THREAD

**Issue by zhan9san** [Ranchero-Software/NetNewsWire#3457] opened 2022-02-11 05:19 UTC
Hi team,

Thanks for your contribution in this project and it is really useful.

Would it be possible to add a new feature, configuring http proxy in UI on Mac or IOS client?

Some RSS feeds are not reachable directly. It would be convenient to access them via proxy for NetNewsWire instead of OS system proxy.

**Comment by vincode-io** [comment] 2022-02-11 14:21
Duplicate of #478

**Closed by vincode-io** 2022-02-11 14:21 UTC
