### ISSUE TITLE
NetNewsWire missing 'author' tags in feed

### ISSUE THREAD

**Issue by dumprop** [Ranchero-Software/NetNewsWire#2890] opened 2021-03-15 14:55 UTC
**Describe the bug**
Subject

**To Reproduce**
1. Go to freshrss
2. Click on add feed
3. Enter https://feed.eugenemolotov.ru/?action=display&bridge=Twitter&context=By+username&u=durov&format=Atom
4. See the difference

**Expected behavior**
![image](https://user-images.githubusercontent.com/34004367/111068921-95ff7200-84c2-11eb-97c8-94e814e77f87.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/34004367/111068964-c810d400-84c2-11eb-8563-754c2fba7fb5.png)

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18

https://github.com/FreshRSS/FreshRSS/issues/3518

**Comment by vincode-io** [comment] 2021-03-15 16:55
Duplicate of #2797.

**Closed by vincode-io** 2021-03-15 16:55 UTC
