### ISSUE TITLE
Feature Request: Smart Folders with "contains" options from open-source Vienna app

### ISSUE THREAD

**Issue by sherlock440** [Ranchero-Software/NetNewsWire#3121] opened 2021-05-17 21:21 UTC
I check NetNewsWire (pretty much the best client in my opinion) every six months for one feature that I simply can't use it without - a customizable smart folder feature.

The paid app ReadKit and the free Vienna (which is open source) have this option, and it's an indispensable thing for news writers. For example, I can set up a rule so that my RSS client collects all news with the word "iOS 14" in the text in a separate folder and sends me a notification when such news appears.

The lack of this feature keeps me and many others from using NetNewsWire, although the app is great in all things steely (ideally I'd like to be able to use a proxy, but that's out of the realm of fantasy).

I and many other people would be very happy if you implement the Smart Folders option - especially since it can be roughly copied from open source Vienna.

**Comment by vincode-io** [comment] 2021-05-17 23:38
Duplicate of #217

**Closed by vincode-io** 2021-05-17 23:38 UTC
