### ISSUE TITLE
Feature Request: Sync Feed "Always Use Reader View" Setting 

### ISSUE THREAD

**Issue by githublongmanc** [Ranchero-Software/NetNewsWire#3251] opened 2021-08-11 17:36 UTC
If you mark a feed to "Always Use Reader View" on one device chances are pretty good that's how you want to see it on other devices so would love to see this setting be sync'd across devices.  There are probably some instances where this may be undesirable so perhaps the option to turn this sync-ing off at a global or per-feed level would be needed as well.  Thanks!

**Comment by vincode-io** [comment] 2021-08-11 20:38
Duplicate of #2739.

**Closed by vincode-io** 2021-08-11 20:38 UTC
