### ISSUE TITLE
Horizontal panes with abbreviation in articles list

### ISSUE THREAD

**Issue by paulehoffman** [Ranchero-Software/NetNewsWire#2935] opened 2021-03-28 22:30 UTC
In order to show more new articles, I'd like a View option to be in the more traditional (yech) three-pane style of sidebar on the left, then article list above the article view on the right. In the article view, it would be nice to be able to abbreviate what is seen to maybe two lines (or even one). This is akin to unchecking View -> "Use Column Layout" in Mail.app.

**Comment by vincode-io** [comment] 2021-03-28 22:39
Duplicate of #102.

**Closed by vincode-io** 2021-03-28 22:39 UTC
