### ISSUE TITLE
Feature Request: "Always Use Reader Mode" Preference Syncs Across Devices

### ISSUE THREAD

**Issue by armen-y** [Ranchero-Software/NetNewsWire#3689] opened 2022-09-25 22:36 UTC
"Always Use Reader Mode" currently takes effect per-feed, per-device. This makes it a difficult preference to manage, as it is not uncommon for users to read their feeds on multiple devices. 

A given feed's reader mode preference is likely to be desired on multiple devices. Support the ability to synchronize this preference across NetNewsWire instances using the same account.

**Comment by vincode-io** [comment] 2022-09-25 22:50
Duplicate of #2739

**Closed by vincode-io** 2022-09-25 22:50 UTC
