### ISSUE TITLE
Request Feature: Add feature to enable sync between web feed options

### ISSUE THREAD

**Issue by kevinm6** [Ranchero-Software/NetNewsWire#2989] opened 2021-04-12 07:33 UTC
I think could be useful add the feature to enable/disable sync of options for a web feed, at least with iCloud Sync.
I’m speaking about “Show Notifications…” and “Always Use Reader View” that sync between iOS and macOS.

**Comment by vincode-io** [comment] 2021-04-12 16:02
Duplicate of #2739

**Closed by vincode-io** 2021-04-12 16:02 UTC

**Comment by kevinm6** [comment] 2021-04-12 16:40
Sorry, I didn't see it. 
The request is the same one.
