### ISSUE TITLE
Directory within a directory 

### ISSUE THREAD

**Issue by RafBois** [Ranchero-Software/NetNewsWire#3336] opened 2021-11-05 13:51 UTC
Il n'est pas possible de mettre un répertoire dans un répertoire?

**Comment by vincode-io** [comment] 2021-11-05 14:03
I think you are asking about nested folders. It is not possible to put a folder inside another folder. You can create multiple On My Device accounts and use folders under that to further organize your feeds.

Duplicate of #503.

**Closed by vincode-io** 2021-11-05 14:03 UTC

**Comment by RafBois** [comment] 2021-11-05 14:18
Hello, Sorry for the translation.

This is exactly my problem but I use iCloud to have everything on my machines (Macbook and iPhone).

No plans to develop this function in the near future?

**Comment by vincode-io** [comment] 2021-11-05 14:22
I'm sorry, but it most likely won't be implemented anytime soon.

https://inessential.com/2018/09/09/why_netnewswire_doesnt_support_nested_fo

**Comment by RafBois** [comment] 2021-11-05 14:34
When you are not a developer, it seems so simple!

**Comment by RafBois** [comment] 2021-11-05 14:40
Ok I hadn't read the article. Why not but it's the basis of computer science to put a folder in a folder.

Best regards
