### ISSUE TITLE
Display image from RSS feed

### ISSUE THREAD

**Issue by Krinkle** [Ranchero-Software/NetNewsWire#2214] opened 2020-07-06 00:58 UTC
Sorry for the generic title, I do see images in most feeds, so I imagine there is something specific about this feed that makes it odd. However, I do see the image on another reader (Feedly) and confirmed that it is communicated as part of the XML file so I suspect it would be possible to support.

* Site: <https://polyglot.city/@krinkle>
* Feed: <https://polyglot.city/@krinkle.rss>

XML excerpt:
```xml
    <item>
      <title>krinkle: “to thine own self…”</title>
      <guid isPermalink="true">https://polyglot.city/@krinkle/104440224108458470</guid>
      <link>https://polyglot.city/@krinkle/104440224108458470</link>
      <pubDate>Wed, 01 Jul 2020 19:22:29 +0000</pubDate>
      <description>&lt;p&gt;to thine own self&lt;/p&gt;&lt;p&gt;&amp;quot;&amp;quot;&amp;quot;&lt;br /&gt;(proverb) be true to yourself, do not engage in self-deception. &lt;br /&gt;&amp;quot;&amp;quot;&amp;quot;&lt;/p&gt;&lt;p&gt;Word 2:&lt;br /&gt;I noted this from a scene of Elementary (TV series).&lt;/p&gt;&lt;p&gt;&amp;gt; Watson: &amp;quot;No one can accept something like that forever.&amp;quot;&lt;br /&gt;&amp;gt; Holmes: &amp;quot;To thine own self, Watson.&amp;quot;&lt;/p&gt;&lt;p&gt;Its not uncommon for the Holmes character to utter such rich and poetic language. Its one of my favourite series.&lt;/p&gt;&lt;p&gt;&lt;a href="https://en.wiktionary.org/wiki/to_thine_own_self_be_true" rel="nofollow noopener noreferrer" target="_blank"&gt;&lt;span class="invisible"&gt;https://&lt;/span&gt;&lt;span class="ellipsis"&gt;en.wiktionary.org/wiki/to_thin&lt;/span&gt;&lt;span class="invisible"&gt;e_own_self_be_true&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href="https://polyglot.city/tags/english" class="mention hashtag" rel="tag"&gt;#&lt;span&gt;english&lt;/span&gt;&lt;/a&gt; &lt;a href="https://polyglot.city/tags/word" class="mention hashtag" rel="tag"&gt;#&lt;span&gt;word&lt;/span&gt;&lt;/a&gt; &lt;a href="https://polyglot.city/tags/linguistics" class="mention hashtag" rel="tag"&gt;#&lt;span&gt;linguistics&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;</description>
      <enclosure url="https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/polyglotcity/media_attachments/files/000/520/985/original/a0c6f91a5fb774ca.png" length="285852" type="image/png"/>
    </item>
```

| Original | Feedly (website) | NewNewsWire (default) | NewNewsWire (Reader View)
|--|--|--|--
| <img width="667" alt="Mastodon site" src="https://user-images.githubusercontent.com/156867/86546171-4d52ea80-bf2b-11ea-93e8-74ae841f3dfc.png"> |  <img width="585" alt="Feedly site" src="https://user-images.githubusercontent.com/156867/86546186-5f348d80-bf2b-11ea-8634-a69a23c4e6cd.png"> | ![NNW default](https://user-images.githubusercontent.com/156867/86546202-825f3d00-bf2b-11ea-819a-4b5d0393848d.PNG)| ![NNW Reader View](https://user-images.githubusercontent.com/156867/86546203-83906a00-bf2b-11ea-9a63-d26edfeee583.PNG)

Note that I don't mind whether it is shown on the top or in lists. From looking at some other issues, I actually appreciate that NetNewsWire doesn't show attention-grabbing images in list views. (If you do find a way to get them squares to  show, I'd love an option to preserve the simple distraction-free view of today!)

**Comment by brentsimmons** [comment] 2020-07-06 02:12
Thanks for the report!

This is actually a duplicate of #127.

**Closed by brentsimmons** 2020-07-06 02:12 UTC
