### ISSUE TITLE
[feature request] Show YouTube video embedded in reader view

### ISSUE THREAD

**Issue by MrHarry123** [Ranchero-Software/NetNewsWire#3623] opened 2022-07-11 12:07 UTC
I really love using NetNewsWire to follow YouTube channels, so I don't have to create a Google account.

Would be really nice though if the reader view would support this by showing the video in an embeded view (preferably the non tracking variant). I can imagine there are also some other video services which would be nice to be supported as well, so it is not only YouTube.

I'm not sure if this is technically possible, but it would be really sweet.

**Comment by vincode-io** [comment] 2022-07-25 23:34
Duplicate of #2538

**Closed by vincode-io** 2022-07-25 23:34 UTC
