### ISSUE TITLE
MacOS: Article URLs with non ASCII characters can not open in browser 

### ISSUE THREAD

**Issue by whexy** [Ranchero-Software/NetNewsWire#1787] opened 2020-02-13 15:07 UTC
MacOS 10.15
Ver 5.0.3(2618)
When trying to open an article in browser (right-click and choose "open in browser", or double-click it), some won't raise my browser up.
I try to find a pattern, and it seems if the article to open has non ASCII characters in its URL, nothing will be open.
For instance,  to open a link [http://www.rfi.fr/cn/中国/20200213-美参议院推决议纪念李文亮](http://www.rfi.fr/cn/中国/20200213-美参议院推决议纪念李文亮). Since it has Chinese characters, the browser (I use Safari as default) won't be open and nothing will show.
Many cases can be found in this feed: [http://cn.rfi.fr/general/rss/](http://cn.rfi.fr/general/rss/)

**Comment by kpreid** [comment] 2020-03-15 15:58
Non-ASCII URLs (or [IRIs](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier) to be technically precise) also appear commonly in Reddit feeds. A workaround is to click the article title link in the right pane, but it'd be nice if this weren't necessary.

**Comment by Wevah** [comment] 2020-07-09 06:55
I can't seem to reproduce this anymore, even on 5.0.3. Are there any more broken examples I could use?

**Comment by Wevah** [comment] 2020-07-09 06:57
Oh, it looks like the http://cn.rfi.fr/general/rss/ feed has started percent-encoding their paths.

**Comment by vincode-io** [comment] 2020-09-03 01:23
This is fixed and will be in an upcoming release.

**Closed** 2020-09-03 01:23 UTC
Labels: macOS
