### ISSUE TITLE
Not working under Big Sur

### ISSUE THREAD

**Issue by timothyarmes** [Ranchero-Software/NetNewsWire#2570] opened 2020-11-13 10:51 UTC
Hi,

NetNewsWire is no longer working for me sing upgrading to Big Sur.  The interface displays no content, and a refesh displays the error 'Unauthorized'.  The console contains this:

```
default	11:48:40.357635+0100	runningboardd	Acquiring assertion targeting [app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] from originator [daemon<com.apple.coreservices.launchservicesd>:117] with description <RBSAssertionDescriptor| "frontmost:80965" ID:169-117-36435 target:80965 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveFocal" sourceEnvironment:"(null)">
	]>
default	11:48:40.357846+0100	runningboardd	Assertion 169-117-36435 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965]) will be created as active
default	11:48:40.359981+0100	runningboardd	Finished acquiring assertion 169-117-36435 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965])
default	11:48:40.360248+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring jetsam update because this process is not memory-managed
default	11:48:40.360310+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring suspend because this process is not lifecycle managed
default	11:48:40.360354+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Set darwin role to: UserInteractiveFocal
default	11:48:40.360385+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring GPU update because this process is not GPU managed
default	11:48:40.360445+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Skipping AppNap state - not lifecycle managed
default	11:48:40.360522+0100	runningboardd	Calculated state for app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>: running-active (role: UserInteractiveFocal)
default	11:48:40.363837+0100	runningboardd	Acquiring assertion targeting [app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] from originator [daemon<com.apple.coreservices.launchservicesd>:117] with description <RBSAssertionDescriptor| "notification:80965" ID:169-117-36436 target:80965 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	11:48:40.363965+0100	runningboardd	Assertion 169-117-36436 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965]) will be created as active
default	11:48:40.365978+0100	runningboardd	Acquiring assertion targeting [app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] from originator [daemon<com.apple.WindowServer(88)>:154] with description <RBSAssertionDescriptor| "FUSBFrontmostProcess" ID:169-154-36437 target:80965 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Frontmost" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
default	11:48:40.366101+0100	runningboardd	Assertion 169-154-36437 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965]) will be created as active
default	11:48:40.366836+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring jetsam update because this process is not memory-managed
default	11:48:40.366873+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring suspend because this process is not lifecycle managed
default	11:48:40.366858+0100	runningboardd	Calculated state for app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>: running-active (role: UserInteractiveFocal)
default	11:48:40.366967+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring GPU update because this process is not GPU managed
default	11:48:40.367249+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Skipping AppNap state - not lifecycle managed
default	11:48:40.367403+0100	runningboardd	Calculated state for app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>: running-active (role: UserInteractiveFocal)
default	11:48:40.367496+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring jetsam update because this process is not memory-managed
default	11:48:40.367568+0100	runningboardd	Finished acquiring assertion 169-117-36436 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965])
default	11:48:40.367604+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring suspend because this process is not lifecycle managed
default	11:48:40.367686+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring GPU update because this process is not GPU managed
default	11:48:40.367821+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Skipping AppNap state - not lifecycle managed
default	11:48:40.367958+0100	runningboardd	Finished acquiring assertion 169-154-36437 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965])
default	11:48:40.389331+0100	NetNewsWire	0x10f4e95e8 - [PID=0] WebProcessCache::setApplicationIsActive: (isActive=1)
default	11:48:40.706372+0100	tccd	AUTHREQ_ATTRIBUTION: msgID=154.2517, attribution={accessing={identifier=com.ranchero.NetNewsWire-Evergreen, pid=80965, auid=503, euid=503, binary_path=/Applications/NetNewsWire.app/Contents/MacOS/NetNewsWire}, requesting={identifier=com.apple.WindowServer, pid=154, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer}, },
default	11:48:40.706423+0100	tccd	requestor: identifier=com.apple.WindowServer, pid=154, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer is checking access for accessor identifier=com.ranchero.NetNewsWire-Evergreen, pid=80965, auid=503, euid=503, binary_path=/Applications/NetNewsWire.app/Contents/MacOS/NetNewsWire
default	11:48:40.719871+0100	tccd	AUTHREQ_SUBJECT: msgID=154.2517, subject=com.ranchero.NetNewsWire-Evergreen,
default	11:48:41.146164+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher <private>
default	11:48:41.146459+0100	NetNewsWire	[Telemetry]: Activity <nw_activity 12:2 [9A31056B-B9A6-4F11-A360-C71B94658222] (reporting strategy default)> on Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> was not selected for reporting
default	11:48:41.146763+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> {strength 0, tls 4, ct 0, sub 0, sig 1, ciphers 0, bundle 0, builtin 0}
default	11:48:41.146878+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> now using Connection 2
default	11:48:41.147031+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> sent request, body N 0
default	11:48:41.909733+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> received response, status 401 content K
default	11:48:41.910204+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> done using Connection 2
default	11:48:41.910296+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> response ended
default	11:48:41.910358+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> summary for task success {transaction_duration_ms=763, response_status=401, connection=2, reused=1, request_start_ms=0, request_duration_ms=0, response_start_ms=763, response_duration_ms=0, request_bytes=241, response_bytes=321, cache_hit=0}
default	11:48:41.910474+0100	NetNewsWire	Task <580D2DF6-6723-4B4F-A23E-70AFB01DED32>.<9> finished successfully
default	11:48:41.912853+0100	NetNewsWire	UNIX error exception: 17
default	11:48:41.915860+0100	NetNewsWire	UNIX error exception: 17
default	11:48:41.961374+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> resuming, timeouts(60.0, 604800.0) QOS(0x21) Voucher <private>
default	11:48:41.961981+0100	NetNewsWire	[Telemetry]: Activity <nw_activity 12:2 [564C9BD8-FE65-404B-B77C-1F3175F449B9] (reporting strategy default)> on Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> was not selected for reporting
default	11:48:41.962455+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> {strength 0, tls 4, ct 0, sub 0, sig 1, ciphers 0, bundle 0, builtin 0}
default	11:48:41.962662+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> now using Connection 2
default	11:48:41.963865+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> sent request, body S 376
default	11:48:42.546050+0100	runningboardd	Invalidating assertion 169-117-36435 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965]) from originator [daemon<com.apple.coreservices.launchservicesd>:117]
default	11:48:42.557363+0100	runningboardd	Invalidating assertion 169-154-36437 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965]) from originator [daemon<com.apple.WindowServer(88)>:154]
default	11:48:42.592447+0100	NetNewsWire	0x10f4e95e8 - [PID=0] WebProcessCache::setApplicationIsActive: (isActive=0)
default	11:48:42.672435+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> received response, status 200 content U
default	11:48:42.672528+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> done using Connection 2
default	11:48:42.673599+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> response ended
default	11:48:42.673746+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> summary for task success {transaction_duration_ms=711, response_status=200, connection=2, reused=1, request_start_ms=0, request_duration_ms=1, response_start_ms=709, response_duration_ms=1, request_bytes=422, response_bytes=586, cache_hit=0}
default	11:48:42.673980+0100	NetNewsWire	Task <99C51646-C112-4CA1-969D-AA63A514D5FC>.<10> finished successfully
default	11:48:42.701908+0100	runningboardd	Calculated state for app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>: running-active (role: UserInteractiveNonFocal)
default	11:48:42.701942+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring jetsam update because this process is not memory-managed
default	11:48:42.702106+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring suspend because this process is not lifecycle managed
default	11:48:42.702290+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Set darwin role to: UserInteractiveNonFocal
default	11:48:42.702379+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring GPU update because this process is not GPU managed
default	11:48:42.702543+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Skipping AppNap state - not lifecycle managed
default	11:48:42.762212+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.766825+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.770363+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.772161+0100	NetNewsWire	possible duplicate, trying to delete invalid items
default	11:48:42.772391+0100	NetNewsWire	no unique id, using 10 attributes from mDbAttributes
default	11:48:42.776731+0100	NetNewsWire	duplicate item exception is real; throwing it on
default	11:48:42.776813+0100	NetNewsWire	caught CssmError during add: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.839793+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.842686+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.845283+0100	NetNewsWire	CSSM Exception: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:42.849212+0100	NetNewsWire	possible duplicate, trying to delete invalid items
default	11:48:42.849808+0100	NetNewsWire	no unique id, using 10 attributes from mDbAttributes
default	11:48:42.856635+0100	NetNewsWire	duplicate item exception is real; throwing it on
default	11:48:42.856792+0100	NetNewsWire	caught CssmError during add: -2147413719 CSSMERR_DL_INVALID_UNIQUE_INDEX_DATA
default	11:48:46.357882+0100	runningboardd	Assertion did invalidate due to timeout: 169-117-36436 (target:[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965])
default	11:48:46.590759+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring jetsam update because this process is not memory-managed
default	11:48:46.590789+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring suspend because this process is not lifecycle managed
default	11:48:46.590775+0100	runningboardd	Calculated state for app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>: running-active (role: UserInteractiveNonFocal)
default	11:48:46.590807+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Ignoring GPU update because this process is not GPU managed
default	11:48:46.590866+0100	runningboardd	[app<application.com.ranchero.NetNewsWire-Evergreen.359372262.359372275(503)>:80965] Skipping AppNap state - not lifecycle managed

```

**Comment by vincode-io** [comment] 2020-11-13 11:28
Have you tried rebooting your computer since you had trouble launching NetNewsWire?  Apple was having some problems with Gatekeeper yesterday and this might have something to do with it.

If that doesn't fix your problem, could you try deleting and downloading NetNewsWire 5.1.3 again and see if it works for you?

**Comment by kevinm6** [comment] 2020-11-15 19:10
It happened the same here.
I followed what @vincode-io said and it works. 
The problem with Big Sur was that NNW wasn’t syncing or refreshing, even if I forced it: the progress bar on the bottom was stuck every time on "3 of 11”. 
After deleting the app and all of its data, included all the plist, Application Support files and so on, I’ve installed again the app, login into Feedly and everything works as expected.

**Comment by timothyarmes** [comment] 2020-11-16 09:30
Well, I've:

Updated the the very latest version of Big Sur
Deleted NNW, the plists and the data in the Application Support folder
Reinstalled NNW

I can't add Feedly.  Attempting to do so results this error (authenticating with Google):

![image](https://user-images.githubusercontent.com/1092550/99235863-b1998b00-27f6-11eb-9f77-5caeded2be90.png)

**Comment by kevinm6** [comment] 2020-11-16 09:50
I can’t help you. The mainly difference is that my authentication is with Apple in Feedly.
It seems to me, that the problem is the authentication process of Google in Big Sur, maybe Google must update their process with the new version of macOS.

**Comment by timothyarmes** [comment] 2020-11-16 09:56
I've just created extra logins on Feedly, including a simply email address and password. Both fail with exactly the same error message.

**Comment by kevinm6** [comment] 2020-11-16 10:01
So, it could be a error of macOS Keychain. 
Try to search into keychain if there are some expired certificates, keys, or delete everything about NNW in the Keychain.
Delete again the app and all of its files and try again. 
Is the only help I can give you for my knowledge.

**Comment by vincode-io** [comment] 2020-11-16 17:04
@timothyarmes Have you renamed the app to something other than NetNewsWire.app?  If so, that can cause problems with our current keychain implementation in some cases.

**Comment by timothyarmes** [comment] 2020-11-16 17:08
It's interesting that you ask.  For a while it was called NetNewsWire-2.app (presumably since there was already one in the downloads folder).  I remember that I deleted the original and renamed the new one to just NetNewsWire.  I think all that was before the Big Sur upgrade, and it was working.

Since then however I've deleted it completely and re-installed (with the default name), so I can't see why they'd be an issues now.

**Comment by vincode-io** [comment] 2020-11-16 17:13
That is probably the problem you are having.  Read through this solution to see if it can help you can get your keychain sorted out.  https://github.com/Ranchero-Software/NetNewsWire/issues/2419#issuecomment-692412390

**Comment by timothyarmes** [comment] 2020-11-16 17:28
Wow, that worked.  Thanks, I'd never have found that.

It's definitely a problem though, since I didn't even rename it on purpose, I just happened to have an old version in my downloads folder.  Is there nothing that can be do to improve the use experience here?

**Comment by vincode-io** [comment] 2020-11-16 17:58
We're working on it.  Issue #2419.  I'm closing this one out since it is a duplicate of that one.

**Closed by vincode-io** 2020-11-16 17:58 UTC
