### ISSUE TITLE
Titles of renamed feeds aren't respected when importing subscriptions in MacOS

### ISSUE THREAD

**Issue by tynandebold** [Ranchero-Software/NetNewsWire#2205] opened 2020-07-04 10:03 UTC
If a feed is renamed, that new designation isn't respected when importing subscriptions from a NNW-generated `opml` file.

Specific case:
- I subscribe to [this feed](https://hnrss.org/whoishiring/jobs?q=london+OR+berlin)
- I rename it to _Who's hiring (london || berlin)?_
- That feed is represented in my exported `subscriptions.opml` file as:
  - `<outline text="Who's hiring (london || berlin)?" title="Who's hiring (london || berlin)?" description="" type="rss" version="RSS" htmlUrl="https://news.ycombinator.com/item?id=23379196" xmlUrl="https://hnrss.org/whoishiring/jobs?q=london+OR+berlin"/>`
- When importing the subscriptions file, the feed name defaults to this: _Ask HN: Who is hiring? (July 2020)_, which is the value set in the `title` tag of the xml feed, not the `title` tag found in the exported subscriptions file. I expect the title to be _Who's hiring (london || berlin)?_

In the current implementation, I'm guessing the `title` tag from the feed itself outweighs the renamed `title` attribute in the `opml` file, though I'm expecting the behavior to be the opposite.

**Comment by jrus** [comment] 2021-01-26 15:46
This seems like a duplicate of https://github.com/Ranchero-Software/NetNewsWire/issues/609

Also seems like a bug to me. Needing to manually rename a large list of feeds which explicitly had their titles set in the OPML file is very tedious and frustrating.

**Comment by tynandebold** [comment] 2021-01-26 17:40
You're right, it's a duplicate.

And indeed, quite a pain to do this manually.

**Comment by vincode-io** [comment] 2021-01-26 21:35
Duplicate of #609.

**Closed by vincode-io** 2021-01-26 21:35 UTC
