### ISSUE TITLE
Footnotes Not Working With Articles From Feedly

### ISSUE THREAD

**Issue by Nonameentered** [Ranchero-Software/NetNewsWire#2371] opened 2020-08-21 02:43 UTC
Normal clicks do not do anything. 3D/Force/Haptic touch is able to open the link.
Footnote example here: https://daringfireball.net/2020/08/applespeak_to_english_xbox_game_pass.

**Comment by ybbond** [comment] 2020-11-05 14:08
Seconded this

**Comment by brehaut** [comment] 2020-11-20 22:46
I can reproduce this on macOS NNW as well as in iOS. 

It looks like feedly is rewriting the document in some fashion that is throwing off the newsfoot script. Looking in the developer console, whenever the link inside the `.newsfoot-footnote-container` element is clicked I’m seeing a log for

`TypeError: null is not an object (evaluating 'document.querySelector(`[id='${targetId}']`).innerHTML') newsfoot.js: 147`

Looking at the DOM for the footnotes it appears feedly is stripping off the id's from the footnotes themselves, making the above query fail.

I’m not sure if theres necessarily a good work around here. If we could get a small corpus of examples from sites other than Daring Fireball we could figure out a plan.

At a baseline, it probably pays to check the return value of the `querySelector` call and fallback to browser default behaviour if we can't handle it ourselves.

Secondly, at least in the case of Daring Fireball, we have enough information in the footnote reference link and the footnote's return link to stitch together the content. I'm hesitant to build that special case until we know how other sites markup is affected.

**Comment by vincode-io** [comment] 2020-11-20 22:59
Here is another blog that uses footnotes that has the same issue.  https://pxlnv.com/feed/json

Here is an example that you can pull up in NNW on a Feedly account.

[Reviewers See Simultaneous Gains in Performance and Battery Life With Apple’s First M1 Macs](https://pxlnv.com/linklog/m1-mac-reviews/)

**Comment by ybbond** [comment] 2020-11-21 18:11
first, for @brentsimmons , I want to clarify. You added "iOS" label for this issue, but this is also happen for macOS version.

second, is there anyone already working on this issue?
I took a little inspection with NNW's inspect element for DaringFireball, MacStories and some other sites fetched from both Feedbin and Feedly. I also take a look at the current `newsfoot.js`. If there is currently no one tackling this, I might try to modify `newsfoot.js`.

I notice that current `newsfoot.js` works very well with Daring Fireball's articles fetched from Feedbin —the [`installContainer`](https://github.com/Ranchero-Software/NetNewsWire/blob/d9c117fc5905a3538cd3123a79011d0df89f2713/Shared/Article%20Rendering/newsfoot.js#L146), and the [`scrollTo`](https://github.com/Ranchero-Software/NetNewsWire/blob/d9c117fc5905a3538cd3123a79011d0df89f2713/Shared/Article%20Rendering/newsfoot.js#L160) function. While the script can only do the `installContainer` for articles from other websites (e.g. MacStories).

**Comment by vincode-io** [comment] 2021-03-16 19:14
This got fixed in one of the more recent releases.

**Closed by vincode-io** 2021-03-16 19:14 UTC
Labels: iOS, macOS
