### ISSUE TITLE
Feature request: traditional view for timeline and article

### ISSUE THREAD

**Issue by ucbsm** [Ranchero-Software/NetNewsWire#796] opened 2019-07-07 14:43 UTC
Hoping "Layout" option(s) might be implemented, as in NNW3. (as in attached screenshot)

![Screen Shot 2019-07-07 at 10 41 22 AM](https://user-images.githubusercontent.com/52629457/60769964-fb6f4e80-a0a3-11e9-9b93-994015233e99.png)

**Comment by timmerk** [comment] 2019-08-13 04:45
Seconded - the "Traditional View" in NNW3 is one of the main reasons I still use it over the other Mac RSS readers out there.

**Comment by JayBrown** [comment] 2019-08-26 14:23
Definitely second that. If you implement this, I'll leave my **[Vienna](https://github.com/ViennaRSS/vienna-rss)** exile and return to NNW.

**Comment by chicagobob** [comment] 2019-08-30 02:59
Ditto.  Came here to search open issues just looking for this one.  Even though I'm already sold on NNW5, this would be really great IMHO.

**Comment by noahkuhn** [comment] 2019-09-06 13:19
+1 Yes, this is necessary.

**Comment by tompave** [comment] 2019-11-10 19:09
+1

The usability of a layout is highly subjective. The current 3 column "modern" one is not the best for everyone.

**Comment by tompave** [comment] 2019-11-10 19:11
Actually, I think that this is a duplicate of https://github.com/brentsimmons/NetNewsWire/issues/102.

**Comment by vincode-io** [comment] 2020-03-20 11:48
Duplicate of #102.

**Closed by vincode-io** 2020-03-20 11:48 UTC
