### ISSUE TITLE
Title HTML does not appear to be escaped correctly

### ISSUE THREAD

**Issue by thegengen** [Ranchero-Software/NetNewsWire#2333] opened 2020-08-13 12:29 UTC
Only verified on macOS since I don't have the iOS version of NetNewsReader. Here's a picture of what's happening.

<img width="2332" alt="Screen Shot 2020-08-13 at 15 24 54" src="https://user-images.githubusercontent.com/36608/90134169-6bf1a000-dd79-11ea-9d2c-979e4dd58a0d.png">

The article is here: https://kilianvalkhof.com/2020/javascript/supercharging-input-type-number/ 
Thank you so much for your delightful app. Let me know if there's anything else I can do to help.

**Comment by brentsimmons** [comment] 2020-08-13 23:02
What’s the URL of the feed you’re subscribed to?

**Comment by thegengen** [comment] 2020-08-14 06:49
Oh, duh! It's https://sidebar.io/feed.xml

**Comment by brentsimmons** [comment] 2023-03-06 04:58
Duplicate of #722

**Closed by brentsimmons** 2023-03-06 04:58 UTC
