### ISSUE TITLE
Can't watch Youtube subscription videos directly on mac and ios

### ISSUE THREAD

**Issue by lingsir996** [Ranchero-Software/NetNewsWire#3533] opened 2022-04-18 02:59 UTC
Although you can subscribe to NetNewsWire directly through the Youtube URL, you can only see the title and not the specific embedded video, while Reeder, the rss reader, can, and hopefully will fix this problem.

**Comment by vincode-io** [comment] 2022-05-26 19:29
Duplicate of #2538

**Closed by vincode-io** 2022-05-26 19:29 UTC
