### ISSUE TITLE
Feature request: restore folder expansion state on launch

### ISSUE THREAD

**Issue by ucbsm** [Ranchero-Software/NetNewsWire#795] opened 2019-07-07 14:39 UTC
If "Folders" are expanded upon application Quit, would be nice if they remained expanded upon app relaunch...

**Comment by HillbillyInBC** [comment] 2019-08-10 16:35
Seconded. Yet another missing feed organization feature that will keep me on NNW4.

**Comment by ssgelm** [comment] 2019-08-22 04:50
Yes please!  This one is driving me crazy. :)

**Comment by macdaddy1944** [comment] 2019-08-28 23:36
Second this request. I haven't gone back to 4 yet but having to expand each folder every time I launch the app is a major waste of time.

**Comment by dkocher** [comment] 2019-08-29 12:39
Duplicate for #562.

**Comment by vincode-io** [comment] 2020-01-08 00:57
I'm closing this as a duplicate of #562.

**Closed by vincode-io** 2020-01-08 00:57 UTC
