### ISSUE TITLE
Localization Proposal

### ISSUE THREAD

**Issue by stuartbreckenridge** [Ranchero-Software/NetNewsWire#3790] opened 2022-12-22 05:41 UTC
### Current State

The codebase makes extensive use of `NSLocalizedString`s, generally in the format of:

`NSLocalizedString("Are you sure you want to delete the “%@” feed?", comment: "Feed delete text")`

or, in SwiftUI:

`Text("Are you sure you want to delete the “%@” feed?", comment: "Feed delete text")`

With no changes to the above, a Localization Export would generate an `en.xcloc` file using the `NSLocalizedString` value as the key and English (development language) translation:

|Key|English|Comment|
|---|---|---|
|Are you sure you want to delete the “%@” feed?|Are you sure you want to delete the “%@” feed?|Feed delete text|

Further, all `NSLocalizedString`s—just over 300 for the iOS target—would end up in a single `Localizable.strings` file. 

![image](https://user-images.githubusercontent.com/7046652/209063275-73bc24e5-f8bc-49b9-b49e-2f36d1f158f1.png)

---

### Keys

- Keys should be keys and not a mirror of the development language.
    - This ensures that changes to the base translation don't affect the key. (If the base language is used as the key, and the base translation changes, all translations for the old key would need to be reapplied to the new key. With this approach, you can change the base translation without impacting the key or other language translations.)  
    - This makes it easier to spot non-localized strings at runtime.
    - It removes English norms from the keys (grammar, punctuation).
- They should follow as consistent a format as possible:
	- `<ui_element>.<ui_position>.<optional_action>.<optional_variables>`

Concretely, non-localized strings would display as keys, while localized strings would display translated:

![Friday, 23 Dec 2022 21:30:32](https://user-images.githubusercontent.com/7046652/209344206-e9b79844-0a25-4a1d-aac0-c810754da100.png)

In code, this approach would manifest as follows:

`NSLocalizedString("button.title.markallasread.%@, comment: "Mark All as Read in ”feed”. The variable is the feed name.")`

In `*.strings`:

```
/* Mark All as Read in ”feed”. The variable name is the feed name. */
"button.title.markallasread.%@" = "Mark All as Read in ”%@”";
```

In `xcloc`: 

|Key|English|French|Comment|
|---|---|---|---|
|button.title.markallasread.%@|Mark All as Read in “%@”|Marquez tout comme lu dans “%@”|Mark All as Read in ”feed”. The variable name is the feed name.|

### Comments

- All strings that require localization should be audited to ensure that their `comment` clearly articulates the purpose.
- All strings that require localization from here on must include a clear comment.
- Where strings have multiple variables, the comment must describe the ordering.

### Organisation

As discussed above, without changes everything will end up in a single `Localizable.strings` file. 

For the main targets, this proposal suggests (though it is not required) taking an active approach and defining [where our `strings` will live](https://developer.apple.com/videos/play/wwdc2021/10221/?time=547) based on the screen/major feature in which they are being used:

`Feeds.strings`
`Timeline.strings`
`Article.strings`
`Settings.strings`

`NSLocalizedString("alert.message.deletefeed.%@", tableName: "Feeds" comment: "Alert: delete feed confirmation message")`

The only exclusion to this would be strings that are common, e.g., basic button titles like "Done", "Dismiss", or "Cancel". They can be included in a `Shared.strings` file and shared amongst the targets.

`NSLocalizedString("button.title.done", tableName: "Shared" comment: "Button title: Done")`
`String(localized: "button.title.done", table: "Shared", comment: "Button title: Done")`
`Text("button.title.done", table: "Shared", comment: "Button title: Done")`

Extensions (Share, Widget, etc.) are small enough that their translations can be stored in their own `Localizable.strings` file.

### Future Translations

For each release, we will need to be disciplined to ensure that new strings are localized. The way I see this working is as follows:

1. `Text("button.title.addmastodonuser", table: "Settings", comment: "Button title: adds a Mastodon user feed")`
2. We do an Export Localization
3. Add the Base Localization (English) and Import
4. Prior to Release, Export again and translators update `es`, `fr` files (etc)
5. We import, test...
7. ...and then we should be good to go.

### Updates to Existing Translations

Updates to existing translations must be done in existing `.strings` files. Xcode will not overwrite _existing_ translations on import.

**Comment by vincode-io** [comment] 2022-12-23 19:50
Please change this to a comment in #78. Duplicate of #78.

**Closed by vincode-io** 2022-12-23 19:50 UTC

**Comment by stuartbreckenridge** [comment] 2022-12-23 22:35
Done.

**Comment by stuartbreckenridge** [comment] 2022-12-23 22:41
@vincode-io Note that this is an architectural proposal that underpins all other open Localization feature requests: #78, #849, #850, #851, #1749, and #2140.
