### ISSUE TITLE
MacOS: Article Image Zoom

### ISSUE THREAD

**Issue by coffeewhisky** [Ranchero-Software/NetNewsWire#3278] opened 2021-09-07 12:51 UTC
On iOS, images in articles that are larger than the article display window can be clicked on and will show full screen. Can this be added to the MacOS version of NNW?

Ideally this would be like a QuickLook window for embedded images, and is how the desktop Apple News application works.

**Comment by vincode-io** [comment] 2021-09-07 16:56
Duplicate of #647.

**Closed by vincode-io** 2021-09-07 16:56 UTC
