### ISSUE TITLE
Feature Request: Select text in Fullscreen mode

### ISSUE THREAD

**Issue by Alex-Vasile** [Ranchero-Software/NetNewsWire#3565] opened 2022-05-18 23:17 UTC
Currently when fullscreen mode is turned on in the iOS version you are no longer able to select text. Trying to do so will bring up a strange long-press / sharing view.

**Comment by vincode-io** [comment] 2022-05-26 19:58
Duplicate of #3287

**Closed by vincode-io** 2022-05-26 19:58 UTC
