### ISSUE TITLE
iOS Import opml not working.

### ISSUE THREAD

**Issue by lanox** [Ranchero-Software/NetNewsWire#1547] opened 2020-01-07 01:08 UTC
Hi

Firstly I love NetNewsWire, it is a rss reader I was looking for.

I am trying to import my opml from mac NetNewsWire, however the file is greyed out and I cant select it.

Steps I am doing:

1. Export from mac NetNewsWire save it to iCloud
2. Go to iOS -> settings-> Import Sub -> Select iCloud Drive
3. I can see the file however it is greyed out and I can't click on it.

I am not sure if I am doing something wrong, however this use to work when I did it earlier in December.

Thanks

L

**Comment by brentsimmons** [comment] 2020-01-07 01:12
It’s a bug — we’re working on it. :)

Duplicate of #1443.

**Closed by brentsimmons** 2020-01-07 01:12 UTC

**Comment by lanox** [comment] 2020-01-07 01:14
so sorry, should of done a search rather then wing straight away.

**Comment by brentsimmons** [comment] 2020-01-07 01:15
Quite alright. It’s our job, not yours, to groom the bugs database. 👍

**Comment by vincode-io** [comment] 2020-01-07 01:29
Closing since this is a duplicate.
