### ISSUE TITLE
iOS: AccountView Service icons are misaligned horizontally

### ISSUE THREAD

**Issue by flowinho** [Ranchero-Software/NetNewsWire#1886] opened 2020-03-12 17:58 UTC
In the Settings View the icons for Feedly and FeedBin are slightly misaligned and their horizontal edges do not align with the table view separators.

This an easy fix but improves visual quality a lot.

![Image](https://i.imgur.com/FI8gUtv.jpg)

**Comment by vincode-io** [comment] 2020-03-12 18:03
Believe it or not, we spent quite a bit of time debating about how to correctly align those icons.  They do actually look better overhanging the separator like that, but of course that is subjective.  Anyway, I'm closing this one since this is very much by design.

**Closed by vincode-io** 2020-03-12 18:03 UTC
