### ISSUE TITLE
"iCloud and iCloud" wording in error

### ISSUE THREAD

**Issue by Leland** [Ranchero-Software/NetNewsWire#3797] opened 2022-12-29 01:49 UTC
The error itself is fine (I needed to log in again), but the wording is a bit strange. 

Version: Version 6.1.1b1 (6107)

macOS 12.5.1 (21G83)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/714017/209892960-9810354d-2ffc-49b2-9e28-dd3ffd4650e9.png">

**Comment by jez** [comment] 2022-12-31 07:04
For what it's worth, I had this same bug just now, and I don't think my problem is that I'm not signed in—all my other iCloud accounts on the laptop are working.

Version 6.1 (6106)

**Comment by vincode-io** [comment] 2023-01-13 22:56
Duplicate of #3610

**Closed by vincode-io** 2023-01-13 22:56 UTC
