### ISSUE TITLE
card/grid view

### ISSUE THREAD

**Issue by bingoxo** [Ranchero-Software/NetNewsWire#3355] opened 2021-11-18 23:31 UTC
Can you please add it ?

example : 
![3LK7PFFvUfu_vZbSsZAYNYfc3afLS4GdY6vdJOS30DI](https://user-images.githubusercontent.com/49401307/142513093-ea570dfd-2b89-44d4-9428-aa4768161762.jpg)

**Comment by vincode-io** [comment] 2021-11-18 23:33
Duplicate of #1551

**Closed by vincode-io** 2021-11-18 23:33 UTC
