### ISSUE TITLE
6.0a4: Yotube thumbnails aren't showing when using iCloud sync

### ISSUE THREAD

**Issue by eivindml** [Ranchero-Software/NetNewsWire#2834] opened 2021-02-25 11:35 UTC
Youtube RSS feeds doesn't show the thumbnail/video player when using iCloud as a syncing service. See screenshot.

<img width="1440" alt="Skjermbilde 2021-02-25 kl  12 29 52" src="https://user-images.githubusercontent.com/202450/109147863-cd9db880-7765-11eb-97ee-c19743a85ca2.png">

**Comment by vincode-io** [comment] 2021-02-25 21:18
Duplicate of #2538.

**Closed by vincode-io** 2021-02-25 21:18 UTC
