### ISSUE TITLE
iCloud Sync problem

### ISSUE THREAD

**Issue by rsalmei** [Ranchero-Software/NetNewsWire#3253] opened 2021-08-14 17:40 UTC
Last night I changed the organization of a few feeds via the iOS app. I only created a new folder, and moved five feeds to it.
Now, when I look at my desktop app, the folder is created and have the correct name, but is empty. Those feeds are gone there.
I tried to reboot (and maybe wait icloud refresh itself), but nope. Refresh in both apps also do not help.
Please what can I do?

Edit: Well, on the mobile again, I dragged one feed to another folder. It immediately appeared on desktop, but empty 😞, no posts whatsoever. Hitting refresh on desktop made it gather posts like it was the first time, thus it lost some older ones, which I hadn't read yet 😞😞.

**Comment by vincode-io** [comment] 2021-08-18 01:02
This is actually a duplicate of #3047 which is fixed in the upcoming NNW for Mac 6.0.3 release.

I recommend you remove and add your iCloud account on your Mac again to get it back in sync.

**Closed by vincode-io** 2021-08-18 01:02 UTC
