### ISSUE TITLE
Large Emoji

### ISSUE THREAD

**Issue by cdevroe** [Ranchero-Software/NetNewsWire#2026] opened 2020-04-28 14:44 UTC
The fix for this on Mac may come from the work done on #1666 but I am unsure. 

<img width="623" alt="Screen Shot 2020-04-28 at 10 43 31 AM" src="https://user-images.githubusercontent.com/19237/80501175-2087c300-893d-11ea-8c01-1d28c15eda25.png">

I am unsure exactly what to suggest other than the emoji size should likely correspond to the type size.

**Comment by brentsimmons** [comment] 2020-04-28 18:25
This looks like the same issue. The issue is that it’s not really an emoji — it’s a graphic.

**Comment by vincode-io** [comment] 2020-04-28 19:16
I just checked and this is a duplicate of #1666 and is fixed by it.

**Closed by vincode-io** 2020-04-28 19:16 UTC

**Comment by cdevroe** [comment] 2020-04-28 19:17
Thanks @vincode-io & @brentsimmons
