### ISSUE TITLE
Reader view caches website content for too long. No easy way to refresh cache. 

### ISSUE THREAD

**Issue by caffeinepickles** [Ranchero-Software/NetNewsWire#3805] opened 2023-01-03 10:03 UTC
**Edit:** 
I have been served the  old version of my article for quite a while. In my frustration I removed and re-subscribed to the feed several times and still got the older version of the article in reader view. The issue is that it was hard-cached in the in-app storage. I deleted the app and data via iOS settings and reinstalled it. Only then the cache was deleted. Finally i cloud render the fresh version of the article in reader view. Everything works fine now. 

However, on macOS I was not able to delete the cached version of the article, not knowing where to find said cache. I still see the days old broken version of my article. 

**Suggestions:**
1. Can we have control over the cache policy in settings? 
2. Alternatively how about a fresh re-render of the html inside the reader view on pull-down action?

---

**Initial post:** 

I added my own feed to NetNewsWire. While the feed entry preview works flawlessly NetNewsWire has a problem loading images when prompted to render the article in reader view. My html code is as clean as it gets. The <img> objects have a sane size, absolute data paths and everything. Unfortunately I only get empty placeholder boxes. Clicking the boxes starts a loading animation. The images never load. Since I can't see what is happening in the background, I don't know what is going on. I tested the reader of Feeder for android and the images load just fine. So do they when I open a browser's reader view. 

Any ideas? Is this a bug?

**Comment by sbaildon** [comment] 2023-01-05 13:38
I have blitzed this directory to reset my local feed list. `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application\ Support/NetNewsWire/Accounts/OnMyMac/`

**Comment by vincode-io** [comment] 2023-01-13 23:32
It is actually WKWebView doing the caching here or the service that we use to generate the Reader View HTML. Most likely it was the service having an issue with the conditional get information.

I'm going to close this issue as a duplicate of #3493 since we would use the same API call to clear both cookies and web content.

**Closed by vincode-io** 2023-01-13 23:32 UTC
