### ISSUE TITLE
Feature request: ability to filter feeds from smart filter 

### ISSUE THREAD

**Issue by milesmcclane** [Ranchero-Software/NetNewsWire#1887] opened 2020-03-12 20:10 UTC
As the title says, there are several feeds I follow which I just want to look at periodically, and would like to be able to not have them clutter up the today filter. 

Awesome work on this app btw. Just what iOS was crying out for. So excited!

**Comment by brentsimmons** [comment] 2020-03-12 20:11
What do you mean by filtering feeds?

**Comment by milesmcclane** [comment] 2020-03-12 20:13
Sorry weird phone glitch, posted to early - had to edit comment.

**Comment by Brookke** [comment] 2020-03-16 15:47
This would be super useful maybe something like the below could work?
![Untitled 3](https://user-images.githubusercontent.com/10200358/76775499-5746b700-679d-11ea-90d3-659c5b82b9b5.png)

**Comment by thefranke** [comment] 2021-07-08 11:17
+1 for this feature. Vienna-RSS has smart folders which have a bunch of possible conditions: Read status, subject, author and folder queries etc. Perhaps this could be used as a template. Those folders are great to sift through heavy streams which have hundreds of posts a week or even a day.

<img width="721" alt="Screenshot 2021-07-08 at 13 17 28" src="https://user-images.githubusercontent.com/834956/124912989-e3ae6600-dfee-11eb-8c5c-2966a5c02fe3.png">

**Comment by brentsimmons** [comment] 2023-03-06 03:09
Duplicate of #217

**Closed by brentsimmons** 2023-03-06 03:09 UTC
