### ISSUE TITLE
iOS and Mac clients out of sync through Feedly

### ISSUE THREAD

**Issue by NeilCadsawan** [Ranchero-Software/NetNewsWire#3711] opened 2022-10-05 15:32 UTC
I've been noticing the past week or so that my iOS and Mac clients aren't staying in sync. iOS client version 6.0.2 (Build 610). Mac client 6.1 (6106)

Screenshots taken seconds apart after refreshing feeds:
![IMG_6899](https://user-images.githubusercontent.com/73011244/194100681-85f0a8a5-96c2-4052-bd95-b0c242e7dde2.PNG)

<img width="1902" alt="Screen Shot 2022-10-05 at 8 16 57 AM" src="https://user-images.githubusercontent.com/73011244/194100757-12653d45-7aa5-4b91-8bca-cab8f917d6c4.png">

**Comment by NeilCadsawan** [comment] 2022-10-05 17:09
I just marked all as read on the Mac client and then refreshed. Then I refreshed the iOS client. This is the result:

![Screen Shot 2022-10-05 at 10 06 55 AM](https://user-images.githubusercontent.com/73011244/194120124-3acc4294-0a69-419e-8b9a-18bec7aac599.png)

![IMG_6900](https://user-images.githubusercontent.com/73011244/194120237-0412315f-48b9-467c-b746-e1ddf78e98d0.PNG)

The iOS client increased the unread count!

**Comment by vincode-io** [comment] 2022-10-05 17:34
That doesn't tell me anything. Could you do the starred test that I described above?

**Comment by vincode-io** [comment] 2022-10-05 18:13
At the very least, sign on to the Feedly web interface and let me know if your iPhone or Mac matches the unread count you see there.

**Comment by NeilCadsawan** [comment] 2022-10-05 20:37
Okay, so here's what I did, and the results:

1. Signed into Feedly.com and marked everything as read.
2. Refreshed both iOS and Mac Clients
3. Both clients were reset to all read.
4. Waited for new updates to feeds (aka went to lunch)
5. Afterwards, checked on unread status on Feedly
6. Both iOS and Mac clients correctly matched Feedly unread count.
7. Picked one folder (F1) and marked as read on iOS, updated.
8. Refreshed Feedly and Mac client. F1 not update as being read on both Feedly and Mac client
9. Picked a different folder on Mac client (F2) and marked as read, then updated
10. Refreshed Feedly and iOS client. F2 did not update on Feedly and iOS client
11. On Feedly, marked F1 and F2 as read, updated
12. Refreshed iOS and Mac clients. Both clients now show F1 and F2 as being read.

So, it seems that both clients are reading from Feedly correctly, but the "read" statuses aren't making it back to Feedly.

**Comment by vincode-io** [comment] 2022-10-05 20:43
On your Mac, I need you to get a file for me so that I can diagnose it.

Inside of `~/Library/Containers/com.ranchero.NetNewsWire-Evergreen/Data/Library/Application Support/NetNewsWire/Accounts` you will find a folder that starts with `16_`. Inside that folder is a file called `Sync.sqlite3`. I need you to zip that file and attach it with your next comment.

**Comment by NeilCadsawan** [comment] 2022-10-05 20:49
[Sync.sqlite3.zip](https://github.com/Ranchero-Software/NetNewsWire/files/9718888/Sync.sqlite3.zip)

**Comment by vincode-io** [comment] 2022-10-05 22:32
Thank you so much for the database file. I was able to diagnose the problem and it wasn't what I thought it would be! I'll follow up with details in my next comment.

For you, I would remove the Feedly account in NetNewsWire from your iPhone and your Mac and you should be back in business. We'll release a NetNewsWire update in the future that prevents this issue in the future.

**Comment by vincode-io** [comment] 2022-10-05 22:36
The root cause of this problem was the number of read statuses that were trying to be synced. Feedly doesn't have the limit documented, but we hit it. There were over 3400 entries trying to be marked as read. The NetNewsWire code for Feedly syncing doesn't try to chunk these into multiple requests, so we send the full shot and Feedly sends an error message back.

We should chunk these up into requests of 300 status updates so that we don't hit the Feedly limit.

**Comment by NeilCadsawan** [comment] 2022-10-05 22:53
Thanks for helping resolve this issue. It's much appreciated.

**Comment by miguelandres** [comment] 2022-10-19 15:25
Thanks for the update, @vincode-io. 

I had the same issue, and the reasoning behind this of course makes sense to me ( I was on vacation for a while and I don't read my feeds consistently so I forced "inbox zero" at some point and I'm pretty sure it was 1000~ articles).

*If I'm reading this correctly this is planned to be fixed by version 6.2, right?*

**Closed** 2022-10-28 20:53 UTC

**Comment by vincode-io** [comment] 2022-10-29 00:08
We are actually going to fix this in 6.1 now.
