### ISSUE TITLE
Feature Request: Authenticated Feeds?

### ISSUE THREAD

**Issue by hjdhjd** [Ranchero-Software/NetNewsWire#3558] opened 2022-05-14 16:55 UTC
Would love to use NetNewsWire across the board, but it seems that authenticated RSS feed support is missing, or I just haven’t figured out how to enable it. 😄 

The most straightforward example is The Information. They have a paywalled authenticated feed at:

https://www.theinformation.com/subscriber_feed

There’s a non-paywalled version at: 

https://www.theinformation.com/feed

I know the authenticated feed works in other RSS readers that support it (e.g. News Explorer on iOS/Mac). I’d love to be able to use NetNewsWire with this - I’ve actually got a few RSS feeds with this issue.

Thanks! Terrific project and contributions to the community.

**Comment by vincode-io** [comment] 2022-05-26 19:44
Duplicate of #502

**Closed by vincode-io** 2022-05-26 19:44 UTC
