### ISSUE TITLE
Feature request: Sort folders to the top

### ISSUE THREAD

**Issue by lilyball** [Ranchero-Software/NetNewsWire#916] opened 2019-08-30 18:04 UTC
Folders right now (Feedbin tags) seem to be sorted to the bottom of the list. I'd much rather have them at the top, because the feeds I've tagged are more important than the ones I haven't.

**Comment by vincode-io** [comment] 2020-02-27 23:29
Duplicate of #809.

**Closed by vincode-io** 2020-02-27 23:29 UTC
