### ISSUE TITLE
Twitter embeds cut off

### ISSUE THREAD

**Issue by Paul-Theron** [Ranchero-Software/NetNewsWire#2219] opened 2020-07-06 12:55 UTC
I use NetNewWire almost exclusively to follow finance Twitter account (I use a secondary app to generate RSS feeds for the people that I follow). A week ago disaster struck - the bottom is chopped off the content right hand reader view. See example below.

Any tips on how to avoid this?

<img width="600" alt="Screenshot 2020-07-06 at 13 26 28" src="https://user-images.githubusercontent.com/67904862/86595218-af960480-bf98-11ea-91c3-ae13fb6cc3f4.png">

**Comment by vincode-io** [comment] 2020-07-06 13:28
Duplicate of #2166

**Closed by vincode-io** 2020-07-06 13:28 UTC
