### ISSUE TITLE
Feedly and YouTube: some feeds are missing in macOS version, are visible in the iOS version (and in Feedly online)

### ISSUE THREAD

**Issue by facconi** [Ranchero-Software/NetNewsWire#2892] opened 2021-03-16 08:45 UTC
Good morning.
I'm using NNW 6 and NNW 5 on macOS Bigsur, and NNW on iOS. All of them sync with my Feedly account.
I'm following a few YouTube channels, and mostly all of them are visible in both iOS and macOS versions of NNW.
One of them is never visible in the macOS version.

I have added the channel in Feedly using the following URL:
https://www.youtube.com/c/GemBoyOfficial/videos

How can I help to debug more this issue?
Thank you very much.

**Comment by vincode-io** [comment] 2021-03-16 14:39
Duplicate of #2538

**Closed by vincode-io** 2021-03-16 14:39 UTC
