### ISSUE TITLE
[Feature request] Filter feeds with keywords or tags

### ISSUE THREAD

**Issue by ramanujansrinath** [Ranchero-Software/NetNewsWire#3332] opened 2021-11-02 00:30 UTC
A set of persistent filtering rules per feed.

Some feeds have tags in the title like "[Mac] title" or "[iOS] title". It would be great to filter out items, and mark the rest as read.

**Comment by vincode-io** [comment] 2021-11-02 00:32
Duplicate of #1864

**Closed by vincode-io** 2021-11-02 00:32 UTC
