### ISSUE TITLE
Location of view jumps whenever iPhone is locked

### ISSUE THREAD

**Issue by dlfivefifty** [Ranchero-Software/NetNewsWire#2225] opened 2020-07-07 14:46 UTC
Whenever the iPhone locks, or if I switch apps, where I was reading gets lost as the view jumps back to the top. This is on v5.0.1

**Comment by vincode-io** [comment] 2020-07-07 16:33
Duplicate of #2075

**Closed by vincode-io** 2020-07-07 16:33 UTC
